using System.Text;
using LUSharpApiGenerator.Models;

namespace LUSharpApiGenerator.Generation;

public class EnumGenerator
{
    private readonly CSharpNaming _naming;

    // Hand-written enums to skip
    private static readonly HashSet<string> SkipEnums = new()
    {
        "AssetType", "AvatarItemType", "Axis", "BulkMoveMode", "CameraMode",
        "CollisionFidelity", "ContentSourceType", "CreatorType",
        "DevCameraOcclusionMode", "DevComputerCameraMovementMode",
        "DevComputerMovementMode", "DevTouchCameraMovementMode",
        "DevTouchMovementMode", "IKCollisionsMode", "JoinSource",
        "MatchmakingType", "Material", "MembershipType", "ModelLevelOfDetail",
        "ModelStreamingMode", "NormalId", "PartType", "PlayerExitReason",
        "RaycastFilterType", "RenderFidelity", "RotationOrder", "RunContext",
        "SecurityCapability", "SurfaceType"
    };

    public EnumGenerator(CSharpNaming naming)
    {
        _naming = naming;
    }

    public int Generate(List<ApiEnum> enums, string apiProjectRoot)
    {
        string outDir = Path.Combine(apiProjectRoot, "Runtime", "STL", "Generated", "Enums");
        Directory.CreateDirectory(outDir);

        int count = 0;
        foreach (var e in enums)
        {
            if (SkipEnums.Contains(e.Name))
                continue;

            string filePath = Path.Combine(outDir, $"{e.Name}.cs");
            File.WriteAllText(filePath, GenerateEnum(e));
            count++;
        }

        return count;
    }

    private string GenerateEnum(ApiEnum e)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by LUSharpApiGenerator — do not edit manually.");
        sb.AppendLine();
        sb.AppendLine("namespace LUSharpAPI.Runtime.STL.Enums");
        sb.AppendLine("{");
        sb.AppendLine($"    public enum {_naming.EscapeIdentifier(e.Name)}");
        sb.AppendLine("    {");

        for (int i = 0; i < e.Items.Count; i++)
        {
            var item = e.Items[i];
            string name = _naming.EscapeIdentifier(item.Name);
            string comma = i < e.Items.Count - 1 ? "," : "";
            sb.AppendLine($"        {name} = {item.Value}{comma}");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
