--!strict
-- Auto-generated by LUSharpRoslynModule
-- Do not edit manually

type Player_self = {
	Name: string;
	Health: number;
	Inventory: { string };
}

local Player = {}
Player.__index = Player
export type Player = typeof(setmetatable({} :: Player_self, Player))

function Player.new(name: string, health: number): Player
	local self = setmetatable({
		Name = "",
		Health = 0,
		Inventory = {},
	} :: Player_self, Player)
	self.Name = name
	self.Health = health
	self.Inventory = {}
	return self
end

function Player.GetStatus(self: Player): string
	return self.Name .. " has " .. self.Health .. " HP"
end

function Player.GetStatusInterpolated(self: Player): string
	return `Player {self.Name} has {self.Health} HP`
end

function Player.AddItem(self: Player, item: string): ()
	table.insert(self.Inventory, item)
end

function Player.HasItem(self: Player, item: string): boolean
	return (table.find(self.Inventory, item) ~= nil)
end

function Player.FindItem(self: Player, item: string): number
	return ((table.find(self.Inventory, item) or 0) - 1)
end

function Player.GetLowerName(self: Player): string
	return string.lower(self.Name)
end

function Player.NameContains(self: Player, sub: string): boolean
	return (string.find(self.Name, sub, 1, true) ~= nil)
end

function Player.GetNameSubstring(self: Player, start: number, length: number): string
	return string.sub(self.Name, start + 1, start + length)
end

function Player.Describe(self: Player, obj: any): string
	local s: string = obj
	if (type(obj) == "string") then
		return `String: {s}`
	end
	local n: number = obj
	if (type(obj) == "number") then
		return `Number: {n}`
	end
	local p: Player = obj
	if (obj ~= nil) then
		return `Player: {p.Name}`
	end
	return "Unknown"
end

function Player.GetTypeName(self: Player): string
	return tostring("Player")
end

function Player.CreateDefault(): Player
	return (function() local __o = Player.new("Default", 100); __o.Name = "Hero"; return __o end)()
end

function Player.ClampHealth(self: Player, min: number, max: number): number
	return math.clamp(self.Health, min, max)
end

function Player.BuildReport(self: Player): string
	local sb = StringBuilder.new()
	(function() sb = sb .. tostring("Report for "); return sb end)()
	(function() sb = sb .. tostring(self.Name); return sb end)()
	(function() sb = sb .. "\n"; return sb end)()
	(function() sb = sb .. tostring("Health: "); return sb end)()
	(function() sb = sb .. tostring(self.Health); return sb end)()
	return sb
end

function Player.SafeName(self: Player, fallback: string?): string
	return if self.Name ~= nil then self.Name else if fallback ~= nil then fallback else "Unknown"
end

function Player.ProcessWithUsing(self: Player): ()
	print("Processing")
end

function Player.HealthCategory(self: Player): string
	if self.Health > 80 then
		return "Healthy"
	elseif self.Health > 50 then
		return "Injured"
	elseif self.Health > 20 then
		return "Critical"
	end
	return "Dead"
end

function Player.ComputeScore(self: Player): number
	local function bonus(level)
		return level * 10
	end
	return self.Health + bonus(5)
end

function Player.GetScores(): { [string]: number }
	local scores = {}
	scores["Alice"] = 100
	scores["Bob"] = 85
	if (scores["Alice"] ~= nil) then
		print("Alice found")
	end
	return scores
end

function Player.SortInventory(self: Player): ()
	table.sort(self.Inventory)
	local count = #self.Inventory
	print(`Sorted {count} items`)
end

function Player.GetNameLength(self: Player): number?
	return if self.Name ~= nil then self.Name.Length else nil
end

return { Player = Player }
