--!strict
-- Auto-generated by SimpleEmitter

local _SlidingTextWindow
local SlidingTextWindow = setmetatable({}, {__index = function(_, k)
	if not _SlidingTextWindow then _SlidingTextWindow = require(script.Parent.SlidingTextWindow) end
	return _SlidingTextWindow.SlidingTextWindow[k]
end})
local _SyntaxFacts
local SyntaxFacts = setmetatable({}, {__index = function(_, k)
	if not _SyntaxFacts then _SyntaxFacts = require(script.Parent.SyntaxFacts) end
	return _SyntaxFacts.SyntaxFacts[k]
end})
local _SyntaxKind
local SyntaxKind = setmetatable({}, {__index = function(_, k)
	if not _SyntaxKind then _SyntaxKind = require(script.Parent.SyntaxKind) end
	return _SyntaxKind.SyntaxKind[k]
end})
local _SyntaxToken
local TokenInfo = setmetatable({}, {__index = function(_, k)
	if not _SyntaxToken then _SyntaxToken = require(script.Parent.SyntaxToken) end
	return _SyntaxToken.TokenInfo[k]
end})

type SimpleTokenizer_self = {
	_window: SlidingTextWindow;
	_tokens: { TokenInfo };
}

local SimpleTokenizer = {}
SimpleTokenizer.__index = SimpleTokenizer
export type SimpleTokenizer = typeof(setmetatable({} :: SimpleTokenizer_self, SimpleTokenizer))

function SimpleTokenizer.new(text: string): SimpleTokenizer
	local self = setmetatable({
		_window = nil :: any,
		_tokens = {},
	} :: SimpleTokenizer_self, SimpleTokenizer)
	self._window = SlidingTextWindow.new(text)
	self._tokens = {}
	return self
end

function SimpleTokenizer.Tokenize(self: SimpleTokenizer): { TokenInfo }
	table.clear(self._tokens)
	while not self._window:IsReallyAtEnd() do
		self._window:Start()
		local token: any = SimpleTokenizer.ScanToken(self)
		if token.Kind ~= SyntaxKind.None then
			table.insert(self._tokens, token)
		end
	end
	table.insert(self._tokens, TokenInfo.new(SyntaxKind.EndOfFileToken, "", self._window.Position, 0))
	return self._tokens
end

function SimpleTokenizer.ScanToken(self: SimpleTokenizer): TokenInfo
	local ch: number = self._window:PeekChar(0)
	if SyntaxFacts.IsWhitespace(ch) then
		return SimpleTokenizer.ScanWhitespace(self)
	end
	if SyntaxFacts.IsNewLine(ch) then
		return SimpleTokenizer.ScanNewLine(self)
	end
	if ch == string.byte("_", 1) or (ch >= string.byte("a", 1) and ch <= string.byte("z", 1)) or (ch >= string.byte("A", 1) and ch <= string.byte("Z", 1)) then
		return SimpleTokenizer.ScanIdentifierOrKeyword(self)
	end
	if SyntaxFacts.IsDecDigit(ch) then
		return SimpleTokenizer.ScanNumericLiteral(self)
	end
	if ch == string.byte("$", 1) and not self._window:IsReallyAtEnd() then
		local peekPos: number = self._window.Position + 1
		if peekPos < self._window.TextLength and self._window:CharAt(peekPos) == 34 then
			return SimpleTokenizer.ScanInterpolatedStringLiteral(self)
		end
	end
	if ch == 34 then
		return SimpleTokenizer.ScanStringLiteral(self)
	end
	if ch == 39 then
		return SimpleTokenizer.ScanCharacterLiteral(self)
	end
	return SimpleTokenizer.ScanPunctuation(self)
end

function SimpleTokenizer.ScanWhitespace(self: SimpleTokenizer): TokenInfo
	local start: number = self._window.Position
	while not self._window:IsReallyAtEnd() and SyntaxFacts.IsWhitespace(self._window:PeekChar(0)) do
		self._window:AdvanceChar(1)
	end
	return TokenInfo.new(SyntaxKind.WhitespaceTrivia, self._window:GetText(false), start, self._window.Position - start)
end

function SimpleTokenizer.ScanNewLine(self: SimpleTokenizer): TokenInfo
	local start: number = self._window.Position
	self._window:AdvancePastNewLine()
	return TokenInfo.new(SyntaxKind.EndOfLineTrivia, self._window:GetText(false), start, self._window.Position - start)
end

function SimpleTokenizer.ScanIdentifierOrKeyword(self: SimpleTokenizer): TokenInfo
	local start: number = self._window.Position
	while not self._window:IsReallyAtEnd() do
		local ch: number = self._window:PeekChar(0)
		if ch == string.byte("_", 1) or (ch >= string.byte("a", 1) and ch <= string.byte("z", 1)) or (ch >= string.byte("A", 1) and ch <= string.byte("Z", 1)) or (ch >= string.byte("0", 1) and ch <= string.byte("9", 1)) then
			self._window:AdvanceChar(1)
		else
			break
		end
	end
	local text: string = self._window:GetText(false)
	local keywordKind: SyntaxKind = SyntaxFacts.GetKeywordKind(text)
	if keywordKind ~= SyntaxKind.None then
		return TokenInfo.new(keywordKind, text, start, #text)
	end
	return TokenInfo.new(SyntaxKind.IdentifierToken, text, start, #text)
end

function SimpleTokenizer.ScanNumericLiteral(self: SimpleTokenizer): TokenInfo
	local start: number = self._window.Position
	while not self._window:IsReallyAtEnd() and SyntaxFacts.IsDecDigit(self._window:PeekChar(0)) do
		self._window:AdvanceChar(1)
	end
	if self._window:PeekChar(0) == string.byte(".", 1) and SyntaxFacts.IsDecDigit(self._window:PeekChar(1)) then
		self._window:AdvanceChar(1)
		while not self._window:IsReallyAtEnd() and SyntaxFacts.IsDecDigit(self._window:PeekChar(0)) do
			self._window:AdvanceChar(1)
		end
	end
	local text: string = self._window:GetText(false)
	return TokenInfo.new(SyntaxKind.NumericLiteralToken, text, start, #text)
end

function SimpleTokenizer.ScanInterpolatedStringLiteral(self: SimpleTokenizer): TokenInfo
	local start: number = self._window.Position
	self._window:AdvanceChar(1)
	self._window:AdvanceChar(1)
	local braceDepth: number = 0
	while not self._window:IsReallyAtEnd() do
		local ch: number = self._window:PeekChar(0)
		if ch == string.byte("{", 1) and braceDepth == 0 then
			local nextPos: number = self._window.Position + 1
			if nextPos < self._window.TextLength and self._window:CharAt(nextPos) == string.byte("{", 1) then
				self._window:AdvanceChar(1)
				self._window:AdvanceChar(1)
				continue
			end
			braceDepth += 1
			self._window:AdvanceChar(1)
			continue
		end
		if ch == string.byte("}", 1) and braceDepth > 0 then
			braceDepth -= 1
			self._window:AdvanceChar(1)
			continue
		end
		if ch == 34 and braceDepth == 0 then
			self._window:AdvanceChar(1)
			break
		end
		if ch == 92 then
			self._window:AdvanceChar(1)
			if not self._window:IsReallyAtEnd() then
				self._window:AdvanceChar(1)
			end
		else
			self._window:AdvanceChar(1)
		end
	end
	local text: string = self._window:GetText(false)
	return TokenInfo.new(SyntaxKind.InterpolatedStringToken, text, start, #text)
end

function SimpleTokenizer.ScanStringLiteral(self: SimpleTokenizer): TokenInfo
	local start: number = self._window.Position
	self._window:AdvanceChar(1)
	while not self._window:IsReallyAtEnd() do
		local ch: number = self._window:PeekChar(0)
		if ch == 34 then
			self._window:AdvanceChar(1)
			break
		end
		if ch == 92 then
			self._window:AdvanceChar(1)
			if not self._window:IsReallyAtEnd() then
				self._window:AdvanceChar(1)
			end
		else
			self._window:AdvanceChar(1)
		end
	end
	local text: string = self._window:GetText(false)
	return TokenInfo.new(SyntaxKind.StringLiteralToken, text, start, #text)
end

function SimpleTokenizer.ScanCharacterLiteral(self: SimpleTokenizer): TokenInfo
	local start: number = self._window.Position
	self._window:AdvanceChar(1)
	if self._window:PeekChar(0) == 92 then
		self._window:AdvanceChar(1)
		if not self._window:IsReallyAtEnd() then
			local esc: number = self._window:PeekChar(0)
			if esc == string.byte("u", 1) then
				self._window:AdvanceChar(1)
				local i: number = 0
				while i < 4 and not self._window:IsReallyAtEnd() and SyntaxFacts.IsHexDigit(self._window:PeekChar(0)) do
					self._window:AdvanceChar(1)
					i += 1
				end
			elseif esc == string.byte("U", 1) then
				self._window:AdvanceChar(1)
				local i: number = 0
				while i < 8 and not self._window:IsReallyAtEnd() and SyntaxFacts.IsHexDigit(self._window:PeekChar(0)) do
					self._window:AdvanceChar(1)
					i += 1
				end
			else
				self._window:AdvanceChar(1)
			end
		end
	elseif not self._window:IsReallyAtEnd() then
		self._window:AdvanceChar(1)
	end
	if self._window:PeekChar(0) == 39 then
		self._window:AdvanceChar(1)
	end
	local text: string = self._window:GetText(false)
	return TokenInfo.new(SyntaxKind.CharacterLiteralToken, text, start, #text)
end

function SimpleTokenizer.ScanPunctuation(self: SimpleTokenizer): TokenInfo
	local start: number = self._window.Position
	local ch: number = self._window:NextChar()
	local kind: SyntaxKind = if ch == string.byte("{", 1) then SyntaxKind.OpenBraceToken elseif ch == string.byte("}", 1) then SyntaxKind.CloseBraceToken elseif ch == string.byte("(", 1) then SyntaxKind.OpenParenToken elseif ch == string.byte(")", 1) then SyntaxKind.CloseParenToken elseif ch == string.byte("[", 1) then SyntaxKind.OpenBracketToken elseif ch == string.byte("]", 1) then SyntaxKind.CloseBracketToken elseif ch == string.byte(";", 1) then SyntaxKind.SemicolonToken elseif ch == string.byte(",", 1) then SyntaxKind.CommaToken elseif ch == string.byte(".", 1) then SyntaxKind.DotToken elseif ch == string.byte(":", 1) then SyntaxKind.ColonToken elseif ch == string.byte("?", 1) then SimpleTokenizer.ScanQuestionToken(self) elseif ch == string.byte("~", 1) then SyntaxKind.TildeToken elseif ch == string.byte("+", 1) then SimpleTokenizer.ScanPlusToken(self) elseif ch == string.byte("-", 1) then SimpleTokenizer.ScanMinusToken(self) elseif ch == string.byte("*", 1) then SyntaxKind.AsteriskToken elseif ch == string.byte("/", 1) then SimpleTokenizer.ScanSlashToken(self) elseif ch == string.byte("%", 1) then SyntaxKind.PercentToken elseif ch == string.byte("&", 1) then SimpleTokenizer.ScanAmpersandToken(self) elseif ch == string.byte("|", 1) then SimpleTokenizer.ScanBarToken(self) elseif ch == string.byte("^", 1) then SyntaxKind.CaretToken elseif ch == string.byte("!", 1) then SimpleTokenizer.ScanExclamationToken(self) elseif ch == string.byte("=", 1) then SimpleTokenizer.ScanEqualsToken(self) elseif ch == string.byte("<", 1) then SimpleTokenizer.ScanLessThanToken(self) elseif ch == string.byte(">", 1) then SimpleTokenizer.ScanGreaterThanToken(self) else SyntaxKind.None
	local text: string = self._window:GetText(false)
	return TokenInfo.new(kind, text, start, #text)
end

function SimpleTokenizer.ScanPlusToken(self: SimpleTokenizer): SyntaxKind
	if self._window:PeekChar(0) == string.byte("+", 1) then
		self._window:AdvanceChar(1)
		return SyntaxKind.PlusPlusToken
	end
	if self._window:PeekChar(0) == string.byte("=", 1) then
		self._window:AdvanceChar(1)
		return SyntaxKind.PlusEqualsToken
	end
	return SyntaxKind.PlusToken
end

function SimpleTokenizer.ScanMinusToken(self: SimpleTokenizer): SyntaxKind
	if self._window:PeekChar(0) == string.byte("-", 1) then
		self._window:AdvanceChar(1)
		return SyntaxKind.MinusMinusToken
	end
	if self._window:PeekChar(0) == string.byte("=", 1) then
		self._window:AdvanceChar(1)
		return SyntaxKind.MinusEqualsToken
	end
	if self._window:PeekChar(0) == string.byte(">", 1) then
		self._window:AdvanceChar(1)
		return SyntaxKind.MinusGreaterThanToken
	end
	return SyntaxKind.MinusToken
end

function SimpleTokenizer.ScanSlashToken(self: SimpleTokenizer): SyntaxKind
	if self._window:PeekChar(0) == string.byte("/", 1) then
		while not self._window:IsReallyAtEnd() and not SyntaxFacts.IsNewLine(self._window:PeekChar(0)) do
			self._window:AdvanceChar(1)
		end
		return SyntaxKind.SingleLineCommentTrivia
	end
	if self._window:PeekChar(0) == string.byte("=", 1) then
		self._window:AdvanceChar(1)
		return SyntaxKind.SlashEqualsToken
	end
	return SyntaxKind.SlashToken
end

function SimpleTokenizer.ScanAmpersandToken(self: SimpleTokenizer): SyntaxKind
	if self._window:PeekChar(0) == string.byte("&", 1) then
		self._window:AdvanceChar(1)
		return SyntaxKind.AmpersandAmpersandToken
	end
	if self._window:PeekChar(0) == string.byte("=", 1) then
		self._window:AdvanceChar(1)
		return SyntaxKind.AmpersandEqualsToken
	end
	return SyntaxKind.AmpersandToken
end

function SimpleTokenizer.ScanBarToken(self: SimpleTokenizer): SyntaxKind
	if self._window:PeekChar(0) == string.byte("|", 1) then
		self._window:AdvanceChar(1)
		return SyntaxKind.BarBarToken
	end
	if self._window:PeekChar(0) == string.byte("=", 1) then
		self._window:AdvanceChar(1)
		return SyntaxKind.BarEqualsToken
	end
	return SyntaxKind.BarToken
end

function SimpleTokenizer.ScanQuestionToken(self: SimpleTokenizer): SyntaxKind
	if self._window:PeekChar(0) == string.byte("?", 1) then
		self._window:AdvanceChar(1)
		if self._window:PeekChar(0) == string.byte("=", 1) then
			self._window:AdvanceChar(1)
			return SyntaxKind.QuestionQuestionEqualsToken
		end
		return SyntaxKind.QuestionQuestionToken
	end
	if self._window:PeekChar(0) == string.byte(".", 1) then
		self._window:AdvanceChar(1)
		return SyntaxKind.QuestionDotToken
	end
	return SyntaxKind.QuestionToken
end

function SimpleTokenizer.ScanExclamationToken(self: SimpleTokenizer): SyntaxKind
	if self._window:PeekChar(0) == string.byte("=", 1) then
		self._window:AdvanceChar(1)
		return SyntaxKind.ExclamationEqualsToken
	end
	return SyntaxKind.ExclamationToken
end

function SimpleTokenizer.ScanEqualsToken(self: SimpleTokenizer): SyntaxKind
	if self._window:PeekChar(0) == string.byte("=", 1) then
		self._window:AdvanceChar(1)
		return SyntaxKind.EqualsEqualsToken
	end
	if self._window:PeekChar(0) == string.byte(">", 1) then
		self._window:AdvanceChar(1)
		return SyntaxKind.EqualsGreaterThanToken
	end
	return SyntaxKind.EqualsToken
end

function SimpleTokenizer.ScanLessThanToken(self: SimpleTokenizer): SyntaxKind
	if self._window:PeekChar(0) == string.byte("=", 1) then
		self._window:AdvanceChar(1)
		return SyntaxKind.LessThanEqualsToken
	end
	if self._window:PeekChar(0) == string.byte("<", 1) then
		self._window:AdvanceChar(1)
		return SyntaxKind.LessThanLessThanToken
	end
	return SyntaxKind.LessThanToken
end

function SimpleTokenizer.ScanGreaterThanToken(self: SimpleTokenizer): SyntaxKind
	if self._window:PeekChar(0) == string.byte("=", 1) then
		self._window:AdvanceChar(1)
		return SyntaxKind.GreaterThanEqualsToken
	end
	return SyntaxKind.GreaterThanToken
end


return { SimpleTokenizer = SimpleTokenizer }
