--!strict
-- Auto-generated by SimpleEmitter

local _DeclarationNodes
local ClassDeclarationSyntax = setmetatable({}, {__index = function(_, k)
	if not _DeclarationNodes then _DeclarationNodes = require(script.Parent.DeclarationNodes) end
	return _DeclarationNodes.ClassDeclarationSyntax[k]
end})
local CompilationUnitSyntax = setmetatable({}, {__index = function(_, k)
	if not _DeclarationNodes then _DeclarationNodes = require(script.Parent.DeclarationNodes) end
	return _DeclarationNodes.CompilationUnitSyntax[k]
end})
local ConstructorDeclarationSyntax = setmetatable({}, {__index = function(_, k)
	if not _DeclarationNodes then _DeclarationNodes = require(script.Parent.DeclarationNodes) end
	return _DeclarationNodes.ConstructorDeclarationSyntax[k]
end})
local EnumDeclarationSyntax = setmetatable({}, {__index = function(_, k)
	if not _DeclarationNodes then _DeclarationNodes = require(script.Parent.DeclarationNodes) end
	return _DeclarationNodes.EnumDeclarationSyntax[k]
end})
local EnumMemberSyntax = setmetatable({}, {__index = function(_, k)
	if not _DeclarationNodes then _DeclarationNodes = require(script.Parent.DeclarationNodes) end
	return _DeclarationNodes.EnumMemberSyntax[k]
end})
local FieldDeclarationSyntax = setmetatable({}, {__index = function(_, k)
	if not _DeclarationNodes then _DeclarationNodes = require(script.Parent.DeclarationNodes) end
	return _DeclarationNodes.FieldDeclarationSyntax[k]
end})
local MethodDeclarationSyntax = setmetatable({}, {__index = function(_, k)
	if not _DeclarationNodes then _DeclarationNodes = require(script.Parent.DeclarationNodes) end
	return _DeclarationNodes.MethodDeclarationSyntax[k]
end})
local ParameterSyntax = setmetatable({}, {__index = function(_, k)
	if not _DeclarationNodes then _DeclarationNodes = require(script.Parent.DeclarationNodes) end
	return _DeclarationNodes.ParameterSyntax[k]
end})
local PropertyDeclarationSyntax = setmetatable({}, {__index = function(_, k)
	if not _DeclarationNodes then _DeclarationNodes = require(script.Parent.DeclarationNodes) end
	return _DeclarationNodes.PropertyDeclarationSyntax[k]
end})
local StructDeclarationSyntax = setmetatable({}, {__index = function(_, k)
	if not _DeclarationNodes then _DeclarationNodes = require(script.Parent.DeclarationNodes) end
	return _DeclarationNodes.StructDeclarationSyntax[k]
end})
local _ExpressionNodes
local ArrayCreationExpressionSyntax = setmetatable({}, {__index = function(_, k)
	if not _ExpressionNodes then _ExpressionNodes = require(script.Parent.ExpressionNodes) end
	return _ExpressionNodes.ArrayCreationExpressionSyntax[k]
end})
local AssignmentExpressionSyntax = setmetatable({}, {__index = function(_, k)
	if not _ExpressionNodes then _ExpressionNodes = require(script.Parent.ExpressionNodes) end
	return _ExpressionNodes.AssignmentExpressionSyntax[k]
end})
local BinaryExpressionSyntax = setmetatable({}, {__index = function(_, k)
	if not _ExpressionNodes then _ExpressionNodes = require(script.Parent.ExpressionNodes) end
	return _ExpressionNodes.BinaryExpressionSyntax[k]
end})
local CastExpressionSyntax = setmetatable({}, {__index = function(_, k)
	if not _ExpressionNodes then _ExpressionNodes = require(script.Parent.ExpressionNodes) end
	return _ExpressionNodes.CastExpressionSyntax[k]
end})
local ConditionalAccessExpressionSyntax = setmetatable({}, {__index = function(_, k)
	if not _ExpressionNodes then _ExpressionNodes = require(script.Parent.ExpressionNodes) end
	return _ExpressionNodes.ConditionalAccessExpressionSyntax[k]
end})
local ConditionalExpressionSyntax = setmetatable({}, {__index = function(_, k)
	if not _ExpressionNodes then _ExpressionNodes = require(script.Parent.ExpressionNodes) end
	return _ExpressionNodes.ConditionalExpressionSyntax[k]
end})
local ElementAccessExpressionSyntax = setmetatable({}, {__index = function(_, k)
	if not _ExpressionNodes then _ExpressionNodes = require(script.Parent.ExpressionNodes) end
	return _ExpressionNodes.ElementAccessExpressionSyntax[k]
end})
local IdentifierNameSyntax = setmetatable({}, {__index = function(_, k)
	if not _ExpressionNodes then _ExpressionNodes = require(script.Parent.ExpressionNodes) end
	return _ExpressionNodes.IdentifierNameSyntax[k]
end})
local InvocationExpressionSyntax = setmetatable({}, {__index = function(_, k)
	if not _ExpressionNodes then _ExpressionNodes = require(script.Parent.ExpressionNodes) end
	return _ExpressionNodes.InvocationExpressionSyntax[k]
end})
local IsPatternExpressionSyntax = setmetatable({}, {__index = function(_, k)
	if not _ExpressionNodes then _ExpressionNodes = require(script.Parent.ExpressionNodes) end
	return _ExpressionNodes.IsPatternExpressionSyntax[k]
end})
local LambdaExpressionSyntax = setmetatable({}, {__index = function(_, k)
	if not _ExpressionNodes then _ExpressionNodes = require(script.Parent.ExpressionNodes) end
	return _ExpressionNodes.LambdaExpressionSyntax[k]
end})
local LiteralExpressionSyntax = setmetatable({}, {__index = function(_, k)
	if not _ExpressionNodes then _ExpressionNodes = require(script.Parent.ExpressionNodes) end
	return _ExpressionNodes.LiteralExpressionSyntax[k]
end})
local MemberAccessExpressionSyntax = setmetatable({}, {__index = function(_, k)
	if not _ExpressionNodes then _ExpressionNodes = require(script.Parent.ExpressionNodes) end
	return _ExpressionNodes.MemberAccessExpressionSyntax[k]
end})
local ObjectCreationExpressionSyntax = setmetatable({}, {__index = function(_, k)
	if not _ExpressionNodes then _ExpressionNodes = require(script.Parent.ExpressionNodes) end
	return _ExpressionNodes.ObjectCreationExpressionSyntax[k]
end})
local ParenthesizedExpressionSyntax = setmetatable({}, {__index = function(_, k)
	if not _ExpressionNodes then _ExpressionNodes = require(script.Parent.ExpressionNodes) end
	return _ExpressionNodes.ParenthesizedExpressionSyntax[k]
end})
local PostfixUnaryExpressionSyntax = setmetatable({}, {__index = function(_, k)
	if not _ExpressionNodes then _ExpressionNodes = require(script.Parent.ExpressionNodes) end
	return _ExpressionNodes.PostfixUnaryExpressionSyntax[k]
end})
local PrefixUnaryExpressionSyntax = setmetatable({}, {__index = function(_, k)
	if not _ExpressionNodes then _ExpressionNodes = require(script.Parent.ExpressionNodes) end
	return _ExpressionNodes.PrefixUnaryExpressionSyntax[k]
end})
local SwitchExpressionArmSyntax = setmetatable({}, {__index = function(_, k)
	if not _ExpressionNodes then _ExpressionNodes = require(script.Parent.ExpressionNodes) end
	return _ExpressionNodes.SwitchExpressionArmSyntax[k]
end})
local SwitchExpressionSyntax = setmetatable({}, {__index = function(_, k)
	if not _ExpressionNodes then _ExpressionNodes = require(script.Parent.ExpressionNodes) end
	return _ExpressionNodes.SwitchExpressionSyntax[k]
end})
local _SimpleTokenizer
local SimpleTokenizer = setmetatable({}, {__index = function(_, k)
	if not _SimpleTokenizer then _SimpleTokenizer = require(script.Parent.SimpleTokenizer) end
	return _SimpleTokenizer.SimpleTokenizer[k]
end})
local _StatementNodes
local BlockSyntax = setmetatable({}, {__index = function(_, k)
	if not _StatementNodes then _StatementNodes = require(script.Parent.StatementNodes) end
	return _StatementNodes.BlockSyntax[k]
end})
local BreakStatementSyntax = setmetatable({}, {__index = function(_, k)
	if not _StatementNodes then _StatementNodes = require(script.Parent.StatementNodes) end
	return _StatementNodes.BreakStatementSyntax[k]
end})
local CatchClauseSyntax = setmetatable({}, {__index = function(_, k)
	if not _StatementNodes then _StatementNodes = require(script.Parent.StatementNodes) end
	return _StatementNodes.CatchClauseSyntax[k]
end})
local ContinueStatementSyntax = setmetatable({}, {__index = function(_, k)
	if not _StatementNodes then _StatementNodes = require(script.Parent.StatementNodes) end
	return _StatementNodes.ContinueStatementSyntax[k]
end})
local DoStatementSyntax = setmetatable({}, {__index = function(_, k)
	if not _StatementNodes then _StatementNodes = require(script.Parent.StatementNodes) end
	return _StatementNodes.DoStatementSyntax[k]
end})
local ExpressionStatementSyntax = setmetatable({}, {__index = function(_, k)
	if not _StatementNodes then _StatementNodes = require(script.Parent.StatementNodes) end
	return _StatementNodes.ExpressionStatementSyntax[k]
end})
local ForEachStatementSyntax = setmetatable({}, {__index = function(_, k)
	if not _StatementNodes then _StatementNodes = require(script.Parent.StatementNodes) end
	return _StatementNodes.ForEachStatementSyntax[k]
end})
local ForStatementSyntax = setmetatable({}, {__index = function(_, k)
	if not _StatementNodes then _StatementNodes = require(script.Parent.StatementNodes) end
	return _StatementNodes.ForStatementSyntax[k]
end})
local IfStatementSyntax = setmetatable({}, {__index = function(_, k)
	if not _StatementNodes then _StatementNodes = require(script.Parent.StatementNodes) end
	return _StatementNodes.IfStatementSyntax[k]
end})
local LocalDeclarationStatementSyntax = setmetatable({}, {__index = function(_, k)
	if not _StatementNodes then _StatementNodes = require(script.Parent.StatementNodes) end
	return _StatementNodes.LocalDeclarationStatementSyntax[k]
end})
local LockStatementSyntax = setmetatable({}, {__index = function(_, k)
	if not _StatementNodes then _StatementNodes = require(script.Parent.StatementNodes) end
	return _StatementNodes.LockStatementSyntax[k]
end})
local ReturnStatementSyntax = setmetatable({}, {__index = function(_, k)
	if not _StatementNodes then _StatementNodes = require(script.Parent.StatementNodes) end
	return _StatementNodes.ReturnStatementSyntax[k]
end})
local SwitchSectionSyntax = setmetatable({}, {__index = function(_, k)
	if not _StatementNodes then _StatementNodes = require(script.Parent.StatementNodes) end
	return _StatementNodes.SwitchSectionSyntax[k]
end})
local SwitchStatementSyntax = setmetatable({}, {__index = function(_, k)
	if not _StatementNodes then _StatementNodes = require(script.Parent.StatementNodes) end
	return _StatementNodes.SwitchStatementSyntax[k]
end})
local ThrowStatementSyntax = setmetatable({}, {__index = function(_, k)
	if not _StatementNodes then _StatementNodes = require(script.Parent.StatementNodes) end
	return _StatementNodes.ThrowStatementSyntax[k]
end})
local TryStatementSyntax = setmetatable({}, {__index = function(_, k)
	if not _StatementNodes then _StatementNodes = require(script.Parent.StatementNodes) end
	return _StatementNodes.TryStatementSyntax[k]
end})
local TupleDeconstructionStatementSyntax = setmetatable({}, {__index = function(_, k)
	if not _StatementNodes then _StatementNodes = require(script.Parent.StatementNodes) end
	return _StatementNodes.TupleDeconstructionStatementSyntax[k]
end})
local UsingStatementSyntax = setmetatable({}, {__index = function(_, k)
	if not _StatementNodes then _StatementNodes = require(script.Parent.StatementNodes) end
	return _StatementNodes.UsingStatementSyntax[k]
end})
local WhileStatementSyntax = setmetatable({}, {__index = function(_, k)
	if not _StatementNodes then _StatementNodes = require(script.Parent.StatementNodes) end
	return _StatementNodes.WhileStatementSyntax[k]
end})
local _SyntaxKind
local SyntaxKind = setmetatable({}, {__index = function(_, k)
	if not _SyntaxKind then _SyntaxKind = require(script.Parent.SyntaxKind) end
	return _SyntaxKind.SyntaxKind[k]
end})
local _SyntaxNode
local ExpressionSyntax = setmetatable({}, {__index = function(_, k)
	if not _SyntaxNode then _SyntaxNode = require(script.Parent.SyntaxNode) end
	return _SyntaxNode.ExpressionSyntax[k]
end})
local MemberDeclarationSyntax = setmetatable({}, {__index = function(_, k)
	if not _SyntaxNode then _SyntaxNode = require(script.Parent.SyntaxNode) end
	return _SyntaxNode.MemberDeclarationSyntax[k]
end})
local StatementSyntax = setmetatable({}, {__index = function(_, k)
	if not _SyntaxNode then _SyntaxNode = require(script.Parent.SyntaxNode) end
	return _SyntaxNode.StatementSyntax[k]
end})
local _SyntaxToken
local SyntaxToken = setmetatable({}, {__index = function(_, k)
	if not _SyntaxToken then _SyntaxToken = require(script.Parent.SyntaxToken) end
	return _SyntaxToken.SyntaxToken[k]
end})
local TokenInfo = setmetatable({}, {__index = function(_, k)
	if not _SyntaxToken then _SyntaxToken = require(script.Parent.SyntaxToken) end
	return _SyntaxToken.TokenInfo[k]
end})

type SimpleParser_self = {
	_tokenizer: SimpleTokenizer;
	_tokens: { TokenInfo };
	_position: number;
	_currentClassName: string;
}

local SimpleParser = {}
SimpleParser.__index = SimpleParser
export type SimpleParser = typeof(setmetatable({} :: SimpleParser_self, SimpleParser))

function SimpleParser.new(text: string): SimpleParser
	local self = setmetatable({
		_tokenizer = nil :: any,
		_tokens = {},
		_position = 0,
		_currentClassName = "",
	} :: SimpleParser_self, SimpleParser)
	self._tokenizer = SimpleTokenizer.new(text)
	local tokenList: any = self._tokenizer:Tokenize()
	local filtered: any = table.create(#tokenList)
	local count: number = 0
	for i = 0, #tokenList - 1 do
		local t: any = tokenList[i + 1]
		if t.Kind ~= SyntaxKind.WhitespaceTrivia and t.Kind ~= SyntaxKind.EndOfLineTrivia and t.Kind ~= SyntaxKind.SingleLineCommentTrivia then
			filtered[count + 1] = t
			count += 1
		end
	end
	self._tokens = table.create(count)
	for i = 0, count - 1 do
		self._tokens[i + 1] = filtered[i + 1]
	end
	self._position = 0
	return self
end

function SimpleParser.Current(self: SimpleParser): TokenInfo
	if self._position >= #self._tokens then
		return TokenInfo.new(SyntaxKind.EndOfFileToken, "", 0, 0)
	end
	return self._tokens[self._position + 1]
end

function SimpleParser.Advance(self: SimpleParser): TokenInfo
	local token: any = SimpleParser.Current(self)
	self._position += 1
	return token
end

function SimpleParser.Expect(self: SimpleParser, kind: SyntaxKind): TokenInfo
	local token: any = SimpleParser.Current(self)
	if token.Kind ~= kind then
		return TokenInfo.new(kind, "", token.Start, 0)
	end
	return SimpleParser.Advance(self)
end

function SimpleParser.IsAtEnd(self: SimpleParser): boolean
	return self._position >= #self._tokens or SimpleParser.Current(self).Kind == SyntaxKind.EndOfFileToken
end

function SimpleParser.MakeSyntaxToken(self: SimpleParser, info: TokenInfo): SyntaxToken
	return SyntaxToken.new(info.Kind, info.Text, info.Start, #info)
end

function SimpleParser.ParseCompilationUnit(self: SimpleParser): CompilationUnitSyntax
	local members: any = table.create(256)
	local count: number = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.UsingKeyword do
		SimpleParser.SkipUsingDirective(self)
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.NamespaceKeyword then
		SimpleParser.SkipNamespaceHeader(self)
	end
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseBraceToken do
		local member: any = SimpleParser.ParseMemberDeclaration(self)
		if member ~= nil and count < 256 then
			members[count + 1] = member
			count += 1
		end
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.CloseBraceToken then
		SimpleParser.Advance(self)
	end
	local result: any = table.create(count)
	for i = 0, count - 1 do
		result[i + 1] = members[i + 1]
	end
	return CompilationUnitSyntax.new(result)
end

function SimpleParser.SkipUsingDirective(self: SimpleParser): ()
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.SemicolonToken do
		SimpleParser.Advance(self)
	end
	if not SimpleParser.IsAtEnd(self) then
		SimpleParser.Advance(self)
	end
end

function SimpleParser.SkipNamespaceHeader(self: SimpleParser): ()
	SimpleParser.Advance(self)
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.OpenBraceToken and SimpleParser.Current(self).Kind ~= SyntaxKind.SemicolonToken do
		SimpleParser.Advance(self)
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.SemicolonToken then
		SimpleParser.Advance(self)
		return
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBraceToken then
		SimpleParser.Advance(self)
	end
end

function SimpleParser.ParseMemberDeclaration(self: SimpleParser): MemberDeclarationSyntax
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBracketToken do
		SimpleParser.SkipAttributeList(self)
	end
	local isPublic: boolean = false
	local isPrivate: boolean = false
	local isStatic: boolean = false
	local isAbstract: boolean = false
	local isVirtual: boolean = false
	local isOverride: boolean = false
	while not SimpleParser.IsAtEnd(self) do
		local kind: SyntaxKind = SimpleParser.Current(self).Kind
		if kind == SyntaxKind.PublicKeyword then
			isPublic = true
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.PrivateKeyword then
			isPrivate = true
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.ProtectedKeyword then
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.InternalKeyword then
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.StaticKeyword then
			isStatic = true
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.AbstractKeyword then
			isAbstract = true
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.VirtualKeyword then
			isVirtual = true
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.OverrideKeyword then
			isOverride = true
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.ReadOnlyKeyword then
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.SealedKeyword then
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.NewKeyword then
			if self._position + 1 < #self._tokens then
				local next: any = self._tokens[self._position + 1 + 1].Kind
				if next == SyntaxKind.OpenParenToken or next == SyntaxKind.IdentifierToken or SimpleParser.IsTypeStart(self, next) then
					break
				end
			end
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.ConstKeyword then
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.VolatileKeyword then
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.ExternKeyword then
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.AsyncKeyword or (kind == SyntaxKind.IdentifierToken and SimpleParser.Current(self).Text == "async") then
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.UnsafeKeyword then
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.PartialKeyword then
			SimpleParser.Advance(self)
		else
			break
		end
	end
	if SimpleParser.IsAtEnd(self) then
		return nil
	end
	if SimpleParser.Current(self).Kind == SyntaxKind.ClassKeyword then
		return SimpleParser.ParseClassDeclaration(self)
	end
	if SimpleParser.Current(self).Kind == SyntaxKind.EnumKeyword then
		return SimpleParser.ParseEnumDeclaration(self)
	end
	if SimpleParser.Current(self).Kind == SyntaxKind.StructKeyword then
		return SimpleParser.ParseStructDeclaration(self)
	end
	local typeName: string = SimpleParser.ParseTypeName(self)
	if typeName == nil or SimpleParser.IsAtEnd(self) then
		return nil
	end
	if typeName == self._currentClassName and SimpleParser.Current(self).Kind == SyntaxKind.OpenParenToken then
		return SimpleParser.ParseConstructorDeclaration(self, typeName)
	end
	local name: string = SimpleParser.Current(self).Text
	SimpleParser.Advance(self)
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenParenToken then
		return SimpleParser.ParseMethodDeclaration(self, typeName, name, isStatic)
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBraceToken then
		local saved: number = self._position
		SimpleParser.Advance(self)
		if not SimpleParser.IsAtEnd(self) and (SimpleParser.Current(self).Text == "get" or SimpleParser.Current(self).Text == "set") then
			self._position = saved
			return SimpleParser.ParsePropertyDeclaration(self, typeName, name, isStatic)
		end
		self._position = saved
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.EqualsGreaterThanToken then
		SimpleParser.Advance(self)
		local exprBody: any = SimpleParser.ParseExpression(self)
		SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
		return PropertyDeclarationSyntax.new(typeName, name, true, false, exprBody, isStatic)
	end
	local initializer: ExpressionSyntax = nil
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.EqualsToken then
		SimpleParser.Advance(self)
		initializer = SimpleParser.ParseExpression(self)
	end
	SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
	return FieldDeclarationSyntax.new(typeName, name, initializer, isStatic)
end

function SimpleParser.ParseClassDeclaration(self: SimpleParser): ClassDeclarationSyntax
	SimpleParser.Advance(self)
	local name: string = SimpleParser.Current(self).Text
	SimpleParser.Advance(self)
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.LessThanToken then
		local depth: number = 0
		while not SimpleParser.IsAtEnd(self) do
			if SimpleParser.Current(self).Kind == SyntaxKind.LessThanToken then
				depth += 1
			elseif SimpleParser.Current(self).Kind == SyntaxKind.GreaterThanToken then
				depth -= 1
				if depth == 0 then
					SimpleParser.Advance(self)
					break
				end
			end
			SimpleParser.Advance(self)
		end
	end
	local baseTypeName: string = nil
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.ColonToken then
		SimpleParser.Advance(self)
		if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.IdentifierToken then
			baseTypeName = SimpleParser.Current(self).Text
		end
		while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.OpenBraceToken do
			SimpleParser.Advance(self)
		end
	end
	SimpleParser.Expect(self, SyntaxKind.OpenBraceToken)
	local previousClassName: string = self._currentClassName
	self._currentClassName = name
	local members: any = table.create(256)
	local count: number = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseBraceToken do
		local member: any = SimpleParser.ParseMemberDeclaration(self)
		if member ~= nil and count < 256 then
			members[count + 1] = member
			count += 1
		end
	end
	self._currentClassName = previousClassName
	SimpleParser.Expect(self, SyntaxKind.CloseBraceToken)
	local result: any = table.create(count)
	for i = 0, count - 1 do
		result[i + 1] = members[i + 1]
	end
	return ClassDeclarationSyntax.new(name, baseTypeName, result)
end

function SimpleParser.ParseEnumDeclaration(self: SimpleParser): EnumDeclarationSyntax
	SimpleParser.Advance(self)
	local name: string = SimpleParser.Current(self).Text
	SimpleParser.Advance(self)
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.ColonToken then
		SimpleParser.Advance(self)
		SimpleParser.ParseTypeName(self)
	end
	SimpleParser.Expect(self, SyntaxKind.OpenBraceToken)
	local members: any = table.create(1024)
	local count: number = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseBraceToken do
		local memberName: string = SimpleParser.Current(self).Text
		SimpleParser.Advance(self)
		local value: ExpressionSyntax = nil
		if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.EqualsToken then
			SimpleParser.Advance(self)
			value = SimpleParser.ParseExpression(self)
		end
		if count < 1024 then
			members[count + 1] = EnumMemberSyntax.new(memberName, value)
			count += 1
		end
		if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.CommaToken then
			SimpleParser.Advance(self)
		end
	end
	SimpleParser.Expect(self, SyntaxKind.CloseBraceToken)
	local result: any = table.create(count)
	for i = 0, count - 1 do
		result[i + 1] = members[i + 1]
	end
	return EnumDeclarationSyntax.new(name, result)
end

function SimpleParser.ParseStructDeclaration(self: SimpleParser): StructDeclarationSyntax
	SimpleParser.Advance(self)
	local name: string = SimpleParser.Current(self).Text
	SimpleParser.Advance(self)
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.LessThanToken then
		local depth: number = 0
		while not SimpleParser.IsAtEnd(self) do
			if SimpleParser.Current(self).Kind == SyntaxKind.LessThanToken then
				depth += 1
			elseif SimpleParser.Current(self).Kind == SyntaxKind.GreaterThanToken then
				depth -= 1
				if depth == 0 then
					SimpleParser.Advance(self)
					break
				end
			end
			SimpleParser.Advance(self)
		end
	end
	local baseTypeName: string = nil
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.ColonToken then
		SimpleParser.Advance(self)
		if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.IdentifierToken then
			baseTypeName = SimpleParser.Current(self).Text
		end
		while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.OpenBraceToken do
			SimpleParser.Advance(self)
		end
	end
	SimpleParser.Expect(self, SyntaxKind.OpenBraceToken)
	local previousClassName: string = self._currentClassName
	self._currentClassName = name
	local members: any = table.create(256)
	local count: number = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseBraceToken do
		local member: any = SimpleParser.ParseMemberDeclaration(self)
		if member ~= nil and count < 256 then
			members[count + 1] = member
			count += 1
		end
	end
	self._currentClassName = previousClassName
	SimpleParser.Expect(self, SyntaxKind.CloseBraceToken)
	local result: any = table.create(count)
	for i = 0, count - 1 do
		result[i + 1] = members[i + 1]
	end
	return StructDeclarationSyntax.new(name, baseTypeName, result)
end

function SimpleParser.ParsePropertyDeclaration(self: SimpleParser, typeName: string, name: string, isStatic: boolean): PropertyDeclarationSyntax
	SimpleParser.Expect(self, SyntaxKind.OpenBraceToken)
	local hasGetter: boolean = false
	local hasSetter: boolean = false
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseBraceToken do
		if SimpleParser.Current(self).Text == "get" then
			hasGetter = true
			SimpleParser.Advance(self)
			if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.SemicolonToken then
				SimpleParser.Advance(self)
			elseif not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBraceToken then
				SimpleParser.SkipBlock(self)
			end
		elseif SimpleParser.Current(self).Text == "set" then
			hasSetter = true
			SimpleParser.Advance(self)
			if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.SemicolonToken then
				SimpleParser.Advance(self)
			elseif not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBraceToken then
				SimpleParser.SkipBlock(self)
			end
		else
			SimpleParser.Advance(self)
		end
	end
	SimpleParser.Expect(self, SyntaxKind.CloseBraceToken)
	return PropertyDeclarationSyntax.new(typeName, name, hasGetter, hasSetter, nil, isStatic)
end

function SimpleParser.ParseConstructorDeclaration(self: SimpleParser, name: string): ConstructorDeclarationSyntax
	SimpleParser.Advance(self)
	local parameters: any = table.create(16)
	local paramCount: number = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseParenToken do
		if paramCount > 0 then
			SimpleParser.Expect(self, SyntaxKind.CommaToken)
		end
		SimpleParser.SkipParameterModifiers(self)
		local paramType: string = SimpleParser.ParseTypeName(self)
		local paramName: string = SimpleParser.Current(self).Text
		SimpleParser.Advance(self)
		if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.EqualsToken then
			SimpleParser.Advance(self)
			SimpleParser.ParseExpression(self)
		end
		if paramCount < 16 then
			parameters[paramCount + 1] = ParameterSyntax.new(paramType, paramName)
			paramCount += 1
		end
	end
	SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
	local paramResult: any = table.create(paramCount)
	for i = 0, paramCount - 1 do
		paramResult[i + 1] = parameters[i + 1]
	end
	local baseOrThisKeyword: string = nil
	local initializerArgs: any = table.create(0)
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.ColonToken then
		SimpleParser.Advance(self)
		if not SimpleParser.IsAtEnd(self) and (SimpleParser.Current(self).Kind == SyntaxKind.BaseKeyword or SimpleParser.Current(self).Kind == SyntaxKind.ThisKeyword) then
			baseOrThisKeyword = SimpleParser.Current(self).Text
			SimpleParser.Advance(self)
			SimpleParser.Expect(self, SyntaxKind.OpenParenToken)
			local args: any = table.create(16)
			local argCount: number = 0
			while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseParenToken do
				if argCount > 0 then
					SimpleParser.Expect(self, SyntaxKind.CommaToken)
				end
				if argCount < 16 then
					args[argCount + 1] = SimpleParser.ParseExpression(self)
					argCount += 1
				end
			end
			SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
			initializerArgs = table.create(argCount)
			for i = 0, argCount - 1 do
				initializerArgs[i + 1] = args[i + 1]
			end
		else
			while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.OpenBraceToken and SimpleParser.Current(self).Kind ~= SyntaxKind.SemicolonToken do
				SimpleParser.Advance(self)
			end
		end
	end
	local body: BlockSyntax = nil
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBraceToken then
		body = SimpleParser.ParseBlock(self)
	elseif not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.SemicolonToken then
		SimpleParser.Advance(self)
	end
	return ConstructorDeclarationSyntax.new(name, paramResult, body, baseOrThisKeyword, initializerArgs)
end

function SimpleParser.SkipBlock(self: SimpleParser): ()
	local depth: number = 0
	if SimpleParser.Current(self).Kind == SyntaxKind.OpenBraceToken then
		depth = 1
		SimpleParser.Advance(self)
	end
	while not SimpleParser.IsAtEnd(self) and depth > 0 do
		if SimpleParser.Current(self).Kind == SyntaxKind.OpenBraceToken then
			depth += 1
		elseif SimpleParser.Current(self).Kind == SyntaxKind.CloseBraceToken then
			depth -= 1
		end
		SimpleParser.Advance(self)
	end
end

function SimpleParser.SkipAttributeList(self: SimpleParser): ()
	if SimpleParser.Current(self).Kind ~= SyntaxKind.OpenBracketToken then
		return
	end
	local depth: number = 1
	SimpleParser.Advance(self)
	while not SimpleParser.IsAtEnd(self) and depth > 0 do
		if SimpleParser.Current(self).Kind == SyntaxKind.OpenBracketToken then
			depth += 1
		elseif SimpleParser.Current(self).Kind == SyntaxKind.CloseBracketToken then
			depth -= 1
		end
		SimpleParser.Advance(self)
	end
end

function SimpleParser.SkipParameterModifiers(self: SimpleParser): ()
	while not SimpleParser.IsAtEnd(self) do
		local kind: SyntaxKind = SimpleParser.Current(self).Kind
		if kind == SyntaxKind.ParamsKeyword or kind == SyntaxKind.RefKeyword or kind == SyntaxKind.OutKeyword or kind == SyntaxKind.InKeyword or kind == SyntaxKind.ThisKeyword then
			SimpleParser.Advance(self)
		else
			break
		end
	end
end

function SimpleParser.ParseMethodDeclaration(self: SimpleParser, returnType: string, name: string, isStatic: boolean): MethodDeclarationSyntax
	SimpleParser.Advance(self)
	local parameters: any = table.create(16)
	local paramCount: number = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseParenToken do
		if paramCount > 0 then
			SimpleParser.Expect(self, SyntaxKind.CommaToken)
		end
		SimpleParser.SkipParameterModifiers(self)
		local paramType: string = SimpleParser.ParseTypeName(self)
		local paramName: string = SimpleParser.Current(self).Text
		SimpleParser.Advance(self)
		if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.EqualsToken then
			SimpleParser.Advance(self)
			SimpleParser.ParseExpression(self)
		end
		if paramCount < 16 then
			parameters[paramCount + 1] = ParameterSyntax.new(paramType, paramName)
			paramCount += 1
		end
	end
	SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
	local paramResult: any = table.create(paramCount)
	for i = 0, paramCount - 1 do
		paramResult[i + 1] = parameters[i + 1]
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.ColonToken then
		while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.OpenBraceToken and SimpleParser.Current(self).Kind ~= SyntaxKind.SemicolonToken do
			SimpleParser.Advance(self)
		end
	end
	local body: BlockSyntax = nil
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBraceToken then
		body = SimpleParser.ParseBlock(self)
	elseif not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.EqualsGreaterThanToken then
		SimpleParser.Advance(self)
		local expr: any = SimpleParser.ParseExpression(self)
		SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
		local returnStmt: any = ReturnStatementSyntax.new(expr)
		body = BlockSyntax.new({ returnStmt })
	elseif not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.SemicolonToken then
		SimpleParser.Advance(self)
	end
	return MethodDeclarationSyntax.new(returnType, name, paramResult, body, isStatic)
end

function SimpleParser.ParseTypeName(self: SimpleParser): string
	if SimpleParser.IsAtEnd(self) then
		return nil
	end
	local name: string = SimpleParser.Current(self).Text
	SimpleParser.Advance(self)
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.DotToken and self._position + 1 < #self._tokens and self._tokens[self._position + 1 + 1].Kind == SyntaxKind.IdentifierToken do
		SimpleParser.Advance(self)
		name = name .. "." .. SimpleParser.Current(self).Text
		SimpleParser.Advance(self)
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.LessThanToken then
		name = name .. "<"
		local depth: number = 0
		while not SimpleParser.IsAtEnd(self) do
			if SimpleParser.Current(self).Kind == SyntaxKind.LessThanToken then
				depth += 1
				if depth > 1 then
					name = name .. "<"
				end
				SimpleParser.Advance(self)
			elseif SimpleParser.Current(self).Kind == SyntaxKind.GreaterThanToken then
				depth -= 1
				if depth == 0 then
					name = name .. ">"
					SimpleParser.Advance(self)
					break
				end
				name = name .. ">"
				SimpleParser.Advance(self)
			else
				if SimpleParser.Current(self).Kind ~= SyntaxKind.WhitespaceTrivia then
					name = name .. SimpleParser.Current(self).Text
				end
				SimpleParser.Advance(self)
			end
		end
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBracketToken and self._position + 1 < #self._tokens and self._tokens[self._position + 1 + 1].Kind == SyntaxKind.CloseBracketToken then
		SimpleParser.Advance(self)
		SimpleParser.Advance(self)
		name = name .. "[]"
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.QuestionToken then
		SimpleParser.Advance(self)
		name = name .. "?"
	end
	return name
end

function SimpleParser.ParseBlock(self: SimpleParser): BlockSyntax
	SimpleParser.Expect(self, SyntaxKind.OpenBraceToken)
	local statements: any = table.create(512)
	local count: number = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseBraceToken do
		local stmt: any = SimpleParser.ParseStatement(self)
		if stmt ~= nil and count < 512 then
			statements[count + 1] = stmt
			count += 1
		end
	end
	SimpleParser.Expect(self, SyntaxKind.CloseBraceToken)
	local result: any = table.create(count)
	for i = 0, count - 1 do
		result[i + 1] = statements[i + 1]
	end
	return BlockSyntax.new(result)
end

function SimpleParser.ParseStatement(self: SimpleParser): StatementSyntax
	if SimpleParser.IsAtEnd(self) then
		return nil
	end
	local kind: SyntaxKind = SimpleParser.Current(self).Kind
	if kind == SyntaxKind.ReturnKeyword then
		return SimpleParser.ParseReturnStatement(self)
	end
	if kind == SyntaxKind.IfKeyword then
		return SimpleParser.ParseIfStatement(self)
	end
	if kind == SyntaxKind.WhileKeyword then
		return SimpleParser.ParseWhileStatement(self)
	end
	if kind == SyntaxKind.ForKeyword then
		return SimpleParser.ParseForStatement(self)
	end
	if kind == SyntaxKind.ForEachKeyword then
		return SimpleParser.ParseForEachStatement(self)
	end
	if kind == SyntaxKind.DoKeyword then
		return SimpleParser.ParseDoStatement(self)
	end
	if kind == SyntaxKind.BreakKeyword then
		SimpleParser.Advance(self)
		SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
		return BreakStatementSyntax.new()
	end
	if kind == SyntaxKind.ContinueKeyword then
		SimpleParser.Advance(self)
		SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
		return ContinueStatementSyntax.new()
	end
	if kind == SyntaxKind.SwitchKeyword then
		return SimpleParser.ParseSwitchStatement(self)
	end
	if kind == SyntaxKind.TryKeyword then
		return SimpleParser.ParseTryStatement(self)
	end
	if kind == SyntaxKind.ThrowKeyword then
		return SimpleParser.ParseThrowStatement(self)
	end
	if kind == SyntaxKind.LockKeyword then
		return SimpleParser.ParseLockStatement(self)
	end
	if kind == SyntaxKind.UsingKeyword then
		return SimpleParser.ParseUsingStatement(self)
	end
	if kind == SyntaxKind.OpenBraceToken then
		return SimpleParser.ParseBlock(self)
	end
	local isContextualKeyword: boolean = kind == SyntaxKind.IdentifierToken and (SimpleParser.Current(self).Text == "await" or SimpleParser.Current(self).Text == "yield" or SimpleParser.Current(self).Text == "async")
	if SimpleParser.IsTypeStart(self, kind) and not isContextualKeyword and self._position + 1 < #self._tokens then
		local next: SyntaxKind = self._tokens[self._position + 1 + 1].Kind
		if next == SyntaxKind.IdentifierToken then
			return SimpleParser.ParseLocalDeclaration(self)
		end
		if next == SyntaxKind.QuestionToken and self._position + 2 < #self._tokens and self._tokens[self._position + 2 + 1].Kind == SyntaxKind.IdentifierToken then
			return SimpleParser.ParseLocalDeclaration(self)
		end
		if next == SyntaxKind.OpenBracketToken and self._position + 3 < #self._tokens then
			if self._tokens[self._position + 2 + 1].Kind == SyntaxKind.CloseBracketToken and self._tokens[self._position + 3 + 1].Kind == SyntaxKind.IdentifierToken then
				return SimpleParser.ParseLocalDeclaration(self)
			end
		end
	end
	if kind == SyntaxKind.IdentifierToken and SimpleParser.Current(self).Text == "var" and self._position + 1 < #self._tokens then
		if self._tokens[self._position + 1 + 1].Kind == SyntaxKind.IdentifierToken then
			return SimpleParser.ParseLocalDeclaration(self)
		end
		if self._tokens[self._position + 1 + 1].Kind == SyntaxKind.OpenParenToken then
			return SimpleParser.ParseTupleDeconstruction(self)
		end
	end
	local expr: any = SimpleParser.ParseExpression(self)
	SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
	return ExpressionStatementSyntax.new(expr)
end

function SimpleParser.IsTypeStart(self: SimpleParser, kind: SyntaxKind): boolean
	return kind == SyntaxKind.IntKeyword or kind == SyntaxKind.StringKeyword or kind == SyntaxKind.BoolKeyword or kind == SyntaxKind.VoidKeyword or kind == SyntaxKind.FloatKeyword or kind == SyntaxKind.DoubleKeyword or kind == SyntaxKind.LongKeyword or kind == SyntaxKind.CharKeyword or kind == SyntaxKind.ObjectKeyword or kind == SyntaxKind.IdentifierToken
end

function SimpleParser.ParseReturnStatement(self: SimpleParser): ReturnStatementSyntax
	SimpleParser.Advance(self)
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.SemicolonToken then
		SimpleParser.Advance(self)
		return ReturnStatementSyntax.new(nil)
	end
	local expr: any = SimpleParser.ParseExpression(self)
	SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
	return ReturnStatementSyntax.new(expr)
end

function SimpleParser.ParseIfStatement(self: SimpleParser): IfStatementSyntax
	SimpleParser.Advance(self)
	SimpleParser.Expect(self, SyntaxKind.OpenParenToken)
	local condition: any = SimpleParser.ParseExpression(self)
	SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
	local thenBody: any = SimpleParser.ParseStatementOrBlock(self)
	local elseBody: StatementSyntax = nil
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.ElseKeyword then
		SimpleParser.Advance(self)
		elseBody = SimpleParser.ParseStatementOrBlock(self)
	end
	return IfStatementSyntax.new(condition, thenBody, elseBody)
end

function SimpleParser.ParseWhileStatement(self: SimpleParser): WhileStatementSyntax
	SimpleParser.Advance(self)
	SimpleParser.Expect(self, SyntaxKind.OpenParenToken)
	local condition: any = SimpleParser.ParseExpression(self)
	SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
	local body: any = SimpleParser.ParseStatementOrBlock(self)
	return WhileStatementSyntax.new(condition, body)
end

function SimpleParser.ParseForStatement(self: SimpleParser): ForStatementSyntax
	SimpleParser.Advance(self)
	SimpleParser.Expect(self, SyntaxKind.OpenParenToken)
	local declaration: StatementSyntax = nil
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.SemicolonToken then
		local initKind: SyntaxKind = SimpleParser.Current(self).Kind
		if SimpleParser.IsTypeStart(self, initKind) and self._position + 1 < #self._tokens then
			local next: SyntaxKind = self._tokens[self._position + 1 + 1].Kind
			if next == SyntaxKind.IdentifierToken then
				declaration = SimpleParser.ParseLocalDeclarationNoSemicolon(self)
			else
				local expr: any = SimpleParser.ParseExpression(self)
				declaration = ExpressionStatementSyntax.new(expr)
			end
		elseif initKind == SyntaxKind.IdentifierToken and SimpleParser.Current(self).Text == "var" and self._position + 1 < #self._tokens and self._tokens[self._position + 1 + 1].Kind == SyntaxKind.IdentifierToken then
			declaration = SimpleParser.ParseLocalDeclarationNoSemicolon(self)
		else
			local expr: any = SimpleParser.ParseExpression(self)
			declaration = ExpressionStatementSyntax.new(expr)
		end
	end
	SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
	local condition: ExpressionSyntax = nil
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.SemicolonToken then
		condition = SimpleParser.ParseExpression(self)
	end
	SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
	local incrementors: any = table.create(16)
	local incCount: number = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseParenToken do
		if incCount > 0 then
			SimpleParser.Expect(self, SyntaxKind.CommaToken)
		end
		if incCount < 16 then
			incrementors[incCount + 1] = SimpleParser.ParseExpression(self)
			incCount += 1
		end
	end
	SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
	local incResult: any = table.create(incCount)
	for i = 0, incCount - 1 do
		incResult[i + 1] = incrementors[i + 1]
	end
	local body: any = SimpleParser.ParseStatementOrBlock(self)
	return ForStatementSyntax.new(declaration, condition, incResult, body)
end

function SimpleParser.ParseLocalDeclarationNoSemicolon(self: SimpleParser): LocalDeclarationStatementSyntax
	local typeName: string = SimpleParser.ParseTypeName(self)
	local varName: string = SimpleParser.Current(self).Text
	SimpleParser.Advance(self)
	local initializer: ExpressionSyntax = nil
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.EqualsToken then
		SimpleParser.Advance(self)
		initializer = SimpleParser.ParseExpression(self)
	end
	return LocalDeclarationStatementSyntax.new(typeName, varName, initializer)
end

function SimpleParser.ParseForEachStatement(self: SimpleParser): ForEachStatementSyntax
	SimpleParser.Advance(self)
	SimpleParser.Expect(self, SyntaxKind.OpenParenToken)
	local typeName: string = SimpleParser.ParseTypeName(self)
	local identifier: string = SimpleParser.Current(self).Text
	SimpleParser.Advance(self)
	SimpleParser.Expect(self, SyntaxKind.InKeyword)
	local expression: any = SimpleParser.ParseExpression(self)
	SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
	local body: any = SimpleParser.ParseStatementOrBlock(self)
	return ForEachStatementSyntax.new(typeName, identifier, expression, body)
end

function SimpleParser.ParseDoStatement(self: SimpleParser): DoStatementSyntax
	SimpleParser.Advance(self)
	local body: any = SimpleParser.ParseStatementOrBlock(self)
	SimpleParser.Expect(self, SyntaxKind.WhileKeyword)
	SimpleParser.Expect(self, SyntaxKind.OpenParenToken)
	local condition: any = SimpleParser.ParseExpression(self)
	SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
	SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
	return DoStatementSyntax.new(body, condition)
end

function SimpleParser.ParseSwitchStatement(self: SimpleParser): SwitchStatementSyntax
	SimpleParser.Advance(self)
	SimpleParser.Expect(self, SyntaxKind.OpenParenToken)
	local expression: any = SimpleParser.ParseExpression(self)
	SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
	SimpleParser.Expect(self, SyntaxKind.OpenBraceToken)
	local sections: any = table.create(64)
	local sectionCount: number = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseBraceToken do
		local labels: any = table.create(16)
		local labelCount: number = 0
		while not SimpleParser.IsAtEnd(self) and (SimpleParser.Current(self).Kind == SyntaxKind.CaseKeyword or SimpleParser.Current(self).Kind == SyntaxKind.DefaultKeyword) do
			if SimpleParser.Current(self).Kind == SyntaxKind.CaseKeyword then
				SimpleParser.Advance(self)
				if labelCount < 16 then
					labels[labelCount + 1] = SimpleParser.ParseExpression(self)
					labelCount += 1
				end
				SimpleParser.Expect(self, SyntaxKind.ColonToken)
			else
				SimpleParser.Advance(self)
				if labelCount < 16 then
					labels[labelCount + 1] = nil
					labelCount += 1
				end
				SimpleParser.Expect(self, SyntaxKind.ColonToken)
			end
		end
		local statements: any = table.create(512)
		local stmtCount: number = 0
		while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CaseKeyword and SimpleParser.Current(self).Kind ~= SyntaxKind.DefaultKeyword and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseBraceToken do
			local stmt: any = SimpleParser.ParseStatement(self)
			if stmt ~= nil and stmtCount < 512 then
				statements[stmtCount + 1] = stmt
				stmtCount += 1
			end
		end
		local labelResult: any = table.create(labelCount)
		for i = 0, labelCount - 1 do
			labelResult[i + 1] = labels[i + 1]
		end
		local stmtResult: any = table.create(stmtCount)
		for i = 0, stmtCount - 1 do
			stmtResult[i + 1] = statements[i + 1]
		end
		if sectionCount < 64 then
			sections[sectionCount + 1] = SwitchSectionSyntax.new(labelResult, stmtResult)
			sectionCount += 1
		end
	end
	SimpleParser.Expect(self, SyntaxKind.CloseBraceToken)
	local sectionResult: any = table.create(sectionCount)
	for i = 0, sectionCount - 1 do
		sectionResult[i + 1] = sections[i + 1]
	end
	return SwitchStatementSyntax.new(expression, sectionResult)
end

function SimpleParser.ParseTryStatement(self: SimpleParser): TryStatementSyntax
	SimpleParser.Advance(self)
	local block: any = SimpleParser.ParseBlock(self)
	local catches: any = table.create(8)
	local catchCount: number = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.CatchKeyword do
		SimpleParser.Advance(self)
		local exceptionTypeName: string = nil
		local identifier: string = nil
		if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenParenToken then
			SimpleParser.Advance(self)
			exceptionTypeName = SimpleParser.ParseTypeName(self)
			if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.IdentifierToken then
				identifier = SimpleParser.Current(self).Text
				SimpleParser.Advance(self)
			end
			SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
		end
		local catchBlock: any = SimpleParser.ParseBlock(self)
		if catchCount < 8 then
			catches[catchCount + 1] = CatchClauseSyntax.new(exceptionTypeName, identifier, catchBlock)
			catchCount += 1
		end
	end
	local finallyBlock: BlockSyntax = nil
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.FinallyKeyword then
		SimpleParser.Advance(self)
		finallyBlock = SimpleParser.ParseBlock(self)
	end
	local catchResult: any = table.create(catchCount)
	for i = 0, catchCount - 1 do
		catchResult[i + 1] = catches[i + 1]
	end
	return TryStatementSyntax.new(block, catchResult, finallyBlock)
end

function SimpleParser.ParseThrowStatement(self: SimpleParser): ThrowStatementSyntax
	SimpleParser.Advance(self)
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.SemicolonToken then
		SimpleParser.Advance(self)
		return ThrowStatementSyntax.new(nil)
	end
	local expr: any = SimpleParser.ParseExpression(self)
	SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
	return ThrowStatementSyntax.new(expr)
end

function SimpleParser.ParseLockStatement(self: SimpleParser): LockStatementSyntax
	SimpleParser.Advance(self)
	SimpleParser.Expect(self, SyntaxKind.OpenParenToken)
	local expr: any = SimpleParser.ParseExpression(self)
	SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
	local block: any = SimpleParser.ParseBlock(self)
	return LockStatementSyntax.new(expr, block)
end

function SimpleParser.ParseUsingStatement(self: SimpleParser): StatementSyntax
	SimpleParser.Advance(self)
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.OpenParenToken then
		local typeName: string = SimpleParser.ParseTypeName(self)
		local varName: string = SimpleParser.Current(self).Text
		SimpleParser.Advance(self)
		local init: ExpressionSyntax = nil
		if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.EqualsToken then
			SimpleParser.Advance(self)
			init = SimpleParser.ParseExpression(self)
		end
		SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
		return LocalDeclarationStatementSyntax.new(typeName, varName, init)
	end
	SimpleParser.Expect(self, SyntaxKind.OpenParenToken)
	local decl: LocalDeclarationStatementSyntax = nil
	local usingExpr: ExpressionSyntax = nil
	local isDecl: boolean = false
	if SimpleParser.IsTypeStart(self, SimpleParser.Current(self).Kind) and self._position + 1 < #self._tokens and self._tokens[self._position + 1 + 1].Kind == SyntaxKind.IdentifierToken then
		isDecl = true
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.IdentifierToken and SimpleParser.Current(self).Text == "var" and self._position + 1 < #self._tokens and self._tokens[self._position + 1 + 1].Kind == SyntaxKind.IdentifierToken then
		isDecl = true
	end
	if isDecl then
		local typeName: string = SimpleParser.ParseTypeName(self)
		local varName: string = SimpleParser.Current(self).Text
		SimpleParser.Advance(self)
		local init: ExpressionSyntax = nil
		if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.EqualsToken then
			SimpleParser.Advance(self)
			init = SimpleParser.ParseExpression(self)
		end
		decl = LocalDeclarationStatementSyntax.new(typeName, varName, init)
	else
		usingExpr = SimpleParser.ParseExpression(self)
	end
	SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
	local block: any = SimpleParser.ParseBlock(self)
	return UsingStatementSyntax.new(decl, usingExpr, block)
end

function SimpleParser.ParseStatementOrBlock(self: SimpleParser): StatementSyntax
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBraceToken then
		return SimpleParser.ParseBlock(self)
	end
	return SimpleParser.ParseStatement(self)
end

function SimpleParser.ParseLocalDeclaration(self: SimpleParser): LocalDeclarationStatementSyntax
	local typeName: string = SimpleParser.ParseTypeName(self)
	local varName: string = SimpleParser.Current(self).Text
	SimpleParser.Advance(self)
	local initializer: ExpressionSyntax = nil
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.EqualsToken then
		SimpleParser.Advance(self)
		initializer = SimpleParser.ParseExpression(self)
	end
	SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
	return LocalDeclarationStatementSyntax.new(typeName, varName, initializer)
end

function SimpleParser.ParseTupleDeconstruction(self: SimpleParser): StatementSyntax
	SimpleParser.Advance(self)
	SimpleParser.Expect(self, SyntaxKind.OpenParenToken)
	local names: { string } = table.create(8)
	local nameCount: number = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseParenToken do
		if nameCount > 0 then
			SimpleParser.Expect(self, SyntaxKind.CommaToken)
		end
		if nameCount < 8 then
			names[nameCount + 1] = SimpleParser.Current(self).Text
			nameCount = nameCount + 1
		end
		SimpleParser.Advance(self)
	end
	SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
	SimpleParser.Expect(self, SyntaxKind.EqualsToken)
	local initializer: ExpressionSyntax = SimpleParser.ParseExpression(self)
	SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
	local trimmed: { string } = table.create(nameCount)
	for i = 0, nameCount - 1 do
		trimmed[i + 1] = names[i + 1]
	end
	return TupleDeconstructionStatementSyntax.new(trimmed, initializer)
end

function SimpleParser.ParseExpression(self: SimpleParser): ExpressionSyntax
	return SimpleParser.ParseAssignment(self)
end

function SimpleParser.ParseAssignment(self: SimpleParser): ExpressionSyntax
	local left: any = SimpleParser.ParseConditionalOr(self)
	if not SimpleParser.IsAtEnd(self) then
		local kind: SyntaxKind = SimpleParser.Current(self).Kind
		if kind == SyntaxKind.EqualsToken or kind == SyntaxKind.PlusEqualsToken or kind == SyntaxKind.MinusEqualsToken or kind == SyntaxKind.AsteriskEqualsToken or kind == SyntaxKind.SlashEqualsToken or kind == SyntaxKind.PercentEqualsToken or kind == SyntaxKind.QuestionQuestionEqualsToken then
			local op: any = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			local right: any = SimpleParser.ParseAssignment(self)
			local exprKind: number = if kind == SyntaxKind.EqualsToken then SyntaxKind.SimpleAssignmentExpression else if kind == SyntaxKind.PlusEqualsToken then SyntaxKind.AddAssignmentExpression else if kind == SyntaxKind.MinusEqualsToken then SyntaxKind.SubtractAssignmentExpression else if kind == SyntaxKind.AsteriskEqualsToken then SyntaxKind.MultiplyAssignmentExpression else if kind == SyntaxKind.SlashEqualsToken then SyntaxKind.DivideAssignmentExpression else if kind == SyntaxKind.PercentEqualsToken then SyntaxKind.ModuloAssignmentExpression else SyntaxKind.CoalesceAssignmentExpression
			return AssignmentExpressionSyntax.new(exprKind, left, op, right)
		end
		if kind == SyntaxKind.QuestionToken then
			SimpleParser.Advance(self)
			local whenTrue: any = SimpleParser.ParseExpression(self)
			SimpleParser.Expect(self, SyntaxKind.ColonToken)
			local whenFalse: any = SimpleParser.ParseExpression(self)
			return ConditionalExpressionSyntax.new(left, whenTrue, whenFalse)
		end
	end
	return left
end

function SimpleParser.ParseConditionalOr(self: SimpleParser): ExpressionSyntax
	local left: any = SimpleParser.ParseConditionalAnd(self)
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.BarBarToken do
		local op: any = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		local right: any = SimpleParser.ParseConditionalAnd(self)
		left = BinaryExpressionSyntax.new(8675, left, op, right)
	end
	return left
end

function SimpleParser.ParseConditionalAnd(self: SimpleParser): ExpressionSyntax
	local left: any = SimpleParser.ParseNullCoalescing(self)
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.AmpersandAmpersandToken do
		local op: any = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		local right: any = SimpleParser.ParseNullCoalescing(self)
		left = BinaryExpressionSyntax.new(8676, left, op, right)
	end
	return left
end

function SimpleParser.ParseNullCoalescing(self: SimpleParser): ExpressionSyntax
	local left: any = SimpleParser.ParseEquality(self)
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.QuestionQuestionToken do
		local op: any = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		local right: any = SimpleParser.ParseEquality(self)
		left = BinaryExpressionSyntax.new(8688, left, op, right)
	end
	return left
end

function SimpleParser.ParseEquality(self: SimpleParser): ExpressionSyntax
	local left: any = SimpleParser.ParseRelational(self)
	while not SimpleParser.IsAtEnd(self) do
		local kind: SyntaxKind = SimpleParser.Current(self).Kind
		if kind == SyntaxKind.EqualsEqualsToken or kind == SyntaxKind.ExclamationEqualsToken then
			local op: any = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			local right: any = SimpleParser.ParseRelational(self)
			local exprKind: number = if kind == SyntaxKind.EqualsEqualsToken then 8682 else 8683
			left = BinaryExpressionSyntax.new(exprKind, left, op, right)
		else
			break
		end
	end
	return left
end

function SimpleParser.ParseRelational(self: SimpleParser): ExpressionSyntax
	local left: any = SimpleParser.ParseAdditive(self)
	while not SimpleParser.IsAtEnd(self) do
		local kind: SyntaxKind = SimpleParser.Current(self).Kind
		if kind == SyntaxKind.LessThanToken or kind == SyntaxKind.GreaterThanToken or kind == SyntaxKind.LessThanEqualsToken or kind == SyntaxKind.GreaterThanEqualsToken then
			local op: any = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			local right: any = SimpleParser.ParseAdditive(self)
			local exprKind: number = if kind == SyntaxKind.LessThanToken then 8678 else if kind == SyntaxKind.GreaterThanToken then 8680 else if kind == SyntaxKind.LessThanEqualsToken then 8679 else 8681
			left = BinaryExpressionSyntax.new(exprKind, left, op, right)
		elseif kind == SyntaxKind.IsKeyword then
			local op: any = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			local typeName: string = SimpleParser.ParseTypeName(self)
			if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.IdentifierToken then
				local designation: string = SimpleParser.Current(self).Text
				SimpleParser.Advance(self)
				left = IsPatternExpressionSyntax.new(left, typeName, designation)
			else
				local typeIdent: any = SyntaxToken.new(SyntaxKind.IdentifierToken, typeName, 0, #typeName)
				local right: any = IdentifierNameSyntax.new(typeIdent)
				left = BinaryExpressionSyntax.new(8657, left, op, right)
			end
		elseif kind == SyntaxKind.AsKeyword then
			local op: any = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			local typeName: string = SimpleParser.ParseTypeName(self)
			local typeIdent: any = SyntaxToken.new(SyntaxKind.IdentifierToken, typeName, 0, #typeName)
			local right: any = IdentifierNameSyntax.new(typeIdent)
			left = BinaryExpressionSyntax.new(8658, left, op, right)
		else
			break
		end
	end
	return left
end

function SimpleParser.ParseAdditive(self: SimpleParser): ExpressionSyntax
	local left: any = SimpleParser.ParseMultiplicative(self)
	while not SimpleParser.IsAtEnd(self) do
		local kind: SyntaxKind = SimpleParser.Current(self).Kind
		if kind == SyntaxKind.PlusToken or kind == SyntaxKind.MinusToken then
			local op: any = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			local right: any = SimpleParser.ParseMultiplicative(self)
			local exprKind: number = if kind == SyntaxKind.PlusToken then 8668 else 8669
			left = BinaryExpressionSyntax.new(exprKind, left, op, right)
		else
			break
		end
	end
	return left
end

function SimpleParser.ParseMultiplicative(self: SimpleParser): ExpressionSyntax
	local left: any = SimpleParser.ParseUnary(self)
	while not SimpleParser.IsAtEnd(self) do
		local kind: SyntaxKind = SimpleParser.Current(self).Kind
		if kind == SyntaxKind.AsteriskToken or kind == SyntaxKind.SlashToken or kind == SyntaxKind.PercentToken then
			local op: any = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			local right: any = SimpleParser.ParseUnary(self)
			local exprKind: number = if kind == SyntaxKind.AsteriskToken then 8670 else if kind == SyntaxKind.SlashToken then 8671 else 8672
			left = BinaryExpressionSyntax.new(exprKind, left, op, right)
		else
			break
		end
	end
	return left
end

function SimpleParser.ParseUnary(self: SimpleParser): ExpressionSyntax
	if not SimpleParser.IsAtEnd(self) then
		local kind: SyntaxKind = SimpleParser.Current(self).Kind
		if kind == SyntaxKind.MinusToken or kind == SyntaxKind.ExclamationToken then
			local op: any = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			local operand: any = SimpleParser.ParseUnary(self)
			local exprKind: number = if kind == SyntaxKind.MinusToken then 8730 else 8731
			return PrefixUnaryExpressionSyntax.new(exprKind, op, operand)
		end
		if kind == SyntaxKind.AwaitKeyword or (kind == SyntaxKind.IdentifierToken and SimpleParser.Current(self).Text == "await") then
			local op: any = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			local operand: any = SimpleParser.ParseUnary(self)
			return PrefixUnaryExpressionSyntax.new(8740, op, operand)
		end
		if kind == SyntaxKind.PlusPlusToken or kind == SyntaxKind.MinusMinusToken then
			local op: any = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			local operand: any = SimpleParser.ParseUnary(self)
			local exprKind: number = if kind == SyntaxKind.PlusPlusToken then SyntaxKind.PreIncrementExpression else SyntaxKind.PreDecrementExpression
			return PrefixUnaryExpressionSyntax.new(exprKind, op, operand)
		end
	end
	return SimpleParser.ParsePrimary(self)
end

function SimpleParser.ParsePrimary(self: SimpleParser): ExpressionSyntax
	local expr: any = SimpleParser.ParseAtom(self)
	while not SimpleParser.IsAtEnd(self) do
		if SimpleParser.Current(self).Kind == SyntaxKind.DotToken then
			SimpleParser.Advance(self)
			local name: any = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			expr = MemberAccessExpressionSyntax.new(expr, name)
		elseif SimpleParser.Current(self).Kind == SyntaxKind.QuestionDotToken then
			SimpleParser.Advance(self)
			local name: any = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			local memberAccess: any = MemberAccessExpressionSyntax.new(expr, name)
			if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenParenToken then
				SimpleParser.Advance(self)
				local args: any = table.create(16)
				local argCount: number = 0
				while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseParenToken do
					if argCount > 0 then
						SimpleParser.Expect(self, SyntaxKind.CommaToken)
					end
					if argCount < 16 then
						args[argCount + 1] = SimpleParser.ParseExpression(self)
						argCount += 1
					end
				end
				SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
				local argResult: any = table.create(argCount)
				for i = 0, argCount - 1 do
					argResult[i + 1] = args[i + 1]
				end
				local invocation: any = InvocationExpressionSyntax.new(memberAccess, argResult)
				expr = ConditionalAccessExpressionSyntax.new(expr, invocation)
			else
				expr = ConditionalAccessExpressionSyntax.new(expr, memberAccess)
			end
		elseif SimpleParser.Current(self).Kind == SyntaxKind.OpenParenToken then
			SimpleParser.Advance(self)
			local args: any = table.create(16)
			local argCount: number = 0
			while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseParenToken do
				if argCount > 0 then
					SimpleParser.Expect(self, SyntaxKind.CommaToken)
				end
				if argCount < 16 then
					args[argCount + 1] = SimpleParser.ParseExpression(self)
					argCount += 1
				end
			end
			SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
			local argResult: any = table.create(argCount)
			for i = 0, argCount - 1 do
				argResult[i + 1] = args[i + 1]
			end
			expr = InvocationExpressionSyntax.new(expr, argResult)
		elseif SimpleParser.Current(self).Kind == SyntaxKind.OpenBracketToken then
			SimpleParser.Advance(self)
			local index: any = SimpleParser.ParseExpression(self)
			SimpleParser.Expect(self, SyntaxKind.CloseBracketToken)
			expr = ElementAccessExpressionSyntax.new(expr, index)
		elseif SimpleParser.Current(self).Kind == SyntaxKind.PlusPlusToken or SimpleParser.Current(self).Kind == SyntaxKind.MinusMinusToken then
			local opKind: any = SimpleParser.Current(self).Kind
			SimpleParser.Advance(self)
			local exprKind: number = if opKind == SyntaxKind.PlusPlusToken then SyntaxKind.PostIncrementExpression else SyntaxKind.PostDecrementExpression
			expr = PostfixUnaryExpressionSyntax.new(exprKind, expr, opKind)
		elseif SimpleParser.Current(self).Kind == SyntaxKind.SwitchKeyword then
			expr = SimpleParser.ParseSwitchExpression(self, expr)
		else
			break
		end
	end
	return expr
end

function SimpleParser.ParseAtom(self: SimpleParser): ExpressionSyntax
	if SimpleParser.IsAtEnd(self) then
		return LiteralExpressionSyntax.new(8753, SyntaxToken.new(0, "", 0, 0))
	end
	local kind: SyntaxKind = SimpleParser.Current(self).Kind
	if kind == SyntaxKind.NumericLiteralToken then
		local token: any = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		return LiteralExpressionSyntax.new(8750, token)
	end
	if kind == SyntaxKind.StringLiteralToken then
		local token: any = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		return LiteralExpressionSyntax.new(8751, token)
	end
	if kind == SyntaxKind.InterpolatedStringToken then
		local token: any = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		return LiteralExpressionSyntax.new(8655, token)
	end
	if kind == SyntaxKind.CharacterLiteralToken then
		local token: any = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		return LiteralExpressionSyntax.new(8752, token)
	end
	if kind == SyntaxKind.TrueKeyword then
		local token: any = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		return LiteralExpressionSyntax.new(8748, token)
	end
	if kind == SyntaxKind.FalseKeyword then
		local token: any = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		return LiteralExpressionSyntax.new(8749, token)
	end
	if kind == SyntaxKind.NullKeyword then
		local token: any = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		return LiteralExpressionSyntax.new(8754, token)
	end
	if kind == SyntaxKind.NewKeyword then
		return SimpleParser.ParseObjectCreation(self)
	end
	if kind == SyntaxKind.OpenParenToken then
		if SimpleParser.IsParenthesizedLambda(self) then
			return SimpleParser.ParseParenthesizedLambda(self)
		end
		local saved: number = self._position
		SimpleParser.Advance(self)
		if not SimpleParser.IsAtEnd(self) and SimpleParser.IsTypeStart(self, SimpleParser.Current(self).Kind) then
			local possibleType: string = SimpleParser.Current(self).Text
			local savedInner: number = self._position
			SimpleParser.Advance(self)
			if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.CloseParenToken then
				local savedAfterParen: number = self._position
				SimpleParser.Advance(self)
				if not SimpleParser.IsAtEnd(self) and SimpleParser.IsExpressionStart(self, SimpleParser.Current(self).Kind) then
					local operand: any = SimpleParser.ParseUnary(self)
					return CastExpressionSyntax.new(possibleType, operand)
				end
				self._position = savedAfterParen
			end
			self._position = savedInner
		end
		self._position = saved
		SimpleParser.Advance(self)
		local inner: any = SimpleParser.ParseExpression(self)
		SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
		return ParenthesizedExpressionSyntax.new(inner)
	end
	if kind == SyntaxKind.IdentifierToken and self._position + 1 < #self._tokens and self._tokens[self._position + 1 + 1].Kind == SyntaxKind.EqualsGreaterThanToken then
		return SimpleParser.ParseSimpleLambda(self)
	end
	if kind == SyntaxKind.ThisKeyword or kind == SyntaxKind.BaseKeyword then
		local token: any = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		return IdentifierNameSyntax.new(token)
	end
	if kind == SyntaxKind.IdentifierToken then
		local token: any = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		return IdentifierNameSyntax.new(token)
	end
	if SimpleParser.IsTypeStart(self, kind) then
		local token: any = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		return IdentifierNameSyntax.new(token)
	end
	local unknown: any = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
	return LiteralExpressionSyntax.new(8753, unknown)
end

function SimpleParser.ParseSwitchExpression(self: SimpleParser, governing: ExpressionSyntax): SwitchExpressionSyntax
	SimpleParser.Advance(self)
	SimpleParser.Expect(self, SyntaxKind.OpenBraceToken)
	local arms: any = table.create(64)
	local armCount: number = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseBraceToken do
		if armCount > 0 and SimpleParser.Current(self).Kind == SyntaxKind.CommaToken then
			SimpleParser.Advance(self)
		end
		if SimpleParser.Current(self).Kind == SyntaxKind.CloseBraceToken then
			break
		end
		local pattern: ExpressionSyntax = nil
		if SimpleParser.Current(self).Text == "_" then
			SimpleParser.Advance(self)
			pattern = nil
		else
			pattern = SimpleParser.ParseExpression(self)
		end
		SimpleParser.Expect(self, SyntaxKind.EqualsGreaterThanToken)
		local value: any = SimpleParser.ParseExpression(self)
		if armCount < 64 then
			arms[armCount + 1] = SwitchExpressionArmSyntax.new(pattern, value)
			armCount += 1
		end
	end
	SimpleParser.Expect(self, SyntaxKind.CloseBraceToken)
	local result: any = table.create(armCount)
	for i = 0, armCount - 1 do
		result[i + 1] = arms[i + 1]
	end
	return SwitchExpressionSyntax.new(governing, result)
end

function SimpleParser.ParseObjectCreation(self: SimpleParser): ExpressionSyntax
	SimpleParser.Advance(self)
	local typeName: string = SimpleParser.ParseTypeName(self)
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBracketToken then
		SimpleParser.Advance(self)
		local sizeExpr: ExpressionSyntax = nil
		if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseBracketToken then
			sizeExpr = SimpleParser.ParseExpression(self)
		end
		SimpleParser.Expect(self, SyntaxKind.CloseBracketToken)
		return ArrayCreationExpressionSyntax.new(typeName, sizeExpr)
	end
	local args: any = table.create(16)
	local argCount: number = 0
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenParenToken then
		SimpleParser.Advance(self)
		while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseParenToken do
			if argCount > 0 then
				SimpleParser.Expect(self, SyntaxKind.CommaToken)
			end
			if argCount < 16 then
				args[argCount + 1] = SimpleParser.ParseExpression(self)
				argCount += 1
			end
		end
		SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
	end
	local initializers: { AssignmentExpressionSyntax } = nil
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBraceToken then
		local isArrayType: boolean = #typeName > 2 and string.byte(typeName, #typeName - 1 + 1) == string.byte("]", 1) and string.byte(typeName, #typeName - 2 + 1) == string.byte("[", 1)
		if isArrayType then
			SimpleParser.Advance(self)
			while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseBraceToken do
				if argCount > 0 and SimpleParser.Current(self).Kind == SyntaxKind.CommaToken then
					SimpleParser.Advance(self)
				end
				if SimpleParser.Current(self).Kind == SyntaxKind.CloseBraceToken then
					break
				end
				if argCount < 16 then
					args[argCount + 1] = SimpleParser.ParseExpression(self)
					argCount += 1
				end
			end
			SimpleParser.Expect(self, SyntaxKind.CloseBraceToken)
		else
			SimpleParser.Advance(self)
			local inits: any = table.create(32)
			local initCount: number = 0
			while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseBraceToken do
				if initCount > 0 and SimpleParser.Current(self).Kind == SyntaxKind.CommaToken then
					SimpleParser.Advance(self)
				end
				if SimpleParser.Current(self).Kind == SyntaxKind.CloseBraceToken then
					break
				end
				local expr: any = SimpleParser.ParseExpression(self)
				local assign: AssignmentExpressionSyntax = expr
				if assign ~= nil and initCount < 32 then
					inits[initCount + 1] = assign
					initCount += 1
				end
			end
			SimpleParser.Expect(self, SyntaxKind.CloseBraceToken)
			initializers = table.create(initCount)
			for i = 0, initCount - 1 do
				initializers[i + 1] = inits[i + 1]
			end
		end
	end
	local result: any = table.create(argCount)
	for i = 0, argCount - 1 do
		result[i + 1] = args[i + 1]
	end
	return ObjectCreationExpressionSyntax.new(typeName, result, initializers)
end

function SimpleParser.IsExpressionStart(self: SimpleParser, kind: SyntaxKind): boolean
	return kind == SyntaxKind.IdentifierToken or kind == SyntaxKind.NumericLiteralToken or kind == SyntaxKind.StringLiteralToken or kind == SyntaxKind.CharacterLiteralToken or kind == SyntaxKind.TrueKeyword or kind == SyntaxKind.FalseKeyword or kind == SyntaxKind.NullKeyword or kind == SyntaxKind.OpenParenToken or kind == SyntaxKind.NewKeyword or kind == SyntaxKind.MinusToken or kind == SyntaxKind.ExclamationToken
end

function SimpleParser.IsParenthesizedLambda(self: SimpleParser): boolean
	if SimpleParser.Current(self).Kind ~= SyntaxKind.OpenParenToken then
		return false
	end
	local saved: number = self._position
	local depth: number = 0
	for i = self._position, #self._tokens - 1 do
		local k: SyntaxKind = self._tokens[i + 1].Kind
		if k == SyntaxKind.OpenParenToken then
			depth += 1
		elseif k == SyntaxKind.CloseParenToken then
			depth -= 1
			if depth == 0 then
				if i + 1 < #self._tokens and self._tokens[i + 1 + 1].Kind == SyntaxKind.EqualsGreaterThanToken then
					return true
				end
				return false
			end
		elseif k == SyntaxKind.SemicolonToken or k == SyntaxKind.OpenBraceToken then
			return false
		end
	end
	return false
end

function SimpleParser.ParseSimpleLambda(self: SimpleParser): LambdaExpressionSyntax
	local paramName: string = SimpleParser.Current(self).Text
	SimpleParser.Advance(self)
	SimpleParser.Advance(self)
	local paramNames: any = { paramName }
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBraceToken then
		local block: any = SimpleParser.ParseBlock(self)
		return LambdaExpressionSyntax.new(paramNames, nil, block)
	else
		local body: any = SimpleParser.ParseExpression(self)
		return LambdaExpressionSyntax.new(paramNames, body, nil)
	end
end

function SimpleParser.ParseParenthesizedLambda(self: SimpleParser): LambdaExpressionSyntax
	SimpleParser.Advance(self)
	local paramNames: any = table.create(16)
	local paramCount: number = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseParenToken do
		if paramCount > 0 then
			SimpleParser.Expect(self, SyntaxKind.CommaToken)
		end
		if SimpleParser.IsTypeStart(self, SimpleParser.Current(self).Kind) and self._position + 1 < #self._tokens and self._tokens[self._position + 1 + 1].Kind == SyntaxKind.IdentifierToken then
			SimpleParser.ParseTypeName(self)
			if paramCount < 16 then
				paramNames[paramCount + 1] = SimpleParser.Current(self).Text
				paramCount += 1
			end
			SimpleParser.Advance(self)
		else
			if paramCount < 16 then
				paramNames[paramCount + 1] = SimpleParser.Current(self).Text
				paramCount += 1
			end
			SimpleParser.Advance(self)
		end
	end
	SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
	SimpleParser.Advance(self)
	local paramResult: any = table.create(paramCount)
	for i = 0, paramCount - 1 do
		paramResult[i + 1] = paramNames[i + 1]
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBraceToken then
		local block: any = SimpleParser.ParseBlock(self)
		return LambdaExpressionSyntax.new(paramResult, nil, block)
	else
		local body: any = SimpleParser.ParseExpression(self)
		return LambdaExpressionSyntax.new(paramResult, body, nil)
	end
end


return { SimpleParser = SimpleParser }
