--!strict
-- Auto-generated by SimpleEmitter

type SlidingTextWindow_self = {
	InvalidCharacter: number;
	_text: string;
	_textEnd: number;
	Position: number;
	LexemeStartPosition: number;
}

local SlidingTextWindow = {}
SlidingTextWindow.__index = SlidingTextWindow
export type SlidingTextWindow = typeof(setmetatable({} :: SlidingTextWindow_self, SlidingTextWindow))

function SlidingTextWindow.new(text: string): SlidingTextWindow
	local self = setmetatable({
		InvalidCharacter = 65535,
		_text = "",
		_textEnd = 0,
		Position = 0,
		LexemeStartPosition = 0,
	} :: SlidingTextWindow_self, SlidingTextWindow)
	self._text = text
	self._textEnd = #text
	self.Position = 0
	self.LexemeStartPosition = 0
	return self
end

function SlidingTextWindow.CharAt(self: SlidingTextWindow, pos: number): number
	if pos >= 0 and pos < self._textEnd then
		return string.byte(self._text, pos + 1)
	end
	return self.InvalidCharacter
end

function SlidingTextWindow.Start(self: SlidingTextWindow): ()
	self.LexemeStartPosition = self.Position
end

function SlidingTextWindow.IsReallyAtEnd(self: SlidingTextWindow): boolean
	return self.Position >= self._textEnd
end

function SlidingTextWindow.PeekChar(self: SlidingTextWindow, delta: number): number
	local pos: number = self.Position + delta
	if pos < 0 or pos >= self._textEnd then
		return self.InvalidCharacter
	end
	return string.byte(self._text, pos + 1)
end

function SlidingTextWindow.NextChar(self: SlidingTextWindow): number
	if self.Position >= self._textEnd then
		return self.InvalidCharacter
	end
	local c: number = string.byte(self._text, self.Position + 1)
	self.Position += 1
	return c
end

function SlidingTextWindow.AdvanceChar(self: SlidingTextWindow, n: number): ()
	self.Position += n
end

function SlidingTextWindow.TryAdvance(self: SlidingTextWindow, c: number): boolean
	if SlidingTextWindow.PeekChar(self, 0) == c then
		SlidingTextWindow.AdvanceChar(self, 1)
		return true
	end
	return false
end

function SlidingTextWindow.Reset(self: SlidingTextWindow, position: number): ()
	self.Position = position
end

function SlidingTextWindow.GetText(self: SlidingTextWindow, intern: boolean): string
	local length: number = self.Position - self.LexemeStartPosition
	if length == 0 then
		return ""
	end
	return string.sub(self._text, self.LexemeStartPosition + 1, self.LexemeStartPosition + length)
end

function SlidingTextWindow.GetNewLineWidth(self: SlidingTextWindow): number
	local c: number = SlidingTextWindow.PeekChar(self, 0)
	if c == 13 then
		if SlidingTextWindow.PeekChar(self, 1) == 10 then
			return 2
		end
		return 1
	end
	if c == 10 or c == 133 or c == 8232 or c == 8233 then
		return 1
	end
	return 0
end

function SlidingTextWindow.AdvancePastNewLine(self: SlidingTextWindow): ()
	SlidingTextWindow.AdvanceChar(self, SlidingTextWindow.GetNewLineWidth(self))
end

function SlidingTextWindow.get_Width(self: SlidingTextWindow): number
	return self.Position - self.LexemeStartPosition
end

function SlidingTextWindow.get_TextLength(self: SlidingTextWindow): number
	return self._textEnd
end


return { SlidingTextWindow = SlidingTextWindow }
