--!strict
-- Auto-generated by LUSharpRoslynModule
-- Do not edit manually

type SyntaxNode_self = {
	Kind: number;
	Start: number;
	Length: number;
}

local SyntaxNode = {}
SyntaxNode.__index = SyntaxNode
export type SyntaxNode = typeof(setmetatable({} :: SyntaxNode_self, SyntaxNode))

function SyntaxNode.new(kind: number): SyntaxNode
	local self = setmetatable({
		Kind = 0,
		Start = 0,
		Length = 0,
	} :: SyntaxNode_self, SyntaxNode)
	self.Kind = kind
	return self
end

-- abstract: SyntaxNode.Accept

function SyntaxNode.AcceptWalker(self: SyntaxNode, walker: SyntaxWalker): ()
	walker:DefaultVisit(self)
end

function SyntaxNode.ToDisplayString(self: SyntaxNode): string
	return "SyntaxNode(" + self.Kind + ")"
end

local ExpressionSyntax = setmetatable({}, {__index = SyntaxNode})
ExpressionSyntax.__index = ExpressionSyntax
export type ExpressionSyntax = typeof(setmetatable({}, ExpressionSyntax))

function ExpressionSyntax.new(kind: number): ExpressionSyntax
	local self = setmetatable(SyntaxNode.new(kind) :: any, ExpressionSyntax)
	return self
end

local StatementSyntax = setmetatable({}, {__index = SyntaxNode})
StatementSyntax.__index = StatementSyntax
export type StatementSyntax = typeof(setmetatable({}, StatementSyntax))

function StatementSyntax.new(kind: number): StatementSyntax
	local self = setmetatable(SyntaxNode.new(kind) :: any, StatementSyntax)
	return self
end

local MemberDeclarationSyntax = setmetatable({}, {__index = SyntaxNode})
MemberDeclarationSyntax.__index = MemberDeclarationSyntax
export type MemberDeclarationSyntax = typeof(setmetatable({}, MemberDeclarationSyntax))

function MemberDeclarationSyntax.new(kind: number): MemberDeclarationSyntax
	local self = setmetatable(SyntaxNode.new(kind) :: any, MemberDeclarationSyntax)
	return self
end

return { SyntaxNode = SyntaxNode, ExpressionSyntax = ExpressionSyntax, StatementSyntax = StatementSyntax, MemberDeclarationSyntax = MemberDeclarationSyntax }
