--!strict
-- Auto-generated by SimpleEmitter

type SyntaxToken_self = {
	Kind: number;
	Text: string;
	Start: number;
	Length: number;
}

local SyntaxToken = {}
SyntaxToken.__index = SyntaxToken
export type SyntaxToken = typeof(setmetatable({} :: SyntaxToken_self, SyntaxToken))

function SyntaxToken.new(kind: number, text: string, start: number, length: number): SyntaxToken
	local self = setmetatable({
		Kind = 0,
		Text = "",
		Start = 0,
		Length = 0,
	} :: SyntaxToken_self, SyntaxToken)
	self.Kind = kind
	self.Text = text
	self.Start = start
	self.Length = length
	return self
end

function SyntaxToken.IsMissing(self: SyntaxToken): boolean
	return self.Kind == 0
end

function SyntaxToken.ToString(self: SyntaxToken): string
	return self.Text
end


return { SyntaxToken = SyntaxToken }
