--!strict
-- Auto-generated by LUSharpRoslynModule
-- Do not edit manually

local _SyntaxNode = require(script.Parent.SyntaxNode)
local ExpressionSyntax = _SyntaxNode.ExpressionSyntax

type LiteralExpressionSyntax_self = {
	Token: SyntaxToken;
}

local LiteralExpressionSyntax = setmetatable({}, {__index = ExpressionSyntax})
LiteralExpressionSyntax.__index = LiteralExpressionSyntax
export type LiteralExpressionSyntax = typeof(setmetatable({} :: LiteralExpressionSyntax_self, LiteralExpressionSyntax))

function LiteralExpressionSyntax.new(kind: number, token: SyntaxToken): LiteralExpressionSyntax
	local self = setmetatable(ExpressionSyntax.new(kind) :: any, LiteralExpressionSyntax)
	self.Token = nil :: any
	self.Token = token
	return self
end

function LiteralExpressionSyntax.Accept(self: LiteralExpressionSyntax): string
	return self.Token.Text
end

function LiteralExpressionSyntax.AcceptWalker(self: LiteralExpressionSyntax, walker: SyntaxWalker): ()
	walker:VisitLiteralExpression(self)
end

function LiteralExpressionSyntax.ToDisplayString(self: LiteralExpressionSyntax): string
	return "Literal(" .. self.Token.Text .. ")"
end

type IdentifierNameSyntax_self = {
	Identifier: SyntaxToken;
}

local IdentifierNameSyntax = setmetatable({}, {__index = ExpressionSyntax})
IdentifierNameSyntax.__index = IdentifierNameSyntax
export type IdentifierNameSyntax = typeof(setmetatable({} :: IdentifierNameSyntax_self, IdentifierNameSyntax))

function IdentifierNameSyntax.new(identifier: SyntaxToken): IdentifierNameSyntax
	local self = setmetatable(ExpressionSyntax.new(8616) :: any, IdentifierNameSyntax)
	self.Identifier = nil :: any
	self.Identifier = identifier
	return self
end

function IdentifierNameSyntax.Accept(self: IdentifierNameSyntax): string
	return self.Identifier.Text
end

function IdentifierNameSyntax.AcceptWalker(self: IdentifierNameSyntax, walker: SyntaxWalker): ()
	walker:VisitIdentifierName(self)
end

function IdentifierNameSyntax.ToDisplayString(self: IdentifierNameSyntax): string
	return "Identifier(" .. self.Identifier.Text .. ")"
end

type BinaryExpressionSyntax_self = {
	Left: ExpressionSyntax;
	OperatorToken: SyntaxToken;
	Right: ExpressionSyntax;
}

local BinaryExpressionSyntax = setmetatable({}, {__index = ExpressionSyntax})
BinaryExpressionSyntax.__index = BinaryExpressionSyntax
export type BinaryExpressionSyntax = typeof(setmetatable({} :: BinaryExpressionSyntax_self, BinaryExpressionSyntax))

function BinaryExpressionSyntax.new(kind: number, left: ExpressionSyntax, operatorToken: SyntaxToken, right: ExpressionSyntax): BinaryExpressionSyntax
	local self = setmetatable(ExpressionSyntax.new(kind) :: any, BinaryExpressionSyntax)
	self.Left = nil :: any
	self.OperatorToken = nil :: any
	self.Right = nil :: any
	self.Left = left
	self.OperatorToken = operatorToken
	self.Right = right
	return self
end

function BinaryExpressionSyntax.Accept(self: BinaryExpressionSyntax): string
	return self.Left:Accept() .. " " .. self.OperatorToken.Text .. " " .. self.Right:Accept()
end

function BinaryExpressionSyntax.AcceptWalker(self: BinaryExpressionSyntax, walker: SyntaxWalker): ()
	walker:VisitBinaryExpression(self)
end

function BinaryExpressionSyntax.ToDisplayString(self: BinaryExpressionSyntax): string
	return "Binary(" .. self.Left:ToDisplayString() .. " " .. self.OperatorToken.Text .. " " .. self.Right:ToDisplayString() .. ")"
end

type ParenthesizedExpressionSyntax_self = {
	Expression: ExpressionSyntax;
}

local ParenthesizedExpressionSyntax = setmetatable({}, {__index = ExpressionSyntax})
ParenthesizedExpressionSyntax.__index = ParenthesizedExpressionSyntax
export type ParenthesizedExpressionSyntax = typeof(setmetatable({} :: ParenthesizedExpressionSyntax_self, ParenthesizedExpressionSyntax))

function ParenthesizedExpressionSyntax.new(expression: ExpressionSyntax): ParenthesizedExpressionSyntax
	local self = setmetatable(ExpressionSyntax.new(8632) :: any, ParenthesizedExpressionSyntax)
	self.Expression = nil :: any
	self.Expression = expression
	return self
end

function ParenthesizedExpressionSyntax.Accept(self: ParenthesizedExpressionSyntax): string
	return "(" .. self.Expression:Accept() .. ")"
end

function ParenthesizedExpressionSyntax.AcceptWalker(self: ParenthesizedExpressionSyntax, walker: SyntaxWalker): ()
	walker:VisitParenthesizedExpression(self)
end

function ParenthesizedExpressionSyntax.ToDisplayString(self: ParenthesizedExpressionSyntax): string
	return "Paren(" .. self.Expression:ToDisplayString() .. ")"
end

type PrefixUnaryExpressionSyntax_self = {
	OperatorToken: SyntaxToken;
	Operand: ExpressionSyntax;
}

local PrefixUnaryExpressionSyntax = setmetatable({}, {__index = ExpressionSyntax})
PrefixUnaryExpressionSyntax.__index = PrefixUnaryExpressionSyntax
export type PrefixUnaryExpressionSyntax = typeof(setmetatable({} :: PrefixUnaryExpressionSyntax_self, PrefixUnaryExpressionSyntax))

function PrefixUnaryExpressionSyntax.new(kind: number, operatorToken: SyntaxToken, operand: ExpressionSyntax): PrefixUnaryExpressionSyntax
	local self = setmetatable(ExpressionSyntax.new(kind) :: any, PrefixUnaryExpressionSyntax)
	self.OperatorToken = nil :: any
	self.Operand = nil :: any
	self.OperatorToken = operatorToken
	self.Operand = operand
	return self
end

function PrefixUnaryExpressionSyntax.Accept(self: PrefixUnaryExpressionSyntax): string
	return self.OperatorToken.Text .. self.Operand:Accept()
end

function PrefixUnaryExpressionSyntax.AcceptWalker(self: PrefixUnaryExpressionSyntax, walker: SyntaxWalker): ()
	walker:VisitPrefixUnaryExpression(self)
end

function PrefixUnaryExpressionSyntax.ToDisplayString(self: PrefixUnaryExpressionSyntax): string
	return "PrefixUnary(" .. self.OperatorToken.Text .. self.Operand:ToDisplayString() .. ")"
end

type InvocationExpressionSyntax_self = {
	Expression: ExpressionSyntax;
	Arguments: { ExpressionSyntax };
}

local InvocationExpressionSyntax = setmetatable({}, {__index = ExpressionSyntax})
InvocationExpressionSyntax.__index = InvocationExpressionSyntax
export type InvocationExpressionSyntax = typeof(setmetatable({} :: InvocationExpressionSyntax_self, InvocationExpressionSyntax))

function InvocationExpressionSyntax.new(expression: ExpressionSyntax, arguments: { ExpressionSyntax }): InvocationExpressionSyntax
	local self = setmetatable(ExpressionSyntax.new(8634) :: any, InvocationExpressionSyntax)
	self.Expression = nil :: any
	self.Arguments = {}
	self.Expression = expression
	self.Arguments = arguments
	return self
end

function InvocationExpressionSyntax.Accept(self: InvocationExpressionSyntax): string
	local args = ""
	local i = 0
	while i < #self.Arguments do
		if i > 0 then
			args = args .. ", "
		end
		args = args .. self.Arguments[i + 1]:Accept()
		i += 1
	end
	return self.Expression:Accept() .. "(" .. args .. ")"
end

function InvocationExpressionSyntax.AcceptWalker(self: InvocationExpressionSyntax, walker: SyntaxWalker): ()
	walker:VisitInvocationExpression(self)
end

function InvocationExpressionSyntax.ToDisplayString(self: InvocationExpressionSyntax): string
	return "Invocation(" .. self.Expression:ToDisplayString() .. ")"
end

type MemberAccessExpressionSyntax_self = {
	Expression: ExpressionSyntax;
	Name: SyntaxToken;
}

local MemberAccessExpressionSyntax = setmetatable({}, {__index = ExpressionSyntax})
MemberAccessExpressionSyntax.__index = MemberAccessExpressionSyntax
export type MemberAccessExpressionSyntax = typeof(setmetatable({} :: MemberAccessExpressionSyntax_self, MemberAccessExpressionSyntax))

function MemberAccessExpressionSyntax.new(expression: ExpressionSyntax, name: SyntaxToken): MemberAccessExpressionSyntax
	local self = setmetatable(ExpressionSyntax.new(8689) :: any, MemberAccessExpressionSyntax)
	self.Expression = nil :: any
	self.Name = nil :: any
	self.Expression = expression
	self.Name = name
	return self
end

function MemberAccessExpressionSyntax.Accept(self: MemberAccessExpressionSyntax): string
	return self.Expression:Accept() .. "." .. self.Name.Text
end

function MemberAccessExpressionSyntax.AcceptWalker(self: MemberAccessExpressionSyntax, walker: SyntaxWalker): ()
	walker:VisitMemberAccessExpression(self)
end

function MemberAccessExpressionSyntax.ToDisplayString(self: MemberAccessExpressionSyntax): string
	return "MemberAccess(" .. self.Expression:ToDisplayString() .. "." .. self.Name.Text .. ")"
end

type AssignmentExpressionSyntax_self = {
	Left: ExpressionSyntax;
	OperatorToken: SyntaxToken;
	Right: ExpressionSyntax;
}

local AssignmentExpressionSyntax = setmetatable({}, {__index = ExpressionSyntax})
AssignmentExpressionSyntax.__index = AssignmentExpressionSyntax
export type AssignmentExpressionSyntax = typeof(setmetatable({} :: AssignmentExpressionSyntax_self, AssignmentExpressionSyntax))

function AssignmentExpressionSyntax.new(kind: number, left: ExpressionSyntax, operatorToken: SyntaxToken, right: ExpressionSyntax): AssignmentExpressionSyntax
	local self = setmetatable(ExpressionSyntax.new(kind) :: any, AssignmentExpressionSyntax)
	self.Left = nil :: any
	self.OperatorToken = nil :: any
	self.Right = nil :: any
	self.Left = left
	self.OperatorToken = operatorToken
	self.Right = right
	return self
end

function AssignmentExpressionSyntax.Accept(self: AssignmentExpressionSyntax): string
	return self.Left:Accept() .. " " .. self.OperatorToken.Text .. " " .. self.Right:Accept()
end

function AssignmentExpressionSyntax.AcceptWalker(self: AssignmentExpressionSyntax, walker: SyntaxWalker): ()
	walker:VisitAssignmentExpression(self)
end

function AssignmentExpressionSyntax.ToDisplayString(self: AssignmentExpressionSyntax): string
	return "Assignment(" .. self.Left:ToDisplayString() .. " " .. self.OperatorToken.Text .. " " .. self.Right:ToDisplayString() .. ")"
end

type ObjectCreationExpressionSyntax_self = {
	TypeName: string;
	Arguments: { ExpressionSyntax };
}

local ObjectCreationExpressionSyntax = setmetatable({}, {__index = ExpressionSyntax})
ObjectCreationExpressionSyntax.__index = ObjectCreationExpressionSyntax
export type ObjectCreationExpressionSyntax = typeof(setmetatable({} :: ObjectCreationExpressionSyntax_self, ObjectCreationExpressionSyntax))

function ObjectCreationExpressionSyntax.new(typeName: string, arguments: { ExpressionSyntax }): ObjectCreationExpressionSyntax
	local self = setmetatable(ExpressionSyntax.new(8649) :: any, ObjectCreationExpressionSyntax)
	self.TypeName = ""
	self.Arguments = {}
	self.TypeName = typeName
	self.Arguments = arguments
	return self
end

function ObjectCreationExpressionSyntax.Accept(self: ObjectCreationExpressionSyntax): string
	local args = ""
	local i = 0
	while i < #self.Arguments do
		if i > 0 then
			args += ", "
		end
		args += self.Arguments[i + 1]:Accept()
		i += 1
	end
	return "new " .. self.TypeName .. "(" .. args .. ")"
end

function ObjectCreationExpressionSyntax.AcceptWalker(self: ObjectCreationExpressionSyntax, walker: SyntaxWalker): ()
	walker:VisitObjectCreationExpression(self)
end

function ObjectCreationExpressionSyntax.ToDisplayString(self: ObjectCreationExpressionSyntax): string
	return "New(" .. self.TypeName .. ")"
end

type LambdaExpressionSyntax_self = {
	ParameterNames: { string };
	ExpressionBody: ExpressionSyntax;
	BlockBody: StatementSyntax;
}

local LambdaExpressionSyntax = setmetatable({}, {__index = ExpressionSyntax})
LambdaExpressionSyntax.__index = LambdaExpressionSyntax
export type LambdaExpressionSyntax = typeof(setmetatable({} :: LambdaExpressionSyntax_self, LambdaExpressionSyntax))

function LambdaExpressionSyntax.new(parameterNames: { string }, expressionBody: ExpressionSyntax, blockBody: StatementSyntax): LambdaExpressionSyntax
	local self = setmetatable(ExpressionSyntax.new(8643) :: any, LambdaExpressionSyntax)
	self.ParameterNames = {}
	self.ExpressionBody = nil :: any
	self.BlockBody = nil :: any
	self.ParameterNames = parameterNames
	self.ExpressionBody = expressionBody
	self.BlockBody = blockBody
	return self
end

function LambdaExpressionSyntax.Accept(self: LambdaExpressionSyntax): string
	local parms = ""
	if #self.ParameterNames == 1 then
		parms = self.ParameterNames[0 + 1]
	else
		parms = "("
		local i = 0
		while i < #self.ParameterNames do
			if i > 0 then
				parms += ", "
			end
			parms += self.ParameterNames[i + 1]
			i += 1
		end
		parms += ")"
	end
	if self.ExpressionBody ~= nil then
		return parms .. " => " .. self.ExpressionBody:Accept()
	end
	if self.BlockBody ~= nil then
		return parms .. " => " .. self.BlockBody:Accept()
	end
	return parms .. " => {}"
end

function LambdaExpressionSyntax.AcceptWalker(self: LambdaExpressionSyntax, walker: SyntaxWalker): ()
	walker:VisitLambdaExpression(self)
end

function LambdaExpressionSyntax.ToDisplayString(self: LambdaExpressionSyntax): string
	return "Lambda(" .. #self.ParameterNames .. " params)"
end

type CastExpressionSyntax_self = {
	TypeName: string;
	Expression: ExpressionSyntax;
}

local CastExpressionSyntax = setmetatable({}, {__index = ExpressionSyntax})
CastExpressionSyntax.__index = CastExpressionSyntax
export type CastExpressionSyntax = typeof(setmetatable({} :: CastExpressionSyntax_self, CastExpressionSyntax))

function CastExpressionSyntax.new(typeName: string, expression: ExpressionSyntax): CastExpressionSyntax
	local self = setmetatable(ExpressionSyntax.new(8640) :: any, CastExpressionSyntax)
	self.TypeName = ""
	self.Expression = nil :: any
	self.TypeName = typeName
	self.Expression = expression
	return self
end

function CastExpressionSyntax.Accept(self: CastExpressionSyntax): string
	return "(" .. self.TypeName .. ")" .. self.Expression:Accept()
end

function CastExpressionSyntax.AcceptWalker(self: CastExpressionSyntax, walker: SyntaxWalker): ()
	walker:VisitCastExpression(self)
end

function CastExpressionSyntax.ToDisplayString(self: CastExpressionSyntax): string
	return "Cast(" .. self.TypeName .. ")"
end

return { LiteralExpressionSyntax = LiteralExpressionSyntax, IdentifierNameSyntax = IdentifierNameSyntax, BinaryExpressionSyntax = BinaryExpressionSyntax, ParenthesizedExpressionSyntax = ParenthesizedExpressionSyntax, PrefixUnaryExpressionSyntax = PrefixUnaryExpressionSyntax, InvocationExpressionSyntax = InvocationExpressionSyntax, MemberAccessExpressionSyntax = MemberAccessExpressionSyntax, AssignmentExpressionSyntax = AssignmentExpressionSyntax, ObjectCreationExpressionSyntax = ObjectCreationExpressionSyntax, LambdaExpressionSyntax = LambdaExpressionSyntax, CastExpressionSyntax = CastExpressionSyntax }
