--!strict
-- Auto-generated by LUSharpRoslynModule
-- Do not edit manually

type SyntaxNode_self = {
	Kind: number;
}

local SyntaxNode = {}
SyntaxNode.__index = SyntaxNode
export type SyntaxNode = typeof(setmetatable({} :: SyntaxNode_self, SyntaxNode))

function SyntaxNode.new(kind: number): SyntaxNode
	local self = setmetatable({
		Kind = 0,
	} :: SyntaxNode_self, SyntaxNode)
	self.Kind = kind
	return self
end

-- abstract: SyntaxNode.GetDisplayText

function SyntaxNode.Describe(self: SyntaxNode): string
	return "SyntaxNode(Kind=" .. self.Kind .. ")"
end

type ExpressionNode_self = {
	Value: string;
}

local ExpressionNode = setmetatable({}, {__index = SyntaxNode})
ExpressionNode.__index = ExpressionNode
export type ExpressionNode = typeof(setmetatable({} :: ExpressionNode_self, ExpressionNode))

function ExpressionNode.new(kind: number, value: string): ExpressionNode
	local self = setmetatable(SyntaxNode.new(kind) :: any, ExpressionNode)
	self.Value = ""
	self.Value = value
	return self
end

function ExpressionNode.GetDisplayText(self: ExpressionNode): string
	return self.Value
end

function ExpressionNode.Describe(self: ExpressionNode): string
	return "ExpressionNode(Kind=" .. self.Kind .. ", Value=" .. self.Value .. ")"
end

local LiteralExpression = setmetatable({}, {__index = ExpressionNode})
LiteralExpression.__index = LiteralExpression
export type LiteralExpression = typeof(setmetatable({}, LiteralExpression))

function LiteralExpression.new(value: string): LiteralExpression
	local self = setmetatable(ExpressionNode.new(8750, value) :: any, LiteralExpression)
	return self
end

function LiteralExpression.GetDisplayText(self: LiteralExpression): string
	return "Literal:" .. self.Value
end

return { SyntaxNode = SyntaxNode, ExpressionNode = ExpressionNode, LiteralExpression = LiteralExpression }
