--!strict
-- Auto-generated by LUSharpRoslynModule
-- Do not edit manually

local LanguageFeaturesTest = {}
LanguageFeaturesTest.__index = LanguageFeaturesTest
export type LanguageFeaturesTest = typeof(setmetatable({}, LanguageFeaturesTest))

function LanguageFeaturesTest.SafeGetText(obj: any): string
	local __ok, __pcall_ret = pcall(function()
		return tostring(obj)
	end)
	if not __ok then
		return "error"
	end
	if __ok then return __pcall_ret end
end

function LanguageFeaturesTest.SafeGetTextWithVar(obj: any): string
	local __ok, __pcall_ret = pcall(function()
		return tostring(obj)
	end)
	if not __ok then
		local e = { Message = tostring(__pcall_ret) }
		return e.Message
	end
	if __ok then return __pcall_ret end
end

function LanguageFeaturesTest.SafeGetTextWithFinally(obj: any): string
	local result = ""
	local __ok, __pcall_ret = pcall(function()
		result = tostring(obj)
	end)
	if not __ok then
		local e = { Message = tostring(__pcall_ret) }
		result = e.Message
	end
	print("done")
	return result
end

function LanguageFeaturesTest.SumWithSkip(numbers: { number }, skipValue: number): number
	local sum = 0
	for _, n in numbers do
		if n == skipValue then
			continue
		end
		sum += n
	end
	return sum
end

function LanguageFeaturesTest.ApplyTransform(value: number, multiplier: number): number
	local result = value * multiplier
	return result
end

function LanguageFeaturesTest.GetOrDefault(value: string, fallback: string): string
	return (if value ~= nil then value else fallback)
end

function LanguageFeaturesTest.CountDown(start: number): number
	local count = 0
	local i = start
	repeat
		count += 1
		i -= 1
	until not (i > 0)
	return count
end

return { LanguageFeaturesTest = LanguageFeaturesTest }
