--!strict
-- Auto-generated by LUSharpRoslynModule
-- Do not edit manually

local _DeclarationNodes = require(script.Parent.DeclarationNodes)
local ClassDeclarationSyntax = _DeclarationNodes.ClassDeclarationSyntax
local CompilationUnitSyntax = _DeclarationNodes.CompilationUnitSyntax
local ConstructorDeclarationSyntax = _DeclarationNodes.ConstructorDeclarationSyntax
local EnumDeclarationSyntax = _DeclarationNodes.EnumDeclarationSyntax
local EnumMemberSyntax = _DeclarationNodes.EnumMemberSyntax
local FieldDeclarationSyntax = _DeclarationNodes.FieldDeclarationSyntax
local MethodDeclarationSyntax = _DeclarationNodes.MethodDeclarationSyntax
local ParameterSyntax = _DeclarationNodes.ParameterSyntax
local PropertyDeclarationSyntax = _DeclarationNodes.PropertyDeclarationSyntax
local StructDeclarationSyntax = _DeclarationNodes.StructDeclarationSyntax
local _ExpressionNodes = require(script.Parent.ExpressionNodes)
local AssignmentExpressionSyntax = _ExpressionNodes.AssignmentExpressionSyntax
local BinaryExpressionSyntax = _ExpressionNodes.BinaryExpressionSyntax
local CastExpressionSyntax = _ExpressionNodes.CastExpressionSyntax
local ConditionalExpressionSyntax = _ExpressionNodes.ConditionalExpressionSyntax
local ElementAccessExpressionSyntax = _ExpressionNodes.ElementAccessExpressionSyntax
local IdentifierNameSyntax = _ExpressionNodes.IdentifierNameSyntax
local InvocationExpressionSyntax = _ExpressionNodes.InvocationExpressionSyntax
local LambdaExpressionSyntax = _ExpressionNodes.LambdaExpressionSyntax
local LiteralExpressionSyntax = _ExpressionNodes.LiteralExpressionSyntax
local MemberAccessExpressionSyntax = _ExpressionNodes.MemberAccessExpressionSyntax
local ObjectCreationExpressionSyntax = _ExpressionNodes.ObjectCreationExpressionSyntax
local ParenthesizedExpressionSyntax = _ExpressionNodes.ParenthesizedExpressionSyntax
local PostfixUnaryExpressionSyntax = _ExpressionNodes.PostfixUnaryExpressionSyntax
local PrefixUnaryExpressionSyntax = _ExpressionNodes.PrefixUnaryExpressionSyntax
local SwitchExpressionArmSyntax = _ExpressionNodes.SwitchExpressionArmSyntax
local SwitchExpressionSyntax = _ExpressionNodes.SwitchExpressionSyntax
local _SimpleTokenizer = require(script.Parent.SimpleTokenizer)
local SimpleTokenizer = _SimpleTokenizer.SimpleTokenizer
local TokenInfo = _SimpleTokenizer.TokenInfo
local _StatementNodes = require(script.Parent.StatementNodes)
local BlockSyntax = _StatementNodes.BlockSyntax
local BreakStatementSyntax = _StatementNodes.BreakStatementSyntax
local CatchClauseSyntax = _StatementNodes.CatchClauseSyntax
local ContinueStatementSyntax = _StatementNodes.ContinueStatementSyntax
local DoStatementSyntax = _StatementNodes.DoStatementSyntax
local ExpressionStatementSyntax = _StatementNodes.ExpressionStatementSyntax
local ForEachStatementSyntax = _StatementNodes.ForEachStatementSyntax
local ForStatementSyntax = _StatementNodes.ForStatementSyntax
local IfStatementSyntax = _StatementNodes.IfStatementSyntax
local LocalDeclarationStatementSyntax = _StatementNodes.LocalDeclarationStatementSyntax
local ReturnStatementSyntax = _StatementNodes.ReturnStatementSyntax
local SwitchSectionSyntax = _StatementNodes.SwitchSectionSyntax
local SwitchStatementSyntax = _StatementNodes.SwitchStatementSyntax
local ThrowStatementSyntax = _StatementNodes.ThrowStatementSyntax
local TryStatementSyntax = _StatementNodes.TryStatementSyntax
local WhileStatementSyntax = _StatementNodes.WhileStatementSyntax
local _SyntaxKind = require(script.Parent.SyntaxKind)
local SyntaxKind = _SyntaxKind.SyntaxKind
local _SyntaxToken = require(script.Parent.SyntaxToken)
local SyntaxToken = _SyntaxToken.SyntaxToken

type SimpleParser_self = {
	_tokenizer: SimpleTokenizer;
	_tokens: { TokenInfo };
	_position: number;
	_currentClassName: string;
}

local SimpleParser = {}
SimpleParser.__index = SimpleParser
export type SimpleParser = typeof(setmetatable({} :: SimpleParser_self, SimpleParser))

function SimpleParser.new(text: string): SimpleParser
	local self = setmetatable({
		_tokenizer = nil :: any,
		_tokens = {},
		_position = 0,
		_currentClassName = "",
	} :: SimpleParser_self, SimpleParser)
	self._tokenizer = SimpleTokenizer.new(text)
	local tokenList = SimpleTokenizer.Tokenize(self._tokenizer)
	local filtered = table.create(#tokenList)
	local count = 0
	local i = 0
	while i < #tokenList do
		local t = tokenList[i + 1]
		if t.Kind ~= SyntaxKind.WhitespaceTrivia and t.Kind ~= SyntaxKind.EndOfLineTrivia and t.Kind ~= SyntaxKind.SingleLineCommentTrivia then
			filtered[count + 1] = t
			count += 1
		end
		i += 1
	end
	self._tokens = table.create(count)
	local i = 0
	while i < count do
		self._tokens[i + 1] = filtered[i + 1]
		i += 1
	end
	self._position = 0
	return self
end

function SimpleParser.Current(self: SimpleParser): TokenInfo
	if self._position >= #self._tokens then
		return TokenInfo.new(SyntaxKind.EndOfFileToken, "", 0, 0)
	end
	return self._tokens[self._position + 1]
end

function SimpleParser.Advance(self: SimpleParser): TokenInfo
	local token = SimpleParser.Current(self)
	self._position += 1
	return token
end

function SimpleParser.Expect(self: SimpleParser, kind: number): TokenInfo
	local token = SimpleParser.Current(self)
	if token.Kind ~= kind then
		return TokenInfo.new(kind, "", token.Start, 0)
	end
	return SimpleParser.Advance(self)
end

function SimpleParser.IsAtEnd(self: SimpleParser): boolean
	return self._position >= #self._tokens or SimpleParser.Current(self).Kind == SyntaxKind.EndOfFileToken
end

function SimpleParser.MakeSyntaxToken(self: SimpleParser, info: TokenInfo): SyntaxToken
	return SyntaxToken.new(info.Kind, info.Text, info.Start, #info)
end

function SimpleParser.ParseCompilationUnit(self: SimpleParser): CompilationUnitSyntax
	local members = table.create(256)
	local count = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.UsingKeyword do
		SimpleParser.SkipUsingDirective(self)
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.NamespaceKeyword then
		SimpleParser.SkipNamespaceHeader(self)
	end
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseBraceToken do
		local member = SimpleParser.ParseMemberDeclaration(self)
		if member ~= nil and count < 256 then
			members[count + 1] = member
			count += 1
		end
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.CloseBraceToken then
		SimpleParser.Advance(self)
	end
	local result = table.create(count)
	local i = 0
	while i < count do
		result[i + 1] = members[i + 1]
		i += 1
	end
	return CompilationUnitSyntax.new(result)
end

function SimpleParser.SkipUsingDirective(self: SimpleParser): ()
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.SemicolonToken do
		SimpleParser.Advance(self)
	end
	if not SimpleParser.IsAtEnd(self) then
		SimpleParser.Advance(self)
	end
end

function SimpleParser.SkipNamespaceHeader(self: SimpleParser): ()
	SimpleParser.Advance(self)
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.OpenBraceToken and SimpleParser.Current(self).Kind ~= SyntaxKind.SemicolonToken do
		SimpleParser.Advance(self)
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.SemicolonToken then
		SimpleParser.Advance(self)
		return
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBraceToken then
		SimpleParser.Advance(self)
	end
end

function SimpleParser.ParseMemberDeclaration(self: SimpleParser): MemberDeclarationSyntax
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBracketToken do
		SimpleParser.SkipAttributeList(self)
	end
	local isPublic = false
	local isPrivate = false
	local isStatic = false
	local isAbstract = false
	local isVirtual = false
	local isOverride = false
	while not SimpleParser.IsAtEnd(self) do
		local kind = SimpleParser.Current(self).Kind
		if kind == SyntaxKind.PublicKeyword then
			isPublic = true
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.PrivateKeyword then
			isPrivate = true
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.ProtectedKeyword then
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.InternalKeyword then
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.StaticKeyword then
			isStatic = true
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.AbstractKeyword then
			isAbstract = true
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.VirtualKeyword then
			isVirtual = true
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.OverrideKeyword then
			isOverride = true
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.ReadOnlyKeyword then
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.SealedKeyword then
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.NewKeyword then
			if self._position + 1 < #self._tokens then
				local next = self._tokens[self._position + 1 + 1].Kind
				if next == SyntaxKind.OpenParenToken or next == SyntaxKind.IdentifierToken or SimpleParser.IsTypeStart(self, next) then
					break
				end
			end
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.ConstKeyword then
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.VolatileKeyword then
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.ExternKeyword then
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.AsyncKeyword then
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.UnsafeKeyword then
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.PartialKeyword then
			SimpleParser.Advance(self)
		else
			break
		end
	end
	if SimpleParser.IsAtEnd(self) then
		return nil
	end
	if SimpleParser.Current(self).Kind == SyntaxKind.ClassKeyword then
		return SimpleParser.ParseClassDeclaration(self)
	end
	if SimpleParser.Current(self).Kind == SyntaxKind.EnumKeyword then
		return SimpleParser.ParseEnumDeclaration(self)
	end
	if SimpleParser.Current(self).Kind == SyntaxKind.StructKeyword then
		return SimpleParser.ParseStructDeclaration(self)
	end
	local typeName = SimpleParser.ParseTypeName(self)
	if typeName == nil or SimpleParser.IsAtEnd(self) then
		return nil
	end
	if typeName == self._currentClassName and SimpleParser.Current(self).Kind == SyntaxKind.OpenParenToken then
		return SimpleParser.ParseConstructorDeclaration(self, typeName)
	end
	local name = SimpleParser.Current(self).Text
	SimpleParser.Advance(self)
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenParenToken then
		return SimpleParser.ParseMethodDeclaration(self, typeName, name, isStatic)
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBraceToken then
		local saved = self._position
		SimpleParser.Advance(self)
		if not SimpleParser.IsAtEnd(self) and (SimpleParser.Current(self).Text == "get" or SimpleParser.Current(self).Text == "set") then
			self._position = saved
			return SimpleParser.ParsePropertyDeclaration(self, typeName, name, isStatic)
		end
		self._position = saved
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.EqualsGreaterThanToken then
		SimpleParser.Advance(self)
		local exprBody = SimpleParser.ParseExpression(self)
		SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
		return PropertyDeclarationSyntax.new(typeName, name, true, false, exprBody, isStatic)
	end
	local initializer = nil
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.EqualsToken then
		SimpleParser.Advance(self)
		initializer = SimpleParser.ParseExpression(self)
	end
	SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
	return FieldDeclarationSyntax.new(typeName, name, initializer, isStatic)
end

function SimpleParser.ParseClassDeclaration(self: SimpleParser): ClassDeclarationSyntax
	SimpleParser.Advance(self)
	local name = SimpleParser.Current(self).Text
	SimpleParser.Advance(self)
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.LessThanToken then
		local depth = 0
		while not SimpleParser.IsAtEnd(self) do
			if SimpleParser.Current(self).Kind == SyntaxKind.LessThanToken then
				depth += 1
			elseif SimpleParser.Current(self).Kind == SyntaxKind.GreaterThanToken then
				depth -= 1
				if depth == 0 then
					SimpleParser.Advance(self)
					break
				end
			end
			SimpleParser.Advance(self)
		end
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.ColonToken then
		SimpleParser.Advance(self)
		while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.OpenBraceToken do
			SimpleParser.Advance(self)
		end
	end
	SimpleParser.Expect(self, SyntaxKind.OpenBraceToken)
	local previousClassName = self._currentClassName
	self._currentClassName = name
	local members = table.create(256)
	local count = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseBraceToken do
		local member = SimpleParser.ParseMemberDeclaration(self)
		if member ~= nil and count < 256 then
			members[count + 1] = member
			count += 1
		end
	end
	self._currentClassName = previousClassName
	SimpleParser.Expect(self, SyntaxKind.CloseBraceToken)
	local result = table.create(count)
	local i = 0
	while i < count do
		result[i + 1] = members[i + 1]
		i += 1
	end
	return ClassDeclarationSyntax.new(name, result)
end

function SimpleParser.ParseEnumDeclaration(self: SimpleParser): EnumDeclarationSyntax
	SimpleParser.Advance(self)
	local name = SimpleParser.Current(self).Text
	SimpleParser.Advance(self)
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.ColonToken then
		SimpleParser.Advance(self)
		SimpleParser.ParseTypeName(self)
	end
	SimpleParser.Expect(self, SyntaxKind.OpenBraceToken)
	local members = table.create(256)
	local count = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseBraceToken do
		local memberName = SimpleParser.Current(self).Text
		SimpleParser.Advance(self)
		local value = nil
		if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.EqualsToken then
			SimpleParser.Advance(self)
			value = SimpleParser.ParseExpression(self)
		end
		if count < 256 then
			members[count + 1] = EnumMemberSyntax.new(memberName, value)
			count += 1
		end
		if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.CommaToken then
			SimpleParser.Advance(self)
		end
	end
	SimpleParser.Expect(self, SyntaxKind.CloseBraceToken)
	local result = table.create(count)
	local i = 0
	while i < count do
		result[i + 1] = members[i + 1]
		i += 1
	end
	return EnumDeclarationSyntax.new(name, result)
end

function SimpleParser.ParseStructDeclaration(self: SimpleParser): StructDeclarationSyntax
	SimpleParser.Advance(self)
	local name = SimpleParser.Current(self).Text
	SimpleParser.Advance(self)
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.LessThanToken then
		local depth = 0
		while not SimpleParser.IsAtEnd(self) do
			if SimpleParser.Current(self).Kind == SyntaxKind.LessThanToken then
				depth += 1
			elseif SimpleParser.Current(self).Kind == SyntaxKind.GreaterThanToken then
				depth -= 1
				if depth == 0 then
					SimpleParser.Advance(self)
					break
				end
			end
			SimpleParser.Advance(self)
		end
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.ColonToken then
		SimpleParser.Advance(self)
		while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.OpenBraceToken do
			SimpleParser.Advance(self)
		end
	end
	SimpleParser.Expect(self, SyntaxKind.OpenBraceToken)
	local previousClassName = self._currentClassName
	self._currentClassName = name
	local members = table.create(256)
	local count = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseBraceToken do
		local member = SimpleParser.ParseMemberDeclaration(self)
		if member ~= nil and count < 256 then
			members[count + 1] = member
			count += 1
		end
	end
	self._currentClassName = previousClassName
	SimpleParser.Expect(self, SyntaxKind.CloseBraceToken)
	local result = table.create(count)
	local i = 0
	while i < count do
		result[i + 1] = members[i + 1]
		i += 1
	end
	return StructDeclarationSyntax.new(name, result)
end

function SimpleParser.ParsePropertyDeclaration(self: SimpleParser, typeName: string, name: string, isStatic: boolean): PropertyDeclarationSyntax
	SimpleParser.Expect(self, SyntaxKind.OpenBraceToken)
	local hasGetter = false
	local hasSetter = false
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseBraceToken do
		if SimpleParser.Current(self).Text == "get" then
			hasGetter = true
			SimpleParser.Advance(self)
			if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.SemicolonToken then
				SimpleParser.Advance(self)
			elseif not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBraceToken then
				SimpleParser.SkipBlock(self)
			end
		elseif SimpleParser.Current(self).Text == "set" then
			hasSetter = true
			SimpleParser.Advance(self)
			if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.SemicolonToken then
				SimpleParser.Advance(self)
			elseif not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBraceToken then
				SimpleParser.SkipBlock(self)
			end
		else
			SimpleParser.Advance(self)
		end
	end
	SimpleParser.Expect(self, SyntaxKind.CloseBraceToken)
	return PropertyDeclarationSyntax.new(typeName, name, hasGetter, hasSetter, nil, isStatic)
end

function SimpleParser.ParseConstructorDeclaration(self: SimpleParser, name: string): ConstructorDeclarationSyntax
	SimpleParser.Advance(self)
	local parameters = table.create(16)
	local paramCount = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseParenToken do
		if paramCount > 0 then
			SimpleParser.Expect(self, SyntaxKind.CommaToken)
		end
		SimpleParser.SkipParameterModifiers(self)
		local paramType = SimpleParser.ParseTypeName(self)
		local paramName = SimpleParser.Current(self).Text
		SimpleParser.Advance(self)
		if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.EqualsToken then
			SimpleParser.Advance(self)
			SimpleParser.ParseExpression(self)
		end
		if paramCount < 16 then
			parameters[paramCount + 1] = ParameterSyntax.new(paramType, paramName)
			paramCount += 1
		end
	end
	SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
	local paramResult = table.create(paramCount)
	local i = 0
	while i < paramCount do
		paramResult[i + 1] = parameters[i + 1]
		i += 1
	end
	local baseOrThisKeyword = nil
	local initializerArgs = table.create(0)
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.ColonToken then
		SimpleParser.Advance(self)
		if not SimpleParser.IsAtEnd(self) and (SimpleParser.Current(self).Kind == SyntaxKind.BaseKeyword or SimpleParser.Current(self).Kind == SyntaxKind.ThisKeyword) then
			baseOrThisKeyword = SimpleParser.Current(self).Text
			SimpleParser.Advance(self)
			SimpleParser.Expect(self, SyntaxKind.OpenParenToken)
			local args = table.create(16)
			local argCount = 0
			while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseParenToken do
				if argCount > 0 then
					SimpleParser.Expect(self, SyntaxKind.CommaToken)
				end
				if argCount < 16 then
					args[argCount + 1] = SimpleParser.ParseExpression(self)
					argCount += 1
				end
			end
			SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
			initializerArgs = table.create(argCount)
			local i = 0
			while i < argCount do
				initializerArgs[i + 1] = args[i + 1]
				i += 1
			end
		else
			while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.OpenBraceToken and SimpleParser.Current(self).Kind ~= SyntaxKind.SemicolonToken do
				SimpleParser.Advance(self)
			end
		end
	end
	local body = nil
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBraceToken then
		body = SimpleParser.ParseBlock(self)
	elseif not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.SemicolonToken then
		SimpleParser.Advance(self)
	end
	return ConstructorDeclarationSyntax.new(name, paramResult, body, baseOrThisKeyword, initializerArgs)
end

function SimpleParser.SkipBlock(self: SimpleParser): ()
	local depth = 0
	if SimpleParser.Current(self).Kind == SyntaxKind.OpenBraceToken then
		depth = 1
		SimpleParser.Advance(self)
	end
	while not SimpleParser.IsAtEnd(self) and depth > 0 do
		if SimpleParser.Current(self).Kind == SyntaxKind.OpenBraceToken then
			depth += 1
		elseif SimpleParser.Current(self).Kind == SyntaxKind.CloseBraceToken then
			depth -= 1
		end
		SimpleParser.Advance(self)
	end
end

function SimpleParser.SkipAttributeList(self: SimpleParser): ()
	if SimpleParser.Current(self).Kind ~= SyntaxKind.OpenBracketToken then
		return
	end
	local depth = 1
	SimpleParser.Advance(self)
	while not SimpleParser.IsAtEnd(self) and depth > 0 do
		if SimpleParser.Current(self).Kind == SyntaxKind.OpenBracketToken then
			depth += 1
		elseif SimpleParser.Current(self).Kind == SyntaxKind.CloseBracketToken then
			depth -= 1
		end
		SimpleParser.Advance(self)
	end
end

function SimpleParser.SkipParameterModifiers(self: SimpleParser): ()
	while not SimpleParser.IsAtEnd(self) do
		local kind = SimpleParser.Current(self).Kind
		if kind == SyntaxKind.ParamsKeyword or kind == SyntaxKind.RefKeyword or kind == SyntaxKind.OutKeyword or kind == SyntaxKind.InKeyword or kind == SyntaxKind.ThisKeyword then
			SimpleParser.Advance(self)
		else
			break
		end
	end
end

function SimpleParser.ParseMethodDeclaration(self: SimpleParser, returnType: string, name: string, isStatic: boolean): MethodDeclarationSyntax
	SimpleParser.Advance(self)
	local parameters = table.create(16)
	local paramCount = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseParenToken do
		if paramCount > 0 then
			SimpleParser.Expect(self, SyntaxKind.CommaToken)
		end
		SimpleParser.SkipParameterModifiers(self)
		local paramType = SimpleParser.ParseTypeName(self)
		local paramName = SimpleParser.Current(self).Text
		SimpleParser.Advance(self)
		if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.EqualsToken then
			SimpleParser.Advance(self)
			SimpleParser.ParseExpression(self)
		end
		if paramCount < 16 then
			parameters[paramCount + 1] = ParameterSyntax.new(paramType, paramName)
			paramCount += 1
		end
	end
	SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
	local paramResult = table.create(paramCount)
	local i = 0
	while i < paramCount do
		paramResult[i + 1] = parameters[i + 1]
		i += 1
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.ColonToken then
		while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.OpenBraceToken and SimpleParser.Current(self).Kind ~= SyntaxKind.SemicolonToken do
			SimpleParser.Advance(self)
		end
	end
	local body = nil
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBraceToken then
		body = SimpleParser.ParseBlock(self)
	elseif not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.EqualsGreaterThanToken then
		SimpleParser.Advance(self)
		local expr = SimpleParser.ParseExpression(self)
		SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
		local returnStmt = ReturnStatementSyntax.new(expr)
		body = BlockSyntax.new({ returnStmt })
	elseif not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.SemicolonToken then
		SimpleParser.Advance(self)
	end
	return MethodDeclarationSyntax.new(returnType, name, paramResult, body, isStatic)
end

function SimpleParser.ParseTypeName(self: SimpleParser): string
	if SimpleParser.IsAtEnd(self) then
		return nil
	end
	local name = SimpleParser.Current(self).Text
	SimpleParser.Advance(self)
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.DotToken and self._position + 1 < #self._tokens and self._tokens[self._position + 1 + 1].Kind == SyntaxKind.IdentifierToken do
		SimpleParser.Advance(self)
		name = name .. "." .. SimpleParser.Current(self).Text
		SimpleParser.Advance(self)
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.LessThanToken then
		local depth = 0
		while not SimpleParser.IsAtEnd(self) do
			if SimpleParser.Current(self).Kind == SyntaxKind.LessThanToken then
				depth += 1
			elseif SimpleParser.Current(self).Kind == SyntaxKind.GreaterThanToken then
				depth -= 1
				if depth == 0 then
					SimpleParser.Advance(self)
					break
				end
			end
			SimpleParser.Advance(self)
		end
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBracketToken then
		SimpleParser.Advance(self)
		if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.CloseBracketToken then
			SimpleParser.Advance(self)
		end
		name = name .. "[]"
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.QuestionToken then
		SimpleParser.Advance(self)
		name = name .. "?"
	end
	return name
end

function SimpleParser.ParseBlock(self: SimpleParser): BlockSyntax
	SimpleParser.Expect(self, SyntaxKind.OpenBraceToken)
	local statements = table.create(128)
	local count = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseBraceToken do
		local stmt = SimpleParser.ParseStatement(self)
		if stmt ~= nil and count < 128 then
			statements[count + 1] = stmt
			count += 1
		end
	end
	SimpleParser.Expect(self, SyntaxKind.CloseBraceToken)
	local result = table.create(count)
	local i = 0
	while i < count do
		result[i + 1] = statements[i + 1]
		i += 1
	end
	return BlockSyntax.new(result)
end

function SimpleParser.ParseStatement(self: SimpleParser): StatementSyntax
	if SimpleParser.IsAtEnd(self) then
		return nil
	end
	local kind = SimpleParser.Current(self).Kind
	if kind == SyntaxKind.ReturnKeyword then
		return SimpleParser.ParseReturnStatement(self)
	end
	if kind == SyntaxKind.IfKeyword then
		return SimpleParser.ParseIfStatement(self)
	end
	if kind == SyntaxKind.WhileKeyword then
		return SimpleParser.ParseWhileStatement(self)
	end
	if kind == SyntaxKind.ForKeyword then
		return SimpleParser.ParseForStatement(self)
	end
	if kind == SyntaxKind.ForEachKeyword then
		return SimpleParser.ParseForEachStatement(self)
	end
	if kind == SyntaxKind.DoKeyword then
		return SimpleParser.ParseDoStatement(self)
	end
	if kind == SyntaxKind.BreakKeyword then
		SimpleParser.Advance(self)
		SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
		return BreakStatementSyntax.new()
	end
	if kind == SyntaxKind.ContinueKeyword then
		SimpleParser.Advance(self)
		SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
		return ContinueStatementSyntax.new()
	end
	if kind == SyntaxKind.SwitchKeyword then
		return SimpleParser.ParseSwitchStatement(self)
	end
	if kind == SyntaxKind.TryKeyword then
		return SimpleParser.ParseTryStatement(self)
	end
	if kind == SyntaxKind.ThrowKeyword then
		return SimpleParser.ParseThrowStatement(self)
	end
	if kind == SyntaxKind.OpenBraceToken then
		return SimpleParser.ParseBlock(self)
	end
	if SimpleParser.IsTypeStart(self, kind) and self._position + 1 < #self._tokens then
		local next = self._tokens[self._position + 1 + 1].Kind
		if next == SyntaxKind.IdentifierToken then
			return SimpleParser.ParseLocalDeclaration(self)
		end
		if next == SyntaxKind.OpenBracketToken and self._position + 3 < #self._tokens then
			if self._tokens[self._position + 2 + 1].Kind == SyntaxKind.CloseBracketToken and self._tokens[self._position + 3 + 1].Kind == SyntaxKind.IdentifierToken then
				return SimpleParser.ParseLocalDeclaration(self)
			end
		end
	end
	if kind == SyntaxKind.IdentifierToken and SimpleParser.Current(self).Text == "var" and self._position + 1 < #self._tokens then
		if self._tokens[self._position + 1 + 1].Kind == SyntaxKind.IdentifierToken then
			return SimpleParser.ParseLocalDeclaration(self)
		end
	end
	local expr = SimpleParser.ParseExpression(self)
	SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
	return ExpressionStatementSyntax.new(expr)
end

function SimpleParser.IsTypeStart(self: SimpleParser, kind: number): boolean
	return kind == SyntaxKind.IntKeyword or kind == SyntaxKind.StringKeyword or kind == SyntaxKind.BoolKeyword or kind == SyntaxKind.VoidKeyword or kind == SyntaxKind.FloatKeyword or kind == SyntaxKind.DoubleKeyword or kind == SyntaxKind.LongKeyword or kind == SyntaxKind.CharKeyword or kind == SyntaxKind.ObjectKeyword or kind == SyntaxKind.IdentifierToken
end

function SimpleParser.ParseReturnStatement(self: SimpleParser): ReturnStatementSyntax
	SimpleParser.Advance(self)
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.SemicolonToken then
		SimpleParser.Advance(self)
		return ReturnStatementSyntax.new(nil)
	end
	local expr = SimpleParser.ParseExpression(self)
	SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
	return ReturnStatementSyntax.new(expr)
end

function SimpleParser.ParseIfStatement(self: SimpleParser): IfStatementSyntax
	SimpleParser.Advance(self)
	SimpleParser.Expect(self, SyntaxKind.OpenParenToken)
	local condition = SimpleParser.ParseExpression(self)
	SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
	local thenBody = SimpleParser.ParseStatementOrBlock(self)
	local elseBody = nil
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.ElseKeyword then
		SimpleParser.Advance(self)
		elseBody = SimpleParser.ParseStatementOrBlock(self)
	end
	return IfStatementSyntax.new(condition, thenBody, elseBody)
end

function SimpleParser.ParseWhileStatement(self: SimpleParser): WhileStatementSyntax
	SimpleParser.Advance(self)
	SimpleParser.Expect(self, SyntaxKind.OpenParenToken)
	local condition = SimpleParser.ParseExpression(self)
	SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
	local body = SimpleParser.ParseStatementOrBlock(self)
	return WhileStatementSyntax.new(condition, body)
end

function SimpleParser.ParseForStatement(self: SimpleParser): ForStatementSyntax
	SimpleParser.Advance(self)
	SimpleParser.Expect(self, SyntaxKind.OpenParenToken)
	local declaration = nil
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.SemicolonToken then
		local initKind = SimpleParser.Current(self).Kind
		if SimpleParser.IsTypeStart(self, initKind) and self._position + 1 < #self._tokens then
			local next = self._tokens[self._position + 1 + 1].Kind
			if next == SyntaxKind.IdentifierToken then
				declaration = SimpleParser.ParseLocalDeclarationNoSemicolon(self)
			else
				local expr = SimpleParser.ParseExpression(self)
				declaration = ExpressionStatementSyntax.new(expr)
			end
		elseif initKind == SyntaxKind.IdentifierToken and SimpleParser.Current(self).Text == "var" and self._position + 1 < #self._tokens and self._tokens[self._position + 1 + 1].Kind == SyntaxKind.IdentifierToken then
			declaration = SimpleParser.ParseLocalDeclarationNoSemicolon(self)
		else
			local expr = SimpleParser.ParseExpression(self)
			declaration = ExpressionStatementSyntax.new(expr)
		end
	end
	SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
	local condition = nil
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.SemicolonToken then
		condition = SimpleParser.ParseExpression(self)
	end
	SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
	local incrementors = table.create(16)
	local incCount = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseParenToken do
		if incCount > 0 then
			SimpleParser.Expect(self, SyntaxKind.CommaToken)
		end
		if incCount < 16 then
			incrementors[incCount + 1] = SimpleParser.ParseExpression(self)
			incCount += 1
		end
	end
	SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
	local incResult = table.create(incCount)
	local i = 0
	while i < incCount do
		incResult[i + 1] = incrementors[i + 1]
		i += 1
	end
	local body = SimpleParser.ParseStatementOrBlock(self)
	return ForStatementSyntax.new(declaration, condition, incResult, body)
end

function SimpleParser.ParseLocalDeclarationNoSemicolon(self: SimpleParser): LocalDeclarationStatementSyntax
	local typeName = SimpleParser.ParseTypeName(self)
	local varName = SimpleParser.Current(self).Text
	SimpleParser.Advance(self)
	local initializer = nil
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.EqualsToken then
		SimpleParser.Advance(self)
		initializer = SimpleParser.ParseExpression(self)
	end
	return LocalDeclarationStatementSyntax.new(typeName, varName, initializer)
end

function SimpleParser.ParseForEachStatement(self: SimpleParser): ForEachStatementSyntax
	SimpleParser.Advance(self)
	SimpleParser.Expect(self, SyntaxKind.OpenParenToken)
	local typeName = SimpleParser.ParseTypeName(self)
	local identifier = SimpleParser.Current(self).Text
	SimpleParser.Advance(self)
	SimpleParser.Expect(self, SyntaxKind.InKeyword)
	local expression = SimpleParser.ParseExpression(self)
	SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
	local body = SimpleParser.ParseStatementOrBlock(self)
	return ForEachStatementSyntax.new(typeName, identifier, expression, body)
end

function SimpleParser.ParseDoStatement(self: SimpleParser): DoStatementSyntax
	SimpleParser.Advance(self)
	local body = SimpleParser.ParseStatementOrBlock(self)
	SimpleParser.Expect(self, SyntaxKind.WhileKeyword)
	SimpleParser.Expect(self, SyntaxKind.OpenParenToken)
	local condition = SimpleParser.ParseExpression(self)
	SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
	SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
	return DoStatementSyntax.new(body, condition)
end

function SimpleParser.ParseSwitchStatement(self: SimpleParser): SwitchStatementSyntax
	SimpleParser.Advance(self)
	SimpleParser.Expect(self, SyntaxKind.OpenParenToken)
	local expression = SimpleParser.ParseExpression(self)
	SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
	SimpleParser.Expect(self, SyntaxKind.OpenBraceToken)
	local sections = table.create(64)
	local sectionCount = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseBraceToken do
		local labels = table.create(16)
		local labelCount = 0
		while not SimpleParser.IsAtEnd(self) and (SimpleParser.Current(self).Kind == SyntaxKind.CaseKeyword or SimpleParser.Current(self).Kind == SyntaxKind.DefaultKeyword) do
			if SimpleParser.Current(self).Kind == SyntaxKind.CaseKeyword then
				SimpleParser.Advance(self)
				if labelCount < 16 then
					labels[labelCount + 1] = SimpleParser.ParseExpression(self)
					labelCount += 1
				end
				SimpleParser.Expect(self, SyntaxKind.ColonToken)
			else
				SimpleParser.Advance(self)
				if labelCount < 16 then
					labels[labelCount + 1] = nil
					labelCount += 1
				end
				SimpleParser.Expect(self, SyntaxKind.ColonToken)
			end
		end
		local statements = table.create(128)
		local stmtCount = 0
		while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CaseKeyword and SimpleParser.Current(self).Kind ~= SyntaxKind.DefaultKeyword and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseBraceToken do
			local stmt = SimpleParser.ParseStatement(self)
			if stmt ~= nil and stmtCount < 128 then
				statements[stmtCount + 1] = stmt
				stmtCount += 1
			end
		end
		local labelResult = table.create(labelCount)
		local i = 0
		while i < labelCount do
			labelResult[i + 1] = labels[i + 1]
			i += 1
		end
		local stmtResult = table.create(stmtCount)
		local i = 0
		while i < stmtCount do
			stmtResult[i + 1] = statements[i + 1]
			i += 1
		end
		if sectionCount < 64 then
			sections[sectionCount + 1] = SwitchSectionSyntax.new(labelResult, stmtResult)
			sectionCount += 1
		end
	end
	SimpleParser.Expect(self, SyntaxKind.CloseBraceToken)
	local sectionResult = table.create(sectionCount)
	local i = 0
	while i < sectionCount do
		sectionResult[i + 1] = sections[i + 1]
		i += 1
	end
	return SwitchStatementSyntax.new(expression, sectionResult)
end

function SimpleParser.ParseTryStatement(self: SimpleParser): TryStatementSyntax
	SimpleParser.Advance(self)
	local block = SimpleParser.ParseBlock(self)
	local catches = table.create(8)
	local catchCount = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.CatchKeyword do
		SimpleParser.Advance(self)
		local exceptionTypeName = nil
		local identifier = nil
		if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenParenToken then
			SimpleParser.Advance(self)
			exceptionTypeName = SimpleParser.ParseTypeName(self)
			if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.IdentifierToken then
				identifier = SimpleParser.Current(self).Text
				SimpleParser.Advance(self)
			end
			SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
		end
		local catchBlock = SimpleParser.ParseBlock(self)
		if catchCount < 8 then
			catches[catchCount + 1] = CatchClauseSyntax.new(exceptionTypeName, identifier, catchBlock)
			catchCount += 1
		end
	end
	local finallyBlock = nil
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.FinallyKeyword then
		SimpleParser.Advance(self)
		finallyBlock = SimpleParser.ParseBlock(self)
	end
	local catchResult = table.create(catchCount)
	local i = 0
	while i < catchCount do
		catchResult[i + 1] = catches[i + 1]
		i += 1
	end
	return TryStatementSyntax.new(block, catchResult, finallyBlock)
end

function SimpleParser.ParseThrowStatement(self: SimpleParser): ThrowStatementSyntax
	SimpleParser.Advance(self)
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.SemicolonToken then
		SimpleParser.Advance(self)
		return ThrowStatementSyntax.new(nil)
	end
	local expr = SimpleParser.ParseExpression(self)
	SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
	return ThrowStatementSyntax.new(expr)
end

function SimpleParser.ParseStatementOrBlock(self: SimpleParser): StatementSyntax
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBraceToken then
		return SimpleParser.ParseBlock(self)
	end
	return SimpleParser.ParseStatement(self)
end

function SimpleParser.ParseLocalDeclaration(self: SimpleParser): LocalDeclarationStatementSyntax
	local typeName = SimpleParser.ParseTypeName(self)
	local varName = SimpleParser.Current(self).Text
	SimpleParser.Advance(self)
	local initializer = nil
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.EqualsToken then
		SimpleParser.Advance(self)
		initializer = SimpleParser.ParseExpression(self)
	end
	SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
	return LocalDeclarationStatementSyntax.new(typeName, varName, initializer)
end

function SimpleParser.ParseExpression(self: SimpleParser): ExpressionSyntax
	return SimpleParser.ParseAssignment(self)
end

function SimpleParser.ParseAssignment(self: SimpleParser): ExpressionSyntax
	local left = SimpleParser.ParseConditionalOr(self)
	if not SimpleParser.IsAtEnd(self) then
		local kind = SimpleParser.Current(self).Kind
		if kind == SyntaxKind.EqualsToken or kind == SyntaxKind.PlusEqualsToken or kind == SyntaxKind.MinusEqualsToken or kind == SyntaxKind.AsteriskEqualsToken or kind == SyntaxKind.SlashEqualsToken or kind == SyntaxKind.PercentEqualsToken then
			local op = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			local right = SimpleParser.ParseAssignment(self)
			local exprKind = if kind == SyntaxKind.EqualsToken then SyntaxKind.SimpleAssignmentExpression else if kind == SyntaxKind.PlusEqualsToken then SyntaxKind.AddAssignmentExpression else if kind == SyntaxKind.MinusEqualsToken then SyntaxKind.SubtractAssignmentExpression else if kind == SyntaxKind.AsteriskEqualsToken then SyntaxKind.MultiplyAssignmentExpression else if kind == SyntaxKind.SlashEqualsToken then SyntaxKind.DivideAssignmentExpression else SyntaxKind.ModuloAssignmentExpression
			return AssignmentExpressionSyntax.new(exprKind, left, op, right)
		end
		if kind == SyntaxKind.QuestionToken then
			SimpleParser.Advance(self)
			local whenTrue = SimpleParser.ParseExpression(self)
			SimpleParser.Expect(self, SyntaxKind.ColonToken)
			local whenFalse = SimpleParser.ParseExpression(self)
			return ConditionalExpressionSyntax.new(left, whenTrue, whenFalse)
		end
	end
	return left
end

function SimpleParser.ParseConditionalOr(self: SimpleParser): ExpressionSyntax
	local left = SimpleParser.ParseConditionalAnd(self)
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.BarBarToken do
		local op = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		local right = SimpleParser.ParseConditionalAnd(self)
		left = BinaryExpressionSyntax.new(8675, left, op, right)
	end
	return left
end

function SimpleParser.ParseConditionalAnd(self: SimpleParser): ExpressionSyntax
	local left = SimpleParser.ParseNullCoalescing(self)
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.AmpersandAmpersandToken do
		local op = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		local right = SimpleParser.ParseNullCoalescing(self)
		left = BinaryExpressionSyntax.new(8676, left, op, right)
	end
	return left
end

function SimpleParser.ParseNullCoalescing(self: SimpleParser): ExpressionSyntax
	local left = SimpleParser.ParseEquality(self)
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.QuestionQuestionToken do
		local op = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		local right = SimpleParser.ParseEquality(self)
		left = BinaryExpressionSyntax.new(8688, left, op, right)
	end
	return left
end

function SimpleParser.ParseEquality(self: SimpleParser): ExpressionSyntax
	local left = SimpleParser.ParseRelational(self)
	while not SimpleParser.IsAtEnd(self) do
		local kind = SimpleParser.Current(self).Kind
		if kind == SyntaxKind.EqualsEqualsToken or kind == SyntaxKind.ExclamationEqualsToken then
			local op = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			local right = SimpleParser.ParseRelational(self)
			local exprKind = if kind == SyntaxKind.EqualsEqualsToken then 8682 else 8683
			left = BinaryExpressionSyntax.new(exprKind, left, op, right)
		else
			break
		end
	end
	return left
end

function SimpleParser.ParseRelational(self: SimpleParser): ExpressionSyntax
	local left = SimpleParser.ParseAdditive(self)
	while not SimpleParser.IsAtEnd(self) do
		local kind = SimpleParser.Current(self).Kind
		if kind == SyntaxKind.LessThanToken or kind == SyntaxKind.GreaterThanToken or kind == SyntaxKind.LessThanEqualsToken or kind == SyntaxKind.GreaterThanEqualsToken then
			local op = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			local right = SimpleParser.ParseAdditive(self)
			local exprKind = if kind == SyntaxKind.LessThanToken then 8678 else if kind == SyntaxKind.GreaterThanToken then 8680 else if kind == SyntaxKind.LessThanEqualsToken then 8679 else 8681
			left = BinaryExpressionSyntax.new(exprKind, left, op, right)
		elseif kind == SyntaxKind.IsKeyword then
			local op = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			local typeName = SimpleParser.ParseTypeName(self)
			local typeIdent = SyntaxToken.new(SyntaxKind.IdentifierToken, typeName, 0, #typeName)
			local right = IdentifierNameSyntax.new(typeIdent)
			left = BinaryExpressionSyntax.new(8657, left, op, right)
			if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.IdentifierToken then
				SimpleParser.Advance(self)
			end
		elseif kind == SyntaxKind.AsKeyword then
			local op = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			local typeName = SimpleParser.ParseTypeName(self)
			local typeIdent = SyntaxToken.new(SyntaxKind.IdentifierToken, typeName, 0, #typeName)
			local right = IdentifierNameSyntax.new(typeIdent)
			left = BinaryExpressionSyntax.new(8658, left, op, right)
		else
			break
		end
	end
	return left
end

function SimpleParser.ParseAdditive(self: SimpleParser): ExpressionSyntax
	local left = SimpleParser.ParseMultiplicative(self)
	while not SimpleParser.IsAtEnd(self) do
		local kind = SimpleParser.Current(self).Kind
		if kind == SyntaxKind.PlusToken or kind == SyntaxKind.MinusToken then
			local op = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			local right = SimpleParser.ParseMultiplicative(self)
			local exprKind = if kind == SyntaxKind.PlusToken then 8668 else 8669
			left = BinaryExpressionSyntax.new(exprKind, left, op, right)
		else
			break
		end
	end
	return left
end

function SimpleParser.ParseMultiplicative(self: SimpleParser): ExpressionSyntax
	local left = SimpleParser.ParseUnary(self)
	while not SimpleParser.IsAtEnd(self) do
		local kind = SimpleParser.Current(self).Kind
		if kind == SyntaxKind.AsteriskToken or kind == SyntaxKind.SlashToken or kind == SyntaxKind.PercentToken then
			local op = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			local right = SimpleParser.ParseUnary(self)
			local exprKind = if kind == SyntaxKind.AsteriskToken then 8670 else if kind == SyntaxKind.SlashToken then 8671 else 8672
			left = BinaryExpressionSyntax.new(exprKind, left, op, right)
		else
			break
		end
	end
	return left
end

function SimpleParser.ParseUnary(self: SimpleParser): ExpressionSyntax
	if not SimpleParser.IsAtEnd(self) then
		local kind = SimpleParser.Current(self).Kind
		if kind == SyntaxKind.MinusToken or kind == SyntaxKind.ExclamationToken then
			local op = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			local operand = SimpleParser.ParseUnary(self)
			local exprKind = if kind == SyntaxKind.MinusToken then 8730 else 8731
			return PrefixUnaryExpressionSyntax.new(exprKind, op, operand)
		end
		if kind == SyntaxKind.PlusPlusToken or kind == SyntaxKind.MinusMinusToken then
			local op = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			local operand = SimpleParser.ParseUnary(self)
			local exprKind = if kind == SyntaxKind.PlusPlusToken then SyntaxKind.PreIncrementExpression else SyntaxKind.PreDecrementExpression
			return PrefixUnaryExpressionSyntax.new(exprKind, op, operand)
		end
	end
	return SimpleParser.ParsePrimary(self)
end

function SimpleParser.ParsePrimary(self: SimpleParser): ExpressionSyntax
	local expr = SimpleParser.ParseAtom(self)
	while not SimpleParser.IsAtEnd(self) do
		if SimpleParser.Current(self).Kind == SyntaxKind.DotToken then
			SimpleParser.Advance(self)
			local name = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			expr = MemberAccessExpressionSyntax.new(expr, name)
		elseif SimpleParser.Current(self).Kind == SyntaxKind.OpenParenToken then
			SimpleParser.Advance(self)
			local args = table.create(16)
			local argCount = 0
			while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseParenToken do
				if argCount > 0 then
					SimpleParser.Expect(self, SyntaxKind.CommaToken)
				end
				if argCount < 16 then
					args[argCount + 1] = SimpleParser.ParseExpression(self)
					argCount += 1
				end
			end
			SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
			local argResult = table.create(argCount)
			local i = 0
			while i < argCount do
				argResult[i + 1] = args[i + 1]
				i += 1
			end
			expr = InvocationExpressionSyntax.new(expr, argResult)
		elseif SimpleParser.Current(self).Kind == SyntaxKind.OpenBracketToken then
			SimpleParser.Advance(self)
			local index = SimpleParser.ParseExpression(self)
			SimpleParser.Expect(self, SyntaxKind.CloseBracketToken)
			expr = ElementAccessExpressionSyntax.new(expr, index)
		elseif SimpleParser.Current(self).Kind == SyntaxKind.PlusPlusToken or SimpleParser.Current(self).Kind == SyntaxKind.MinusMinusToken then
			local opKind = SimpleParser.Current(self).Kind
			SimpleParser.Advance(self)
			local exprKind = if opKind == SyntaxKind.PlusPlusToken then SyntaxKind.PostIncrementExpression else SyntaxKind.PostDecrementExpression
			expr = PostfixUnaryExpressionSyntax.new(exprKind, expr, opKind)
		elseif SimpleParser.Current(self).Kind == SyntaxKind.SwitchKeyword then
			expr = SimpleParser.ParseSwitchExpression(self, expr)
		else
			break
		end
	end
	return expr
end

function SimpleParser.ParseAtom(self: SimpleParser): ExpressionSyntax
	if SimpleParser.IsAtEnd(self) then
		return LiteralExpressionSyntax.new(8753, SyntaxToken.new(0, "", 0, 0))
	end
	local kind = SimpleParser.Current(self).Kind
	if kind == SyntaxKind.NumericLiteralToken then
		local token = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		return LiteralExpressionSyntax.new(8750, token)
	end
	if kind == SyntaxKind.StringLiteralToken then
		local token = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		return LiteralExpressionSyntax.new(8751, token)
	end
	if kind == SyntaxKind.CharacterLiteralToken then
		local token = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		return LiteralExpressionSyntax.new(8752, token)
	end
	if kind == SyntaxKind.TrueKeyword then
		local token = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		return LiteralExpressionSyntax.new(8748, token)
	end
	if kind == SyntaxKind.FalseKeyword then
		local token = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		return LiteralExpressionSyntax.new(8749, token)
	end
	if kind == SyntaxKind.NullKeyword then
		local token = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		return LiteralExpressionSyntax.new(8754, token)
	end
	if kind == SyntaxKind.NewKeyword then
		return SimpleParser.ParseObjectCreation(self)
	end
	if kind == SyntaxKind.OpenParenToken then
		if SimpleParser.IsParenthesizedLambda(self) then
			return SimpleParser.ParseParenthesizedLambda(self)
		end
		local saved = self._position
		SimpleParser.Advance(self)
		if not SimpleParser.IsAtEnd(self) and SimpleParser.IsTypeStart(self, SimpleParser.Current(self).Kind) then
			local possibleType = SimpleParser.Current(self).Text
			local savedInner = self._position
			SimpleParser.Advance(self)
			if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.CloseParenToken then
				local savedAfterParen = self._position
				SimpleParser.Advance(self)
				if not SimpleParser.IsAtEnd(self) and SimpleParser.IsExpressionStart(self, SimpleParser.Current(self).Kind) then
					local operand = SimpleParser.ParseUnary(self)
					return CastExpressionSyntax.new(possibleType, operand)
				end
				self._position = savedAfterParen
			end
			self._position = savedInner
		end
		self._position = saved
		SimpleParser.Advance(self)
		local inner = SimpleParser.ParseExpression(self)
		SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
		return ParenthesizedExpressionSyntax.new(inner)
	end
	if kind == SyntaxKind.IdentifierToken and self._position + 1 < #self._tokens and self._tokens[self._position + 1 + 1].Kind == SyntaxKind.EqualsGreaterThanToken then
		return SimpleParser.ParseSimpleLambda(self)
	end
	if kind == SyntaxKind.IdentifierToken then
		local token = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		return IdentifierNameSyntax.new(token)
	end
	if SimpleParser.IsTypeStart(self, kind) then
		local token = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		return IdentifierNameSyntax.new(token)
	end
	local unknown = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
	return LiteralExpressionSyntax.new(8753, unknown)
end

function SimpleParser.ParseSwitchExpression(self: SimpleParser, governing: ExpressionSyntax): SwitchExpressionSyntax
	SimpleParser.Advance(self)
	SimpleParser.Expect(self, SyntaxKind.OpenBraceToken)
	local arms = table.create(64)
	local armCount = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseBraceToken do
		if armCount > 0 and SimpleParser.Current(self).Kind == SyntaxKind.CommaToken then
			SimpleParser.Advance(self)
		end
		if SimpleParser.Current(self).Kind == SyntaxKind.CloseBraceToken then
			break
		end
		local pattern = nil
		if SimpleParser.Current(self).Text == "_" then
			SimpleParser.Advance(self)
			pattern = nil
		else
			pattern = SimpleParser.ParseExpression(self)
		end
		SimpleParser.Expect(self, SyntaxKind.EqualsGreaterThanToken)
		local value = SimpleParser.ParseExpression(self)
		if armCount < 64 then
			arms[armCount + 1] = SwitchExpressionArmSyntax.new(pattern, value)
			armCount += 1
		end
	end
	SimpleParser.Expect(self, SyntaxKind.CloseBraceToken)
	local result = table.create(armCount)
	local i = 0
	while i < armCount do
		result[i + 1] = arms[i + 1]
		i += 1
	end
	return SwitchExpressionSyntax.new(governing, result)
end

function SimpleParser.ParseObjectCreation(self: SimpleParser): ObjectCreationExpressionSyntax
	SimpleParser.Advance(self)
	local typeName = SimpleParser.ParseTypeName(self)
	local args = table.create(16)
	local argCount = 0
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenParenToken then
		SimpleParser.Advance(self)
		while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseParenToken do
			if argCount > 0 then
				SimpleParser.Expect(self, SyntaxKind.CommaToken)
			end
			if argCount < 16 then
				args[argCount + 1] = SimpleParser.ParseExpression(self)
				argCount += 1
			end
		end
		SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
	end
	local initializers = nil
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBraceToken then
		SimpleParser.Advance(self)
		local inits = table.create(32)
		local initCount = 0
		while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseBraceToken do
			if initCount > 0 and SimpleParser.Current(self).Kind == SyntaxKind.CommaToken then
				SimpleParser.Advance(self)
			end
			if SimpleParser.Current(self).Kind == SyntaxKind.CloseBraceToken then
				break
			end
			local expr = SimpleParser.ParseExpression(self)
			if --[[TODO: IsPatternExpression]] nil and initCount < 32 then
				inits[initCount + 1] = assign
				initCount += 1
			end
		end
		SimpleParser.Expect(self, SyntaxKind.CloseBraceToken)
		initializers = table.create(initCount)
		local i = 0
		while i < initCount do
			initializers[i + 1] = inits[i + 1]
			i += 1
		end
	end
	local result = table.create(argCount)
	local i = 0
	while i < argCount do
		result[i + 1] = args[i + 1]
		i += 1
	end
	return ObjectCreationExpressionSyntax.new(typeName, result, initializers)
end

function SimpleParser.IsExpressionStart(self: SimpleParser, kind: number): boolean
	return kind == SyntaxKind.IdentifierToken or kind == SyntaxKind.NumericLiteralToken or kind == SyntaxKind.StringLiteralToken or kind == SyntaxKind.CharacterLiteralToken or kind == SyntaxKind.TrueKeyword or kind == SyntaxKind.FalseKeyword or kind == SyntaxKind.NullKeyword or kind == SyntaxKind.OpenParenToken or kind == SyntaxKind.NewKeyword or kind == SyntaxKind.MinusToken or kind == SyntaxKind.ExclamationToken
end

function SimpleParser.IsParenthesizedLambda(self: SimpleParser): boolean
	if SimpleParser.Current(self).Kind ~= SyntaxKind.OpenParenToken then
		return false
	end
	local saved = self._position
	local depth = 0
	local i = self._position
	while i < #self._tokens do
		local k = self._tokens[i + 1].Kind
		if k == SyntaxKind.OpenParenToken then
			depth += 1
		elseif k == SyntaxKind.CloseParenToken then
			depth -= 1
			if depth == 0 then
				if i + 1 < #self._tokens and self._tokens[i + 1 + 1].Kind == SyntaxKind.EqualsGreaterThanToken then
					return true
				end
				return false
			end
		elseif k == SyntaxKind.SemicolonToken or k == SyntaxKind.OpenBraceToken then
			return false
		end
		i += 1
	end
	return false
end

function SimpleParser.ParseSimpleLambda(self: SimpleParser): LambdaExpressionSyntax
	local paramName = SimpleParser.Current(self).Text
	SimpleParser.Advance(self)
	SimpleParser.Advance(self)
	local paramNames = { paramName }
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBraceToken then
		local block = SimpleParser.ParseBlock(self)
		return LambdaExpressionSyntax.new(paramNames, nil, block)
	else
		local body = SimpleParser.ParseExpression(self)
		return LambdaExpressionSyntax.new(paramNames, body, nil)
	end
end

function SimpleParser.ParseParenthesizedLambda(self: SimpleParser): LambdaExpressionSyntax
	SimpleParser.Advance(self)
	local paramNames = table.create(16)
	local paramCount = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseParenToken do
		if paramCount > 0 then
			SimpleParser.Expect(self, SyntaxKind.CommaToken)
		end
		if SimpleParser.IsTypeStart(self, SimpleParser.Current(self).Kind) and self._position + 1 < #self._tokens and self._tokens[self._position + 1 + 1].Kind == SyntaxKind.IdentifierToken then
			SimpleParser.ParseTypeName(self)
			if paramCount < 16 then
				paramNames[paramCount + 1] = SimpleParser.Current(self).Text
				paramCount += 1
			end
			SimpleParser.Advance(self)
		else
			if paramCount < 16 then
				paramNames[paramCount + 1] = SimpleParser.Current(self).Text
				paramCount += 1
			end
			SimpleParser.Advance(self)
		end
	end
	SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
	SimpleParser.Advance(self)
	local paramResult = table.create(paramCount)
	local i = 0
	while i < paramCount do
		paramResult[i + 1] = paramNames[i + 1]
		i += 1
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBraceToken then
		local block = SimpleParser.ParseBlock(self)
		return LambdaExpressionSyntax.new(paramResult, nil, block)
	else
		local body = SimpleParser.ParseExpression(self)
		return LambdaExpressionSyntax.new(paramResult, body, nil)
	end
end

return { SimpleParser = SimpleParser }
