--!strict
-- Auto-generated by LUSharpRoslynModule
-- Do not edit manually

local _DeclarationNodes = require(script.Parent.DeclarationNodes)
local ClassDeclarationSyntax = _DeclarationNodes.ClassDeclarationSyntax
local CompilationUnitSyntax = _DeclarationNodes.CompilationUnitSyntax
local FieldDeclarationSyntax = _DeclarationNodes.FieldDeclarationSyntax
local MethodDeclarationSyntax = _DeclarationNodes.MethodDeclarationSyntax
local ParameterSyntax = _DeclarationNodes.ParameterSyntax
local _ExpressionNodes = require(script.Parent.ExpressionNodes)
local AssignmentExpressionSyntax = _ExpressionNodes.AssignmentExpressionSyntax
local BinaryExpressionSyntax = _ExpressionNodes.BinaryExpressionSyntax
local IdentifierNameSyntax = _ExpressionNodes.IdentifierNameSyntax
local InvocationExpressionSyntax = _ExpressionNodes.InvocationExpressionSyntax
local LiteralExpressionSyntax = _ExpressionNodes.LiteralExpressionSyntax
local MemberAccessExpressionSyntax = _ExpressionNodes.MemberAccessExpressionSyntax
local ParenthesizedExpressionSyntax = _ExpressionNodes.ParenthesizedExpressionSyntax
local PrefixUnaryExpressionSyntax = _ExpressionNodes.PrefixUnaryExpressionSyntax
local _SimpleTokenizer = require(script.Parent.SimpleTokenizer)
local SimpleTokenizer = _SimpleTokenizer.SimpleTokenizer
local TokenInfo = _SimpleTokenizer.TokenInfo
local _StatementNodes = require(script.Parent.StatementNodes)
local BlockSyntax = _StatementNodes.BlockSyntax
local ExpressionStatementSyntax = _StatementNodes.ExpressionStatementSyntax
local IfStatementSyntax = _StatementNodes.IfStatementSyntax
local LocalDeclarationStatementSyntax = _StatementNodes.LocalDeclarationStatementSyntax
local ReturnStatementSyntax = _StatementNodes.ReturnStatementSyntax
local WhileStatementSyntax = _StatementNodes.WhileStatementSyntax
local _SyntaxKind = require(script.Parent.SyntaxKind)
local SyntaxKind = _SyntaxKind.SyntaxKind
local _SyntaxToken = require(script.Parent.SyntaxToken)
local SyntaxToken = _SyntaxToken.SyntaxToken

type SimpleParser_self = {
	_tokenizer: SimpleTokenizer;
	_tokens: { TokenInfo };
	_position: number;
}

local SimpleParser = {}
SimpleParser.__index = SimpleParser
export type SimpleParser = typeof(setmetatable({} :: SimpleParser_self, SimpleParser))

function SimpleParser.new(text: string): SimpleParser
	local self = setmetatable({
		_tokenizer = nil :: any,
		_tokens = {},
		_position = 0,
	} :: SimpleParser_self, SimpleParser)
	self._tokenizer = SimpleTokenizer.new(text)
	local tokenList = SimpleTokenizer.Tokenize(self._tokenizer)
	local filtered = table.create(#tokenList)
	local count = 0
	local i = 0
	while i < #tokenList do
		local t = tokenList[i + 1]
		if t.Kind ~= SyntaxKind.WhitespaceTrivia and t.Kind ~= SyntaxKind.EndOfLineTrivia and t.Kind ~= SyntaxKind.SingleLineCommentTrivia then
			filtered[count + 1] = t
			count += 1
		end
		i += 1
	end
	self._tokens = table.create(count)
	local i = 0
	while i < count do
		self._tokens[i + 1] = filtered[i + 1]
		i += 1
	end
	self._position = 0
	return self
end

function SimpleParser.Current(self: SimpleParser): TokenInfo
	if self._position >= #self._tokens then
		return TokenInfo.new(SyntaxKind.EndOfFileToken, "", 0, 0)
	end
	return self._tokens[self._position + 1]
end

function SimpleParser.Advance(self: SimpleParser): TokenInfo
	local token = SimpleParser.Current(self)
	self._position += 1
	return token
end

function SimpleParser.Expect(self: SimpleParser, kind: number): TokenInfo
	local token = SimpleParser.Current(self)
	if token.Kind ~= kind then
		return TokenInfo.new(kind, "", token.Start, 0)
	end
	return SimpleParser.Advance(self)
end

function SimpleParser.IsAtEnd(self: SimpleParser): boolean
	return self._position >= #self._tokens or SimpleParser.Current(self).Kind == SyntaxKind.EndOfFileToken
end

function SimpleParser.MakeSyntaxToken(self: SimpleParser, info: TokenInfo): SyntaxToken
	return SyntaxToken.new(info.Kind, info.Text, info.Start, #info)
end

function SimpleParser.ParseCompilationUnit(self: SimpleParser): CompilationUnitSyntax
	local members = table.create(64)
	local count = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.UsingKeyword do
		SimpleParser.SkipUsingDirective(self)
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.NamespaceKeyword then
		SimpleParser.SkipNamespaceHeader(self)
	end
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseBraceToken do
		local member = SimpleParser.ParseMemberDeclaration(self)
		if member ~= nil and count < 64 then
			members[count + 1] = member
			count += 1
		end
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.CloseBraceToken then
		SimpleParser.Advance(self)
	end
	local result = table.create(count)
	local i = 0
	while i < count do
		result[i + 1] = members[i + 1]
		i += 1
	end
	return CompilationUnitSyntax.new(result)
end

function SimpleParser.SkipUsingDirective(self: SimpleParser): ()
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.SemicolonToken do
		SimpleParser.Advance(self)
	end
	if not SimpleParser.IsAtEnd(self) then
		SimpleParser.Advance(self)
	end
end

function SimpleParser.SkipNamespaceHeader(self: SimpleParser): ()
	SimpleParser.Advance(self)
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.OpenBraceToken and SimpleParser.Current(self).Kind ~= SyntaxKind.SemicolonToken do
		SimpleParser.Advance(self)
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.SemicolonToken then
		SimpleParser.Advance(self)
		return
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBraceToken then
		SimpleParser.Advance(self)
	end
end

function SimpleParser.ParseMemberDeclaration(self: SimpleParser): MemberDeclarationSyntax
	local isPublic = false
	local isPrivate = false
	local isStatic = false
	local isAbstract = false
	local isVirtual = false
	local isOverride = false
	while not SimpleParser.IsAtEnd(self) do
		local kind = SimpleParser.Current(self).Kind
		if kind == SyntaxKind.PublicKeyword then
			isPublic = true
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.PrivateKeyword then
			isPrivate = true
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.ProtectedKeyword then
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.InternalKeyword then
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.StaticKeyword then
			isStatic = true
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.AbstractKeyword then
			isAbstract = true
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.VirtualKeyword then
			isVirtual = true
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.OverrideKeyword then
			isOverride = true
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.ReadOnlyKeyword then
			SimpleParser.Advance(self)
		elseif kind == SyntaxKind.SealedKeyword then
			SimpleParser.Advance(self)
		else
			break
		end
	end
	if SimpleParser.IsAtEnd(self) then
		return nil
	end
	if SimpleParser.Current(self).Kind == SyntaxKind.ClassKeyword then
		return SimpleParser.ParseClassDeclaration(self)
	end
	local typeName = SimpleParser.ParseTypeName(self)
	if typeName == nil or SimpleParser.IsAtEnd(self) then
		return nil
	end
	local name = SimpleParser.Current(self).Text
	SimpleParser.Advance(self)
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenParenToken then
		return SimpleParser.ParseMethodDeclaration(self, typeName, name, isStatic)
	end
	local initializer = nil
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.EqualsToken then
		SimpleParser.Advance(self)
		initializer = SimpleParser.ParseExpression(self)
	end
	SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
	return FieldDeclarationSyntax.new(typeName, name, initializer, isStatic)
end

function SimpleParser.ParseClassDeclaration(self: SimpleParser): ClassDeclarationSyntax
	SimpleParser.Advance(self)
	local name = SimpleParser.Current(self).Text
	SimpleParser.Advance(self)
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.ColonToken then
		SimpleParser.Advance(self)
		while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.OpenBraceToken do
			SimpleParser.Advance(self)
		end
	end
	SimpleParser.Expect(self, SyntaxKind.OpenBraceToken)
	local members = table.create(64)
	local count = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseBraceToken do
		local member = SimpleParser.ParseMemberDeclaration(self)
		if member ~= nil and count < 64 then
			members[count + 1] = member
			count += 1
		end
	end
	SimpleParser.Expect(self, SyntaxKind.CloseBraceToken)
	local result = table.create(count)
	local i = 0
	while i < count do
		result[i + 1] = members[i + 1]
		i += 1
	end
	return ClassDeclarationSyntax.new(name, result)
end

function SimpleParser.ParseMethodDeclaration(self: SimpleParser, returnType: string, name: string, isStatic: boolean): MethodDeclarationSyntax
	SimpleParser.Advance(self)
	local parameters = table.create(16)
	local paramCount = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseParenToken do
		if paramCount > 0 then
			SimpleParser.Expect(self, SyntaxKind.CommaToken)
		end
		local paramType = SimpleParser.ParseTypeName(self)
		local paramName = SimpleParser.Current(self).Text
		SimpleParser.Advance(self)
		if paramCount < 16 then
			parameters[paramCount + 1] = ParameterSyntax.new(paramType, paramName)
			paramCount += 1
		end
	end
	SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
	local paramResult = table.create(paramCount)
	local i = 0
	while i < paramCount do
		paramResult[i + 1] = parameters[i + 1]
		i += 1
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.ColonToken then
		while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.OpenBraceToken and SimpleParser.Current(self).Kind ~= SyntaxKind.SemicolonToken do
			SimpleParser.Advance(self)
		end
	end
	local body = nil
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBraceToken then
		body = SimpleParser.ParseBlock(self)
	elseif not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.SemicolonToken then
		SimpleParser.Advance(self)
	end
	return MethodDeclarationSyntax.new(returnType, name, paramResult, body, isStatic)
end

function SimpleParser.ParseTypeName(self: SimpleParser): string
	if SimpleParser.IsAtEnd(self) then
		return nil
	end
	local name = SimpleParser.Current(self).Text
	SimpleParser.Advance(self)
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBracketToken then
		SimpleParser.Advance(self)
		if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.CloseBracketToken then
			SimpleParser.Advance(self)
		end
		name = name .. "[]"
	end
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.QuestionToken then
		SimpleParser.Advance(self)
		name = name .. "?"
	end
	return name
end

function SimpleParser.ParseBlock(self: SimpleParser): BlockSyntax
	SimpleParser.Expect(self, SyntaxKind.OpenBraceToken)
	local statements = table.create(128)
	local count = 0
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseBraceToken do
		local stmt = SimpleParser.ParseStatement(self)
		if stmt ~= nil and count < 128 then
			statements[count + 1] = stmt
			count += 1
		end
	end
	SimpleParser.Expect(self, SyntaxKind.CloseBraceToken)
	local result = table.create(count)
	local i = 0
	while i < count do
		result[i + 1] = statements[i + 1]
		i += 1
	end
	return BlockSyntax.new(result)
end

function SimpleParser.ParseStatement(self: SimpleParser): StatementSyntax
	if SimpleParser.IsAtEnd(self) then
		return nil
	end
	local kind = SimpleParser.Current(self).Kind
	if kind == SyntaxKind.ReturnKeyword then
		return SimpleParser.ParseReturnStatement(self)
	end
	if kind == SyntaxKind.IfKeyword then
		return SimpleParser.ParseIfStatement(self)
	end
	if kind == SyntaxKind.WhileKeyword then
		return SimpleParser.ParseWhileStatement(self)
	end
	if kind == SyntaxKind.OpenBraceToken then
		return SimpleParser.ParseBlock(self)
	end
	if SimpleParser.IsTypeStart(self, kind) and self._position + 1 < #self._tokens then
		local next = self._tokens[self._position + 1 + 1].Kind
		if next == SyntaxKind.IdentifierToken then
			return SimpleParser.ParseLocalDeclaration(self)
		end
		if next == SyntaxKind.OpenBracketToken and self._position + 3 < #self._tokens then
			if self._tokens[self._position + 2 + 1].Kind == SyntaxKind.CloseBracketToken and self._tokens[self._position + 3 + 1].Kind == SyntaxKind.IdentifierToken then
				return SimpleParser.ParseLocalDeclaration(self)
			end
		end
	end
	if kind == SyntaxKind.IdentifierToken and SimpleParser.Current(self).Text == "var" and self._position + 1 < #self._tokens then
		if self._tokens[self._position + 1 + 1].Kind == SyntaxKind.IdentifierToken then
			return SimpleParser.ParseLocalDeclaration(self)
		end
	end
	local expr = SimpleParser.ParseExpression(self)
	SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
	return ExpressionStatementSyntax.new(expr)
end

function SimpleParser.IsTypeStart(self: SimpleParser, kind: number): boolean
	return kind == SyntaxKind.IntKeyword or kind == SyntaxKind.StringKeyword or kind == SyntaxKind.BoolKeyword or kind == SyntaxKind.VoidKeyword or kind == SyntaxKind.FloatKeyword or kind == SyntaxKind.DoubleKeyword or kind == SyntaxKind.LongKeyword or kind == SyntaxKind.CharKeyword or kind == SyntaxKind.ObjectKeyword or kind == SyntaxKind.IdentifierToken
end

function SimpleParser.ParseReturnStatement(self: SimpleParser): ReturnStatementSyntax
	SimpleParser.Advance(self)
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.SemicolonToken then
		SimpleParser.Advance(self)
		return ReturnStatementSyntax.new(nil)
	end
	local expr = SimpleParser.ParseExpression(self)
	SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
	return ReturnStatementSyntax.new(expr)
end

function SimpleParser.ParseIfStatement(self: SimpleParser): IfStatementSyntax
	SimpleParser.Advance(self)
	SimpleParser.Expect(self, SyntaxKind.OpenParenToken)
	local condition = SimpleParser.ParseExpression(self)
	SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
	local thenBody = SimpleParser.ParseStatementOrBlock(self)
	local elseBody = nil
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.ElseKeyword then
		SimpleParser.Advance(self)
		elseBody = SimpleParser.ParseStatementOrBlock(self)
	end
	return IfStatementSyntax.new(condition, thenBody, elseBody)
end

function SimpleParser.ParseWhileStatement(self: SimpleParser): WhileStatementSyntax
	SimpleParser.Advance(self)
	SimpleParser.Expect(self, SyntaxKind.OpenParenToken)
	local condition = SimpleParser.ParseExpression(self)
	SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
	local body = SimpleParser.ParseStatementOrBlock(self)
	return WhileStatementSyntax.new(condition, body)
end

function SimpleParser.ParseStatementOrBlock(self: SimpleParser): StatementSyntax
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.OpenBraceToken then
		return SimpleParser.ParseBlock(self)
	end
	return SimpleParser.ParseStatement(self)
end

function SimpleParser.ParseLocalDeclaration(self: SimpleParser): LocalDeclarationStatementSyntax
	local typeName = SimpleParser.ParseTypeName(self)
	local varName = SimpleParser.Current(self).Text
	SimpleParser.Advance(self)
	local initializer = nil
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.EqualsToken then
		SimpleParser.Advance(self)
		initializer = SimpleParser.ParseExpression(self)
	end
	SimpleParser.Expect(self, SyntaxKind.SemicolonToken)
	return LocalDeclarationStatementSyntax.new(typeName, varName, initializer)
end

function SimpleParser.ParseExpression(self: SimpleParser): ExpressionSyntax
	return SimpleParser.ParseAssignment(self)
end

function SimpleParser.ParseAssignment(self: SimpleParser): ExpressionSyntax
	local left = SimpleParser.ParseConditionalOr(self)
	if not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.EqualsToken then
		local op = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		local right = SimpleParser.ParseAssignment(self)
		return AssignmentExpressionSyntax.new(8714, left, op, right)
	end
	return left
end

function SimpleParser.ParseConditionalOr(self: SimpleParser): ExpressionSyntax
	local left = SimpleParser.ParseConditionalAnd(self)
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.BarBarToken do
		local op = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		local right = SimpleParser.ParseConditionalAnd(self)
		left = BinaryExpressionSyntax.new(8675, left, op, right)
	end
	return left
end

function SimpleParser.ParseConditionalAnd(self: SimpleParser): ExpressionSyntax
	local left = SimpleParser.ParseEquality(self)
	while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind == SyntaxKind.AmpersandAmpersandToken do
		local op = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		local right = SimpleParser.ParseEquality(self)
		left = BinaryExpressionSyntax.new(8676, left, op, right)
	end
	return left
end

function SimpleParser.ParseEquality(self: SimpleParser): ExpressionSyntax
	local left = SimpleParser.ParseRelational(self)
	while not SimpleParser.IsAtEnd(self) do
		local kind = SimpleParser.Current(self).Kind
		if kind == SyntaxKind.EqualsEqualsToken or kind == SyntaxKind.ExclamationEqualsToken then
			local op = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			local right = SimpleParser.ParseRelational(self)
			local exprKind = if kind == SyntaxKind.EqualsEqualsToken then 8682 else 8683
			left = BinaryExpressionSyntax.new(exprKind, left, op, right)
		else
			break
		end
	end
	return left
end

function SimpleParser.ParseRelational(self: SimpleParser): ExpressionSyntax
	local left = SimpleParser.ParseAdditive(self)
	while not SimpleParser.IsAtEnd(self) do
		local kind = SimpleParser.Current(self).Kind
		if kind == SyntaxKind.LessThanToken or kind == SyntaxKind.GreaterThanToken or kind == SyntaxKind.LessThanEqualsToken or kind == SyntaxKind.GreaterThanEqualsToken then
			local op = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			local right = SimpleParser.ParseAdditive(self)
			local exprKind = if kind == SyntaxKind.LessThanToken then 8678 else if kind == SyntaxKind.GreaterThanToken then 8680 else if kind == SyntaxKind.LessThanEqualsToken then 8679 else 8681
			left = BinaryExpressionSyntax.new(exprKind, left, op, right)
		else
			break
		end
	end
	return left
end

function SimpleParser.ParseAdditive(self: SimpleParser): ExpressionSyntax
	local left = SimpleParser.ParseMultiplicative(self)
	while not SimpleParser.IsAtEnd(self) do
		local kind = SimpleParser.Current(self).Kind
		if kind == SyntaxKind.PlusToken or kind == SyntaxKind.MinusToken then
			local op = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			local right = SimpleParser.ParseMultiplicative(self)
			local exprKind = if kind == SyntaxKind.PlusToken then 8668 else 8669
			left = BinaryExpressionSyntax.new(exprKind, left, op, right)
		else
			break
		end
	end
	return left
end

function SimpleParser.ParseMultiplicative(self: SimpleParser): ExpressionSyntax
	local left = SimpleParser.ParseUnary(self)
	while not SimpleParser.IsAtEnd(self) do
		local kind = SimpleParser.Current(self).Kind
		if kind == SyntaxKind.AsteriskToken or kind == SyntaxKind.SlashToken or kind == SyntaxKind.PercentToken then
			local op = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			local right = SimpleParser.ParseUnary(self)
			local exprKind = if kind == SyntaxKind.AsteriskToken then 8670 else if kind == SyntaxKind.SlashToken then 8671 else 8672
			left = BinaryExpressionSyntax.new(exprKind, left, op, right)
		else
			break
		end
	end
	return left
end

function SimpleParser.ParseUnary(self: SimpleParser): ExpressionSyntax
	if not SimpleParser.IsAtEnd(self) then
		local kind = SimpleParser.Current(self).Kind
		if kind == SyntaxKind.MinusToken or kind == SyntaxKind.ExclamationToken then
			local op = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			local operand = SimpleParser.ParseUnary(self)
			local exprKind = if kind == SyntaxKind.MinusToken then 8730 else 8731
			return PrefixUnaryExpressionSyntax.new(exprKind, op, operand)
		end
	end
	return SimpleParser.ParsePrimary(self)
end

function SimpleParser.ParsePrimary(self: SimpleParser): ExpressionSyntax
	local expr = SimpleParser.ParseAtom(self)
	while not SimpleParser.IsAtEnd(self) do
		if SimpleParser.Current(self).Kind == SyntaxKind.DotToken then
			SimpleParser.Advance(self)
			local name = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
			expr = MemberAccessExpressionSyntax.new(expr, name)
		elseif SimpleParser.Current(self).Kind == SyntaxKind.OpenParenToken then
			SimpleParser.Advance(self)
			local args = table.create(16)
			local argCount = 0
			while not SimpleParser.IsAtEnd(self) and SimpleParser.Current(self).Kind ~= SyntaxKind.CloseParenToken do
				if argCount > 0 then
					SimpleParser.Expect(self, SyntaxKind.CommaToken)
				end
				if argCount < 16 then
					args[argCount + 1] = SimpleParser.ParseExpression(self)
					argCount += 1
				end
			end
			SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
			local argResult = table.create(argCount)
			local i = 0
			while i < argCount do
				argResult[i + 1] = args[i + 1]
				i += 1
			end
			expr = InvocationExpressionSyntax.new(expr, argResult)
		else
			break
		end
	end
	return expr
end

function SimpleParser.ParseAtom(self: SimpleParser): ExpressionSyntax
	if SimpleParser.IsAtEnd(self) then
		return LiteralExpressionSyntax.new(8753, SyntaxToken.new(0, "", 0, 0))
	end
	local kind = SimpleParser.Current(self).Kind
	if kind == SyntaxKind.NumericLiteralToken then
		local token = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		return LiteralExpressionSyntax.new(8750, token)
	end
	if kind == SyntaxKind.StringLiteralToken then
		local token = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		return LiteralExpressionSyntax.new(8751, token)
	end
	if kind == SyntaxKind.CharacterLiteralToken then
		local token = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		return LiteralExpressionSyntax.new(8752, token)
	end
	if kind == SyntaxKind.TrueKeyword then
		local token = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		return LiteralExpressionSyntax.new(8748, token)
	end
	if kind == SyntaxKind.FalseKeyword then
		local token = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		return LiteralExpressionSyntax.new(8749, token)
	end
	if kind == SyntaxKind.NullKeyword then
		local token = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		return LiteralExpressionSyntax.new(8754, token)
	end
	if kind == SyntaxKind.OpenParenToken then
		SimpleParser.Advance(self)
		local inner = SimpleParser.ParseExpression(self)
		SimpleParser.Expect(self, SyntaxKind.CloseParenToken)
		return ParenthesizedExpressionSyntax.new(inner)
	end
	if kind == SyntaxKind.IdentifierToken then
		local token = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		return IdentifierNameSyntax.new(token)
	end
	if SimpleParser.IsTypeStart(self, kind) then
		local token = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
		return IdentifierNameSyntax.new(token)
	end
	local unknown = SimpleParser.MakeSyntaxToken(self, SimpleParser.Advance(self))
	return LiteralExpressionSyntax.new(8753, unknown)
end

return { SimpleParser = SimpleParser }
