--!strict
-- Auto-generated by LUSharpRoslynModule
-- Do not edit manually

local _SyntaxNode = require(script.Parent.SyntaxNode)
local StatementSyntax = _SyntaxNode.StatementSyntax

type BlockSyntax_self = {
	Statements: { StatementSyntax };
}

local BlockSyntax = setmetatable({}, {__index = StatementSyntax})
BlockSyntax.__index = BlockSyntax
export type BlockSyntax = typeof(setmetatable({} :: BlockSyntax_self, BlockSyntax))

function BlockSyntax.new(statements: { StatementSyntax }): BlockSyntax
	local self = setmetatable(StatementSyntax.new(8792) :: any, BlockSyntax)
	self.Statements = {}
	self.Statements = statements
	return self
end

function BlockSyntax.AcceptWalker(self: BlockSyntax, walker: SyntaxWalker): ()
	walker:VisitBlock(self)
end

function BlockSyntax.Accept(self: BlockSyntax): string
	local result = "{\n"
	local i = 0
	while i < #self.Statements do
		result = result .. "  " .. self.Statements[i + 1]:Accept() .. "\n"
		i += 1
	end
	result = result .. "}"
	return result
end

type ReturnStatementSyntax_self = {
	Expression: ExpressionSyntax;
}

local ReturnStatementSyntax = setmetatable({}, {__index = StatementSyntax})
ReturnStatementSyntax.__index = ReturnStatementSyntax
export type ReturnStatementSyntax = typeof(setmetatable({} :: ReturnStatementSyntax_self, ReturnStatementSyntax))

function ReturnStatementSyntax.new(expression: ExpressionSyntax): ReturnStatementSyntax
	local self = setmetatable(StatementSyntax.new(8805) :: any, ReturnStatementSyntax)
	self.Expression = nil :: any
	self.Expression = expression
	return self
end

function ReturnStatementSyntax.AcceptWalker(self: ReturnStatementSyntax, walker: SyntaxWalker): ()
	walker:VisitReturnStatement(self)
end

function ReturnStatementSyntax.Accept(self: ReturnStatementSyntax): string
	if self.Expression == nil then
		return "return;"
	end
	return "return " .. self.Expression:Accept() .. ";"
end

type ExpressionStatementSyntax_self = {
	Expression: ExpressionSyntax;
}

local ExpressionStatementSyntax = setmetatable({}, {__index = StatementSyntax})
ExpressionStatementSyntax.__index = ExpressionStatementSyntax
export type ExpressionStatementSyntax = typeof(setmetatable({} :: ExpressionStatementSyntax_self, ExpressionStatementSyntax))

function ExpressionStatementSyntax.new(expression: ExpressionSyntax): ExpressionStatementSyntax
	local self = setmetatable(StatementSyntax.new(8797) :: any, ExpressionStatementSyntax)
	self.Expression = nil :: any
	self.Expression = expression
	return self
end

function ExpressionStatementSyntax.AcceptWalker(self: ExpressionStatementSyntax, walker: SyntaxWalker): ()
	walker:VisitExpressionStatement(self)
end

function ExpressionStatementSyntax.Accept(self: ExpressionStatementSyntax): string
	return self.Expression:Accept() .. ";"
end

type LocalDeclarationStatementSyntax_self = {
	TypeName: string;
	VariableName: string;
	Initializer: ExpressionSyntax;
}

local LocalDeclarationStatementSyntax = setmetatable({}, {__index = StatementSyntax})
LocalDeclarationStatementSyntax.__index = LocalDeclarationStatementSyntax
export type LocalDeclarationStatementSyntax = typeof(setmetatable({} :: LocalDeclarationStatementSyntax_self, LocalDeclarationStatementSyntax))

function LocalDeclarationStatementSyntax.new(typeName: string, variableName: string, initializer: ExpressionSyntax): LocalDeclarationStatementSyntax
	local self = setmetatable(StatementSyntax.new(8793) :: any, LocalDeclarationStatementSyntax)
	self.TypeName = ""
	self.VariableName = ""
	self.Initializer = nil :: any
	self.TypeName = typeName
	self.VariableName = variableName
	self.Initializer = initializer
	return self
end

function LocalDeclarationStatementSyntax.AcceptWalker(self: LocalDeclarationStatementSyntax, walker: SyntaxWalker): ()
	walker:VisitLocalDeclaration(self)
end

function LocalDeclarationStatementSyntax.Accept(self: LocalDeclarationStatementSyntax): string
	if self.Initializer == nil then
		return self.TypeName .. " " .. self.VariableName .. ";"
	end
	return self.TypeName .. " " .. self.VariableName .. " = " .. self.Initializer:Accept() .. ";"
end

type IfStatementSyntax_self = {
	Condition: ExpressionSyntax;
	ThenBody: StatementSyntax;
	ElseBody: StatementSyntax;
}

local IfStatementSyntax = setmetatable({}, {__index = StatementSyntax})
IfStatementSyntax.__index = IfStatementSyntax
export type IfStatementSyntax = typeof(setmetatable({} :: IfStatementSyntax_self, IfStatementSyntax))

function IfStatementSyntax.new(condition: ExpressionSyntax, thenBody: StatementSyntax, elseBody: StatementSyntax): IfStatementSyntax
	local self = setmetatable(StatementSyntax.new(8803) :: any, IfStatementSyntax)
	self.Condition = nil :: any
	self.ThenBody = nil :: any
	self.ElseBody = nil :: any
	self.Condition = condition
	self.ThenBody = thenBody
	self.ElseBody = elseBody
	return self
end

function IfStatementSyntax.AcceptWalker(self: IfStatementSyntax, walker: SyntaxWalker): ()
	walker:VisitIfStatement(self)
end

function IfStatementSyntax.Accept(self: IfStatementSyntax): string
	local result = "if (" .. self.Condition:Accept() .. ") " .. self.ThenBody:Accept()
	if self.ElseBody ~= nil then
		result = result .. " else " .. self.ElseBody:Accept()
	end
	return result
end

type WhileStatementSyntax_self = {
	Condition: ExpressionSyntax;
	Body: StatementSyntax;
}

local WhileStatementSyntax = setmetatable({}, {__index = StatementSyntax})
WhileStatementSyntax.__index = WhileStatementSyntax
export type WhileStatementSyntax = typeof(setmetatable({} :: WhileStatementSyntax_self, WhileStatementSyntax))

function WhileStatementSyntax.new(condition: ExpressionSyntax, body: StatementSyntax): WhileStatementSyntax
	local self = setmetatable(StatementSyntax.new(8802) :: any, WhileStatementSyntax)
	self.Condition = nil :: any
	self.Body = nil :: any
	self.Condition = condition
	self.Body = body
	return self
end

function WhileStatementSyntax.AcceptWalker(self: WhileStatementSyntax, walker: SyntaxWalker): ()
	walker:VisitWhileStatement(self)
end

function WhileStatementSyntax.Accept(self: WhileStatementSyntax): string
	return "while (" .. self.Condition:Accept() .. ") " .. self.Body:Accept()
end

return { BlockSyntax = BlockSyntax, ReturnStatementSyntax = ReturnStatementSyntax, ExpressionStatementSyntax = ExpressionStatementSyntax, LocalDeclarationStatementSyntax = LocalDeclarationStatementSyntax, IfStatementSyntax = IfStatementSyntax, WhileStatementSyntax = WhileStatementSyntax }
