--!strict
-- Auto-generated by LUSharpRoslynModule
-- Do not edit manually

local _Microsoft = require(script.Parent.Microsoft)
local Microsoft = _Microsoft.Microsoft

type SyntaxWalker_self = {
	_depth: number;
}

local SyntaxWalker = {}
SyntaxWalker.__index = SyntaxWalker
export type SyntaxWalker = typeof(setmetatable({} :: SyntaxWalker_self, SyntaxWalker))

function SyntaxWalker.new(): SyntaxWalker
	local self = setmetatable({
		_depth = 0,
	} :: SyntaxWalker_self, SyntaxWalker)
	self._depth = 0
	return self
end

function SyntaxWalker.get_Depth(self: SyntaxWalker): number
	return self._depth
end

function SyntaxWalker.Visit(self: SyntaxWalker, node: SyntaxNode): ()
	if node == nil then
		return
	end
	node:AcceptWalker(self)
end

function SyntaxWalker.DefaultVisit(self: SyntaxWalker, node: SyntaxNode): ()
end

function SyntaxWalker.VisitCompilationUnit(self: SyntaxWalker, node: CompilationUnitSyntax): ()
	local i = 0
	while i < #node.Members do
		self._depth += 1
		SyntaxWalker.Visit(self, node.Members[i + 1])
		self._depth -= 1
		i += 1
	end
end

function SyntaxWalker.VisitClassDeclaration(self: SyntaxWalker, node: ClassDeclarationSyntax): ()
	local i = 0
	while i < #node.Members do
		self._depth += 1
		SyntaxWalker.Visit(self, node.Members[i + 1])
		self._depth -= 1
		i += 1
	end
end

function SyntaxWalker.VisitStructDeclaration(self: SyntaxWalker, node: StructDeclarationSyntax): ()
	local i = 0
	while i < #node.Members do
		self._depth += 1
		SyntaxWalker.Visit(self, node.Members[i + 1])
		self._depth -= 1
		i += 1
	end
end

function SyntaxWalker.VisitEnumDeclaration(self: SyntaxWalker, node: EnumDeclarationSyntax): ()
end

function SyntaxWalker.VisitMethodDeclaration(self: SyntaxWalker, node: MethodDeclarationSyntax): ()
	if node.Body ~= nil then
		self._depth += 1
		SyntaxWalker.Visit(self, node.Body)
		self._depth -= 1
	end
end

function SyntaxWalker.VisitConstructorDeclaration(self: SyntaxWalker, node: ConstructorDeclarationSyntax): ()
	if node.InitializerArguments ~= nil then
		local i = 0
		while i < #node.InitializerArguments do
			self._depth += 1
			SyntaxWalker.Visit(self, node.InitializerArguments[i + 1])
			self._depth -= 1
			i += 1
		end
	end
	if node.Body ~= nil then
		self._depth += 1
		SyntaxWalker.Visit(self, node.Body)
		self._depth -= 1
	end
end

function SyntaxWalker.VisitFieldDeclaration(self: SyntaxWalker, node: FieldDeclarationSyntax): ()
	if node.Initializer ~= nil then
		self._depth += 1
		SyntaxWalker.Visit(self, node.Initializer)
		self._depth -= 1
	end
end

function SyntaxWalker.VisitPropertyDeclaration(self: SyntaxWalker, node: PropertyDeclarationSyntax): ()
	if node.ExpressionBody ~= nil then
		self._depth += 1
		SyntaxWalker.Visit(self, node.ExpressionBody)
		self._depth -= 1
	end
end

function SyntaxWalker.VisitBlock(self: SyntaxWalker, node: BlockSyntax): ()
	local i = 0
	while i < #node.Statements do
		self._depth += 1
		SyntaxWalker.Visit(self, node.Statements[i + 1])
		self._depth -= 1
		i += 1
	end
end

function SyntaxWalker.VisitReturnStatement(self: SyntaxWalker, node: ReturnStatementSyntax): ()
	if node.Expression ~= nil then
		self._depth += 1
		SyntaxWalker.Visit(self, node.Expression)
		self._depth -= 1
	end
end

function SyntaxWalker.VisitIfStatement(self: SyntaxWalker, node: IfStatementSyntax): ()
	self._depth += 1
	SyntaxWalker.Visit(self, node.Condition)
	self._depth -= 1
	self._depth += 1
	SyntaxWalker.Visit(self, node.ThenBody)
	self._depth -= 1
	if node.ElseBody ~= nil then
		self._depth += 1
		SyntaxWalker.Visit(self, node.ElseBody)
		self._depth -= 1
	end
end

function SyntaxWalker.VisitWhileStatement(self: SyntaxWalker, node: WhileStatementSyntax): ()
	self._depth += 1
	SyntaxWalker.Visit(self, node.Condition)
	self._depth -= 1
	self._depth += 1
	SyntaxWalker.Visit(self, node.Body)
	self._depth -= 1
end

function SyntaxWalker.VisitExpressionStatement(self: SyntaxWalker, node: ExpressionStatementSyntax): ()
	self._depth += 1
	SyntaxWalker.Visit(self, node.Expression)
	self._depth -= 1
end

function SyntaxWalker.VisitLocalDeclaration(self: SyntaxWalker, node: LocalDeclarationStatementSyntax): ()
	if node.Initializer ~= nil then
		self._depth += 1
		SyntaxWalker.Visit(self, node.Initializer)
		self._depth -= 1
	end
end

function SyntaxWalker.VisitForStatement(self: SyntaxWalker, node: ForStatementSyntax): ()
	if node.Declaration ~= nil then
		self._depth += 1
		SyntaxWalker.Visit(self, node.Declaration)
		self._depth -= 1
	end
	if node.Condition ~= nil then
		self._depth += 1
		SyntaxWalker.Visit(self, node.Condition)
		self._depth -= 1
	end
	local i = 0
	while i < #node.Incrementors do
		self._depth += 1
		SyntaxWalker.Visit(self, node.Incrementors[i + 1])
		self._depth -= 1
		i += 1
	end
	self._depth += 1
	SyntaxWalker.Visit(self, node.Body)
	self._depth -= 1
end

function SyntaxWalker.VisitForEachStatement(self: SyntaxWalker, node: ForEachStatementSyntax): ()
	self._depth += 1
	SyntaxWalker.Visit(self, node.Expression)
	self._depth -= 1
	self._depth += 1
	SyntaxWalker.Visit(self, node.Body)
	self._depth -= 1
end

function SyntaxWalker.VisitDoStatement(self: SyntaxWalker, node: DoStatementSyntax): ()
	self._depth += 1
	SyntaxWalker.Visit(self, node.Body)
	self._depth -= 1
	self._depth += 1
	SyntaxWalker.Visit(self, node.Condition)
	self._depth -= 1
end

function SyntaxWalker.VisitBreakStatement(self: SyntaxWalker, node: BreakStatementSyntax): ()
	SyntaxWalker.DefaultVisit(self, node)
end

function SyntaxWalker.VisitContinueStatement(self: SyntaxWalker, node: ContinueStatementSyntax): ()
	SyntaxWalker.DefaultVisit(self, node)
end

function SyntaxWalker.VisitSwitchStatement(self: SyntaxWalker, node: SwitchStatementSyntax): ()
	self._depth += 1
	SyntaxWalker.Visit(self, node.Expression)
	self._depth -= 1
	local i = 0
	while i < #node.Sections do
		self._depth += 1
		SyntaxWalker.Visit(self, node.Sections[i + 1])
		self._depth -= 1
		i += 1
	end
end

function SyntaxWalker.VisitSwitchSection(self: SyntaxWalker, node: SwitchSectionSyntax): ()
	local i = 0
	while i < #node.Labels do
		if node.Labels[i + 1] ~= nil then
			self._depth += 1
			SyntaxWalker.Visit(self, node.Labels[i + 1])
			self._depth -= 1
		end
		i += 1
	end
	local i = 0
	while i < #node.Statements do
		self._depth += 1
		SyntaxWalker.Visit(self, node.Statements[i + 1])
		self._depth -= 1
		i += 1
	end
end

function SyntaxWalker.VisitTryStatement(self: SyntaxWalker, node: TryStatementSyntax): ()
	self._depth += 1
	SyntaxWalker.Visit(self, node.Block)
	self._depth -= 1
	local i = 0
	while i < #node.Catches do
		self._depth += 1
		SyntaxWalker.Visit(self, node.Catches[i + 1])
		self._depth -= 1
		i += 1
	end
	if node.FinallyBlock ~= nil then
		self._depth += 1
		SyntaxWalker.Visit(self, node.FinallyBlock)
		self._depth -= 1
	end
end

function SyntaxWalker.VisitCatchClause(self: SyntaxWalker, node: CatchClauseSyntax): ()
	self._depth += 1
	SyntaxWalker.Visit(self, node.Block)
	self._depth -= 1
end

function SyntaxWalker.VisitThrowStatement(self: SyntaxWalker, node: ThrowStatementSyntax): ()
	if node.Expression ~= nil then
		self._depth += 1
		SyntaxWalker.Visit(self, node.Expression)
		self._depth -= 1
	end
end

function SyntaxWalker.VisitLiteralExpression(self: SyntaxWalker, node: LiteralExpressionSyntax): ()
end

function SyntaxWalker.VisitIdentifierName(self: SyntaxWalker, node: IdentifierNameSyntax): ()
end

function SyntaxWalker.VisitBinaryExpression(self: SyntaxWalker, node: BinaryExpressionSyntax): ()
	self._depth += 1
	SyntaxWalker.Visit(self, node.Left)
	self._depth -= 1
	self._depth += 1
	SyntaxWalker.Visit(self, node.Right)
	self._depth -= 1
end

function SyntaxWalker.VisitPrefixUnaryExpression(self: SyntaxWalker, node: PrefixUnaryExpressionSyntax): ()
	self._depth += 1
	SyntaxWalker.Visit(self, node.Operand)
	self._depth -= 1
end

function SyntaxWalker.VisitParenthesizedExpression(self: SyntaxWalker, node: ParenthesizedExpressionSyntax): ()
	self._depth += 1
	SyntaxWalker.Visit(self, node.Expression)
	self._depth -= 1
end

function SyntaxWalker.VisitInvocationExpression(self: SyntaxWalker, node: InvocationExpressionSyntax): ()
	self._depth += 1
	SyntaxWalker.Visit(self, node.Expression)
	self._depth -= 1
	local i = 0
	while i < #node.Arguments do
		self._depth += 1
		SyntaxWalker.Visit(self, node.Arguments[i + 1])
		self._depth -= 1
		i += 1
	end
end

function SyntaxWalker.VisitMemberAccessExpression(self: SyntaxWalker, node: MemberAccessExpressionSyntax): ()
	self._depth += 1
	SyntaxWalker.Visit(self, node.Expression)
	self._depth -= 1
end

function SyntaxWalker.VisitAssignmentExpression(self: SyntaxWalker, node: AssignmentExpressionSyntax): ()
	self._depth += 1
	SyntaxWalker.Visit(self, node.Left)
	self._depth -= 1
	self._depth += 1
	SyntaxWalker.Visit(self, node.Right)
	self._depth -= 1
end

function SyntaxWalker.VisitObjectCreationExpression(self: SyntaxWalker, node: ObjectCreationExpressionSyntax): ()
	local i = 0
	while i < #node.Arguments do
		self._depth += 1
		SyntaxWalker.Visit(self, node.Arguments[i + 1])
		self._depth -= 1
		i += 1
	end
end

function SyntaxWalker.VisitArrayCreationExpression(self: SyntaxWalker, node: ArrayCreationExpressionSyntax): ()
	if node.SizeExpression ~= nil then
		self._depth += 1
		SyntaxWalker.Visit(self, node.SizeExpression)
		self._depth -= 1
	end
end

function SyntaxWalker.VisitLambdaExpression(self: SyntaxWalker, node: LambdaExpressionSyntax): ()
	if node.ExpressionBody ~= nil then
		self._depth += 1
		SyntaxWalker.Visit(self, node.ExpressionBody)
		self._depth -= 1
	end
	if node.BlockBody ~= nil then
		self._depth += 1
		SyntaxWalker.Visit(self, node.BlockBody)
		self._depth -= 1
	end
end

function SyntaxWalker.VisitCastExpression(self: SyntaxWalker, node: CastExpressionSyntax): ()
	self._depth += 1
	SyntaxWalker.Visit(self, node.Expression)
	self._depth -= 1
end

function SyntaxWalker.VisitElementAccess(self: SyntaxWalker, node: ElementAccessExpressionSyntax): ()
	self._depth += 1
	SyntaxWalker.Visit(self, node.Expression)
	self._depth -= 1
	self._depth += 1
	SyntaxWalker.Visit(self, node.Index)
	self._depth -= 1
end

function SyntaxWalker.VisitPostfixUnary(self: SyntaxWalker, node: PostfixUnaryExpressionSyntax): ()
	self._depth += 1
	SyntaxWalker.Visit(self, node.Operand)
	self._depth -= 1
end

function SyntaxWalker.VisitConditionalExpression(self: SyntaxWalker, node: ConditionalExpressionSyntax): ()
	self._depth += 1
	SyntaxWalker.Visit(self, node.Condition)
	self._depth -= 1
	self._depth += 1
	SyntaxWalker.Visit(self, node.WhenTrue)
	self._depth -= 1
	self._depth += 1
	SyntaxWalker.Visit(self, node.WhenFalse)
	self._depth -= 1
end

function SyntaxWalker.VisitSwitchExpression(self: SyntaxWalker, node: SwitchExpressionSyntax): ()
	self._depth += 1
	SyntaxWalker.Visit(self, node.GoverningExpression)
	self._depth -= 1
	local i = 0
	while i < #node.Arms do
		self._depth += 1
		node.Arms[i + 1]:AcceptWalker(self)
		self._depth -= 1
		i += 1
	end
end

function SyntaxWalker.VisitSwitchExpressionArm(self: SyntaxWalker, node: SwitchExpressionArmSyntax): ()
	if node.Pattern ~= nil then
		self._depth += 1
		SyntaxWalker.Visit(self, node.Pattern)
		self._depth -= 1
	end
	self._depth += 1
	SyntaxWalker.Visit(self, node.Expression)
	self._depth -= 1
end

type TreePrinter_self = {
	_output: string;
}

local TreePrinter = setmetatable({}, {__index = SyntaxWalker})
TreePrinter.__index = TreePrinter
export type TreePrinter = typeof(setmetatable({} :: TreePrinter_self, TreePrinter))

function TreePrinter.new(): TreePrinter
	local self = setmetatable(SyntaxWalker.new() :: any, TreePrinter)
	self._output = ""
	self._output = ""
	return self
end

function TreePrinter.GetOutput(self: TreePrinter): string
	return self._output
end

function TreePrinter.PrintNode(self: TreePrinter, text: string): ()
	local i = 0
	while i < self._depth do
		self._output = self._output .. "  "
		i += 1
	end
	self._output = self._output .. text .. "\n"
end

function TreePrinter.VisitCompilationUnit(self: TreePrinter, node: CompilationUnitSyntax): ()
	TreePrinter.PrintNode(self, "CompilationUnit")
	SyntaxWalker.VisitCompilationUnit(self, node)
end

function TreePrinter.VisitClassDeclaration(self: TreePrinter, node: ClassDeclarationSyntax): ()
	TreePrinter.PrintNode(self, "ClassDeclaration: " .. node.Name)
	SyntaxWalker.VisitClassDeclaration(self, node)
end

function TreePrinter.VisitStructDeclaration(self: TreePrinter, node: StructDeclarationSyntax): ()
	TreePrinter.PrintNode(self, "StructDeclaration: " .. node.Name)
	SyntaxWalker.VisitStructDeclaration(self, node)
end

function TreePrinter.VisitEnumDeclaration(self: TreePrinter, node: EnumDeclarationSyntax): ()
	TreePrinter.PrintNode(self, "EnumDeclaration: " .. node.Name .. " (" .. #node.Members .. " members)")
	SyntaxWalker.VisitEnumDeclaration(self, node)
end

function TreePrinter.VisitMethodDeclaration(self: TreePrinter, node: MethodDeclarationSyntax): ()
	local mods = ""
	if node.IsStatic then
		mods = "static "
	end
	TreePrinter.PrintNode(self, "MethodDeclaration: " .. mods .. node.ReturnType .. " " .. node.Name)
	SyntaxWalker.VisitMethodDeclaration(self, node)
end

function TreePrinter.VisitConstructorDeclaration(self: TreePrinter, node: ConstructorDeclarationSyntax): ()
	TreePrinter.PrintNode(self, "ConstructorDeclaration: " .. node.Name)
	SyntaxWalker.VisitConstructorDeclaration(self, node)
end

function TreePrinter.VisitFieldDeclaration(self: TreePrinter, node: FieldDeclarationSyntax): ()
	local mods = ""
	if node.IsStatic then
		mods = "static "
	end
	TreePrinter.PrintNode(self, "FieldDeclaration: " .. mods .. node.TypeName .. " " .. node.Name)
	SyntaxWalker.VisitFieldDeclaration(self, node)
end

function TreePrinter.VisitPropertyDeclaration(self: TreePrinter, node: PropertyDeclarationSyntax): ()
	local accessors = ""
	if node.HasGetter then
		accessors = accessors .. "get"
	end
	if node.HasSetter then
		if #accessors > 0 then
			accessors = accessors .. ","
		end
		accessors = accessors .. "set"
	end
	TreePrinter.PrintNode(self, "PropertyDeclaration: " .. node.TypeName .. " " .. node.Name .. " {" .. accessors .. "}")
	SyntaxWalker.VisitPropertyDeclaration(self, node)
end

function TreePrinter.VisitBlock(self: TreePrinter, node: BlockSyntax): ()
	TreePrinter.PrintNode(self, "Block (" .. #node.Statements .. " statements)")
	SyntaxWalker.VisitBlock(self, node)
end

function TreePrinter.VisitReturnStatement(self: TreePrinter, node: ReturnStatementSyntax): ()
	TreePrinter.PrintNode(self, "ReturnStatement")
	SyntaxWalker.VisitReturnStatement(self, node)
end

function TreePrinter.VisitIfStatement(self: TreePrinter, node: IfStatementSyntax): ()
	local hasElse = ""
	if node.ElseBody ~= nil then
		hasElse = " +else"
	end
	TreePrinter.PrintNode(self, "IfStatement" .. hasElse)
	SyntaxWalker.VisitIfStatement(self, node)
end

function TreePrinter.VisitWhileStatement(self: TreePrinter, node: WhileStatementSyntax): ()
	TreePrinter.PrintNode(self, "WhileStatement")
	SyntaxWalker.VisitWhileStatement(self, node)
end

function TreePrinter.VisitExpressionStatement(self: TreePrinter, node: ExpressionStatementSyntax): ()
	TreePrinter.PrintNode(self, "ExpressionStatement")
	SyntaxWalker.VisitExpressionStatement(self, node)
end

function TreePrinter.VisitLocalDeclaration(self: TreePrinter, node: LocalDeclarationStatementSyntax): ()
	TreePrinter.PrintNode(self, "LocalDeclaration: " .. node.TypeName .. " " .. node.VariableName)
	SyntaxWalker.VisitLocalDeclaration(self, node)
end

function TreePrinter.VisitForStatement(self: TreePrinter, node: ForStatementSyntax): ()
	TreePrinter.PrintNode(self, "ForStatement")
	SyntaxWalker.VisitForStatement(self, node)
end

function TreePrinter.VisitForEachStatement(self: TreePrinter, node: ForEachStatementSyntax): ()
	TreePrinter.PrintNode(self, "ForEachStatement: " .. node.TypeName .. " " .. node.Identifier)
	SyntaxWalker.VisitForEachStatement(self, node)
end

function TreePrinter.VisitDoStatement(self: TreePrinter, node: DoStatementSyntax): ()
	TreePrinter.PrintNode(self, "DoStatement")
	SyntaxWalker.VisitDoStatement(self, node)
end

function TreePrinter.VisitBreakStatement(self: TreePrinter, node: BreakStatementSyntax): ()
	TreePrinter.PrintNode(self, "BreakStatement")
	SyntaxWalker.VisitBreakStatement(self, node)
end

function TreePrinter.VisitContinueStatement(self: TreePrinter, node: ContinueStatementSyntax): ()
	TreePrinter.PrintNode(self, "ContinueStatement")
	SyntaxWalker.VisitContinueStatement(self, node)
end

function TreePrinter.VisitSwitchStatement(self: TreePrinter, node: SwitchStatementSyntax): ()
	TreePrinter.PrintNode(self, "SwitchStatement")
	SyntaxWalker.VisitSwitchStatement(self, node)
end

function TreePrinter.VisitSwitchSection(self: TreePrinter, node: SwitchSectionSyntax): ()
	local caseCount = 0
	local hasDefault = false
	local i = 0
	while i < #node.Labels do
		if node.Labels[i + 1] == nil then
			hasDefault = true
		else
			caseCount += 1
		end
		i += 1
	end
	local desc = caseCount .. " case(s)"
	if hasDefault then
		desc = desc .. " +default"
	end
	TreePrinter.PrintNode(self, "SwitchSection: " .. desc)
	SyntaxWalker.VisitSwitchSection(self, node)
end

function TreePrinter.VisitTryStatement(self: TreePrinter, node: TryStatementSyntax): ()
	local desc = "TryStatement"
	if #node.Catches > 0 then
		desc = desc .. " (" .. #node.Catches .. " catch)"
	end
	if node.FinallyBlock ~= nil then
		desc = desc .. " +finally"
	end
	TreePrinter.PrintNode(self, desc)
	SyntaxWalker.VisitTryStatement(self, node)
end

function TreePrinter.VisitCatchClause(self: TreePrinter, node: CatchClauseSyntax): ()
	local desc = "CatchClause"
	if node.ExceptionTypeName ~= nil then
		desc = desc .. ": " .. node.ExceptionTypeName
		if node.Identifier ~= nil then
			desc = desc .. " " .. node.Identifier
		end
	end
	TreePrinter.PrintNode(self, desc)
	SyntaxWalker.VisitCatchClause(self, node)
end

function TreePrinter.VisitThrowStatement(self: TreePrinter, node: ThrowStatementSyntax): ()
	local rethrow = if node.Expression == nil then " (re-throw)" else ""
	TreePrinter.PrintNode(self, "ThrowStatement" .. rethrow)
	SyntaxWalker.VisitThrowStatement(self, node)
end

function TreePrinter.VisitLiteralExpression(self: TreePrinter, node: LiteralExpressionSyntax): ()
	TreePrinter.PrintNode(self, "Literal: " .. node.Token.Text)
end

function TreePrinter.VisitIdentifierName(self: TreePrinter, node: IdentifierNameSyntax): ()
	TreePrinter.PrintNode(self, "Identifier: " .. node.Identifier.Text)
end

function TreePrinter.VisitBinaryExpression(self: TreePrinter, node: BinaryExpressionSyntax): ()
	TreePrinter.PrintNode(self, "BinaryExpression: " .. node.OperatorToken.Text)
	SyntaxWalker.VisitBinaryExpression(self, node)
end

function TreePrinter.VisitPrefixUnaryExpression(self: TreePrinter, node: PrefixUnaryExpressionSyntax): ()
	TreePrinter.PrintNode(self, "PrefixUnary: " .. node.OperatorToken.Text)
	SyntaxWalker.VisitPrefixUnaryExpression(self, node)
end

function TreePrinter.VisitParenthesizedExpression(self: TreePrinter, node: ParenthesizedExpressionSyntax): ()
	TreePrinter.PrintNode(self, "ParenthesizedExpression")
	SyntaxWalker.VisitParenthesizedExpression(self, node)
end

function TreePrinter.VisitInvocationExpression(self: TreePrinter, node: InvocationExpressionSyntax): ()
	TreePrinter.PrintNode(self, "InvocationExpression")
	SyntaxWalker.VisitInvocationExpression(self, node)
end

function TreePrinter.VisitMemberAccessExpression(self: TreePrinter, node: MemberAccessExpressionSyntax): ()
	TreePrinter.PrintNode(self, "MemberAccess: ." .. node.Name.Text)
	SyntaxWalker.VisitMemberAccessExpression(self, node)
end

function TreePrinter.VisitAssignmentExpression(self: TreePrinter, node: AssignmentExpressionSyntax): ()
	TreePrinter.PrintNode(self, "Assignment: " .. node.OperatorToken.Text)
	SyntaxWalker.VisitAssignmentExpression(self, node)
end

function TreePrinter.VisitObjectCreationExpression(self: TreePrinter, node: ObjectCreationExpressionSyntax): ()
	TreePrinter.PrintNode(self, "ObjectCreation: " .. node.TypeName)
	SyntaxWalker.VisitObjectCreationExpression(self, node)
end

function TreePrinter.VisitArrayCreationExpression(self: TreePrinter, node: ArrayCreationExpressionSyntax): ()
	TreePrinter.PrintNode(self, "ArrayCreation: " .. node.TypeName)
	SyntaxWalker.VisitArrayCreationExpression(self, node)
end

function TreePrinter.VisitLambdaExpression(self: TreePrinter, node: LambdaExpressionSyntax): ()
	TreePrinter.PrintNode(self, "Lambda (" .. #node.ParameterNames .. " params)")
	SyntaxWalker.VisitLambdaExpression(self, node)
end

function TreePrinter.VisitCastExpression(self: TreePrinter, node: CastExpressionSyntax): ()
	TreePrinter.PrintNode(self, "Cast: " .. node.TypeName)
	SyntaxWalker.VisitCastExpression(self, node)
end

function TreePrinter.VisitElementAccess(self: TreePrinter, node: ElementAccessExpressionSyntax): ()
	TreePrinter.PrintNode(self, "ElementAccess")
	SyntaxWalker.VisitElementAccess(self, node)
end

function TreePrinter.VisitPostfixUnary(self: TreePrinter, node: PostfixUnaryExpressionSyntax): ()
	local opText = if node.OperatorKind == Microsoft.CodeAnalysis.CSharp.SyntaxKind.PlusPlusToken then "++" else "--"
	TreePrinter.PrintNode(self, "PostfixUnary: " .. opText)
	SyntaxWalker.VisitPostfixUnary(self, node)
end

function TreePrinter.VisitConditionalExpression(self: TreePrinter, node: ConditionalExpressionSyntax): ()
	TreePrinter.PrintNode(self, "ConditionalExpression")
	SyntaxWalker.VisitConditionalExpression(self, node)
end

function TreePrinter.VisitSwitchExpression(self: TreePrinter, node: SwitchExpressionSyntax): ()
	TreePrinter.PrintNode(self, "SwitchExpression (" .. #node.Arms .. " arms)")
	SyntaxWalker.VisitSwitchExpression(self, node)
end

function TreePrinter.VisitSwitchExpressionArm(self: TreePrinter, node: SwitchExpressionArmSyntax): ()
	local label = if node.Pattern ~= nil then "case" else "default"
	TreePrinter.PrintNode(self, "SwitchArm: " .. label)
	SyntaxWalker.VisitSwitchExpressionArm(self, node)
end

return { SyntaxWalker = SyntaxWalker, TreePrinter = TreePrinter }
