--!strict
-- Auto-generated by LUSharpRoslynModule
-- Do not edit manually

local StringHelper = {}
StringHelper.__index = StringHelper
export type StringHelper = typeof(setmetatable({}, StringHelper))

function StringHelper.EndsWith(self: StringHelper, text: string, ch: number): boolean
	local last = string.byte(text, #text - 1 + 1)
	return last == ch
end

return { StringHelper = StringHelper }
