using LUSharpTranspiler.AST.SourceConstructor.Builders;
using LUSharpTranspiler.Transform.IR;
using LUSharpTranspiler.Transform.IR.Expressions;
using LUSharpTranspiler.Transform.IR.Statements;

namespace LUSharpTranspiler.Backend;

public static class ModuleEmitter
{
    public static string Emit(LuaModule module)
    {
        var w = new LuaWriter();

        w.WriteLine("-- Generated by LUSharp");
        w.WriteLine();

        // Requires
        foreach (var req in module.Requires)
            w.WriteLine($"local {req.LocalName} = {req.RequirePath}");

        if (module.Requires.Count > 0) w.WriteLine();

        // Classes
        foreach (var cls in module.Classes)
            EmitClass(cls, w);

        // Entry body (Main class only)
        foreach (var stmt in module.EntryBody)
            StatementEmitter.Emit(stmt, w);

        // Module return
        if (module.ScriptType == ScriptType.ModuleScript && module.Classes.Count > 0)
            w.WriteLine($"return {module.Classes[0].Name}");

        return w.ToString();
    }

    private static void EmitClass(LuaClassDef cls, LuaWriter w)
    {
        w.WriteLine($"local {cls.Name} = {{}}");
        w.WriteLine();

        // Static fields
        foreach (var f in cls.StaticFields)
        {
            w.WriteInline($"{cls.Name}.{f.Name} = ");
            if (f.Value != null) ExprEmitter.Emit(f.Value, w);
            else w.WriteInline("nil");
            w.WriteLine();
        }

        if (cls.StaticFields.Count > 0) w.WriteLine();

        // Constructor
        if (cls.Constructor != null)
            EmitMethod(cls.Name, cls.Constructor, w);

        // Methods
        foreach (var method in cls.Methods)
            EmitMethod(cls.Name, method, w);

        // Custom events (_events table)
        if (cls.Events.Count > 0)
        {
            w.WriteLine($"{cls.Name}._events = {{}}");
            foreach (var ev in cls.Events)
                w.WriteLine($"{cls.Name}._events.{ev.Name} = Instance.new(\"BindableEvent\")");
            w.WriteLine();
        }
    }

    private static void EmitMethod(string className, LuaMethodDef method, LuaWriter w)
    {
        var sep = method.IsStatic ? "." : ":";
        var parms = method.IsStatic
            ? method.Parameters
            : method.Parameters.Skip(1).ToList(); // skip 'self' — colon syntax adds it

        w.WriteLine($"function {className}{sep}{method.Name}({string.Join(", ", parms)})");
        w.IndentMore();
        foreach (var stmt in method.Body)
            StatementEmitter.Emit(stmt, w);
        w.IndentLess();
        w.WriteLine("end");
        w.WriteLine();
    }
}
