namespace RoslynLuau;

/// <summary>
/// Walks a SimpleParser AST and emits --!strict Luau source code.
/// Extends SyntaxWalker for declaration/statement dispatch via AcceptWalker,
/// but uses a direct EmitExpression method with kind-based dispatch for expressions
/// (since expressions need to return strings, and Visit methods return void).
///
/// Self-hosting constraints: This file is transpiled to Luau by LuauEmitter.cs.
/// No LINQ, no string interpolation, no var, no is/as patterns, no ?. or ??,
/// no switch expressions. String output via plain string + concatenation.
/// </summary>
public class SimpleEmitter : SyntaxWalker
{
    private string _output;
    private int _indent;
    private string _currentClassName;
    private string _baseClassName;
    private bool _isStaticContext;

    // Collected instance fields for the current class (name, luauType, defaultExpr)
    private string[] _fieldNames;
    private string[] _fieldTypes;
    private string[] _fieldDefaults;
    private int _fieldCount;

    // Collected static fields for the current class (name, luauType, initExpr)
    private string[] _staticFieldNames;
    private string[] _staticFieldTypes;
    private string[] _staticFieldDefaults;
    private int _staticFieldCount;

    // Tracks whether the current class has any instance members
    private bool _hasInstanceMembers;

    // All type names declared in the compilation unit (for module return)
    private string[] _typeNames;
    private int _typeCount;

    // Parameter names and types for the current method (used for colon-call and string indexing detection)
    private string[] _paramNames;
    private string[] _paramTypes;
    private int _paramCount;

    // Local variable names and types for the current method
    private string[] _localNames;
    private string[] _localTypes;
    private int _localCount;

    // Method names for the current class (used for bare instance method dispatch)
    private string[] _methodNames;
    private bool[] _isMethodStatic;
    private int _methodCount;

    public SimpleEmitter()
    {
        _output = "";
        _indent = 0;
        _currentClassName = "";
        _baseClassName = null;
        _isStaticContext = false;
        _fieldNames = new string[64];
        _fieldTypes = new string[64];
        _fieldDefaults = new string[64];
        _fieldCount = 0;
        _staticFieldNames = new string[64];
        _staticFieldTypes = new string[64];
        _staticFieldDefaults = new string[64];
        _staticFieldCount = 0;
        _hasInstanceMembers = false;
        _typeNames = new string[32];
        _typeCount = 0;
        _paramNames = new string[32];
        _paramTypes = new string[32];
        _paramCount = 0;
        _localNames = new string[64];
        _localTypes = new string[64];
        _localCount = 0;
        _methodNames = new string[128];
        _isMethodStatic = new bool[128];
        _methodCount = 0;
    }

    public string GetOutput()
    {
        return _output;
    }

    /// <summary>
    /// Top-level entry point. Emits the full Luau module from a CompilationUnitSyntax.
    /// </summary>
    public string Emit(CompilationUnitSyntax unit)
    {
        AppendLine("--!strict");
        AppendLine("-- Auto-generated by SimpleEmitter");
        AppendLine("");

        // First pass: collect type names for the return statement
        _typeCount = 0;
        for (int i = 0; i < unit.Members.Length; i++)
        {
            int kind = unit.Members[i].Kind;
            if (kind == 8855) // ClassDeclaration
            {
                ClassDeclarationSyntax cls = (ClassDeclarationSyntax)unit.Members[i];
                _typeNames[_typeCount] = cls.Name;
                _typeCount++;
            }
            else if (kind == 8857) // StructDeclaration
            {
                StructDeclarationSyntax str = (StructDeclarationSyntax)unit.Members[i];
                _typeNames[_typeCount] = str.Name;
                _typeCount++;
            }
            else if (kind == 8856) // EnumDeclaration
            {
                EnumDeclarationSyntax enm = (EnumDeclarationSyntax)unit.Members[i];
                _typeNames[_typeCount] = enm.Name;
                _typeCount++;
            }
        }

        // Second pass: emit each top-level member
        for (int i = 0; i < unit.Members.Length; i++)
        {
            unit.Members[i].AcceptWalker(this);
        }

        // Emit module return table
        if (_typeCount > 0)
        {
            AppendLine("");
            string ret = "return { ";
            for (int i = 0; i < _typeCount; i++)
            {
                if (i > 0) ret = ret + ", ";
                ret = ret + _typeNames[i] + " = " + _typeNames[i];
            }
            ret = ret + " }";
            AppendLine(ret);
        }

        return GetOutput();
    }

    // ────────────────────────────────────────────────────────
    //  Output helpers
    // ────────────────────────────────────────────────────────

    private void AppendLine(string text)
    {
        for (int i = 0; i < _indent; i++)
        {
            _output = _output + "\t";
        }
        _output = _output + text + "\n";
    }

    private void Indent()
    {
        _indent++;
    }

    private void Dedent()
    {
        _indent--;
    }

    // ────────────────────────────────────────────────────────
    //  Type mapping: C# type name → Luau type annotation
    // ────────────────────────────────────────────────────────

    private string MapType(string csharpType)
    {
        if (csharpType == null) return "any";
        if (csharpType == "void") return "()";
        if (csharpType == "string") return "string";
        if (csharpType == "bool") return "boolean";
        if (csharpType == "int") return "number";
        if (csharpType == "float") return "number";
        if (csharpType == "double") return "number";
        if (csharpType == "long") return "number";
        if (csharpType == "short") return "number";
        if (csharpType == "byte") return "number";
        if (csharpType == "sbyte") return "number";
        if (csharpType == "ushort") return "number";
        if (csharpType == "uint") return "number";
        if (csharpType == "ulong") return "number";
        if (csharpType == "decimal") return "number";
        if (csharpType == "char") return "number";
        if (csharpType == "object") return "any";
        if (csharpType == "var") return "any";
        if (csharpType == "StringBuilder") return "string";

        // Nullable T? → T?
        if (csharpType.Length > 1 && csharpType[csharpType.Length - 1] == '?')
        {
            string inner = csharpType.Substring(0, csharpType.Length - 1);
            return MapType(inner) + "?";
        }

        // T[] → { T }
        if (csharpType.Length > 2
            && csharpType[csharpType.Length - 1] == ']'
            && csharpType[csharpType.Length - 2] == '[')
        {
            string inner = csharpType.Substring(0, csharpType.Length - 2);
            return "{ " + MapType(inner) + " }";
        }

        // List<T> → { T }
        if (csharpType.Length > 5
            && csharpType.Substring(0, 5) == "List<"
            && csharpType[csharpType.Length - 1] == '>')
        {
            string inner = csharpType.Substring(5, csharpType.Length - 6);
            return "{ " + MapType(inner) + " }";
        }

        // Dictionary<K,V> → { [K]: V }
        if (csharpType.Length > 11
            && csharpType.Substring(0, 11) == "Dictionary<"
            && csharpType[csharpType.Length - 1] == '>')
        {
            string inner = csharpType.Substring(11, csharpType.Length - 12);
            int comma = inner.IndexOf(',');
            if (comma >= 0)
            {
                string keyType = MapType(inner.Substring(0, comma).Trim());
                string valType = MapType(inner.Substring(comma + 1).Trim());
                return "{ [" + keyType + "]: " + valType + " }";
            }
        }

        // HashSet<T> → { [T]: boolean }
        if (csharpType.Length > 8
            && csharpType.Substring(0, 8) == "HashSet<"
            && csharpType[csharpType.Length - 1] == '>')
        {
            string inner = csharpType.Substring(8, csharpType.Length - 9);
            return "{ [" + MapType(inner) + "]: boolean }";
        }

        // Unknown: pass through as-is (user-defined class/struct name)
        return csharpType;
    }

    private string DefaultForType(string csharpType)
    {
        if (csharpType == null) return "nil";
        if (csharpType == "string") return "\"\"";
        if (csharpType == "bool") return "false";
        if (csharpType == "StringBuilder") return "\"\"";
        if (csharpType == "int" || csharpType == "float" || csharpType == "double"
            || csharpType == "long" || csharpType == "short" || csharpType == "byte"
            || csharpType == "sbyte" || csharpType == "ushort" || csharpType == "uint"
            || csharpType == "ulong" || csharpType == "decimal" || csharpType == "char")
        {
            return "0";
        }

        // Collection types → empty table
        if (csharpType.Length > 2
            && csharpType[csharpType.Length - 1] == ']'
            && csharpType[csharpType.Length - 2] == '[')
        {
            return "{}";
        }
        if (csharpType.Length > 5 && csharpType.Substring(0, 5) == "List<") return "{}";
        if (csharpType.Length > 11 && csharpType.Substring(0, 11) == "Dictionary<") return "{}";
        if (csharpType.Length > 8 && csharpType.Substring(0, 8) == "HashSet<") return "{}";

        return "nil :: any";
    }

    // ────────────────────────────────────────────────────────
    //  Declaration visitors
    // ────────────────────────────────────────────────────────

    public override void VisitClassDeclaration(ClassDeclarationSyntax node)
    {
        EmitClassOrStruct(node.Name, node.BaseTypeName, node.Members, false);
    }

    public override void VisitStructDeclaration(StructDeclarationSyntax node)
    {
        EmitClassOrStruct(node.Name, node.BaseTypeName, node.Members, true);
    }

    private void EmitClassOrStruct(string name, string baseTypeName, MemberDeclarationSyntax[] members, bool isStruct)
    {
        string savedClassName = _currentClassName;
        string savedBaseClassName = _baseClassName;
        _currentClassName = name;
        _baseClassName = baseTypeName;

        // Reset field and method collectors for this type
        _fieldCount = 0;
        _staticFieldCount = 0;
        _methodCount = 0;
        _hasInstanceMembers = false;

        // First pass: collect fields and auto-properties for the type_self block
        for (int i = 0; i < members.Length; i++)
        {
            int kind = members[i].Kind;
            if (kind == 8873) // FieldDeclaration
            {
                FieldDeclarationSyntax field = (FieldDeclarationSyntax)members[i];
                if (field.IsStatic)
                {
                    _staticFieldNames[_staticFieldCount] = field.Name;
                    _staticFieldTypes[_staticFieldCount] = field.TypeName;
                    if (field.Initializer != null)
                    {
                        _staticFieldDefaults[_staticFieldCount] = EmitExpression(field.Initializer);
                    }
                    else
                    {
                        _staticFieldDefaults[_staticFieldCount] = null;
                    }
                    _staticFieldCount++;
                }
                else
                {
                    _fieldNames[_fieldCount] = field.Name;
                    _fieldTypes[_fieldCount] = field.TypeName;
                    if (field.Initializer != null)
                    {
                        _fieldDefaults[_fieldCount] = EmitExpression(field.Initializer);
                    }
                    else
                    {
                        _fieldDefaults[_fieldCount] = null;
                    }
                    _fieldCount++;
                    _hasInstanceMembers = true;
                }
            }
            else if (kind == 8892) // PropertyDeclaration
            {
                PropertyDeclarationSyntax prop = (PropertyDeclarationSyntax)members[i];
                if (!prop.IsStatic && prop.HasGetter && prop.ExpressionBody == null)
                {
                    // Auto-property with getter: treat as instance field
                    _fieldNames[_fieldCount] = prop.Name;
                    _fieldTypes[_fieldCount] = prop.TypeName;
                    _fieldDefaults[_fieldCount] = null;
                    _fieldCount++;
                    _hasInstanceMembers = true;
                }
                else if (prop.IsStatic)
                {
                    _staticFieldNames[_staticFieldCount] = prop.Name;
                    _staticFieldTypes[_staticFieldCount] = prop.TypeName;
                    _staticFieldDefaults[_staticFieldCount] = null;
                    _staticFieldCount++;
                }
            }
            else if (kind == 8875) // MethodDeclaration
            {
                MethodDeclarationSyntax method = (MethodDeclarationSyntax)members[i];
                if (!method.IsStatic) _hasInstanceMembers = true;
                // Track method name for bare-call dispatch
                if (_methodCount < 128)
                {
                    _methodNames[_methodCount] = method.Name;
                    _isMethodStatic[_methodCount] = method.IsStatic;
                    _methodCount++;
                }
            }
            else if (kind == 8878) // ConstructorDeclaration
            {
                _hasInstanceMembers = true;
            }
        }

        // A class is all-static when it has no instance members and no instance fields
        bool isAllStatic = !_hasInstanceMembers && _fieldCount == 0;

        // Emit type alias for the self table (instance types only)
        if (!isAllStatic && _fieldCount > 0)
        {
            AppendLine("type " + name + "_self = {");
            Indent();
            for (int i = 0; i < _fieldCount; i++)
            {
                AppendLine(_fieldNames[i] + ": " + MapType(_fieldTypes[i]) + ";");
            }
            Dedent();
            AppendLine("}");
            AppendLine("");
        }

        // Emit the table and __index
        if (baseTypeName != null)
        {
            AppendLine("local " + name + " = setmetatable({}, {__index = " + baseTypeName + "})");
        }
        else
        {
            AppendLine("local " + name + " = {}");
        }
        if (!isAllStatic)
        {
            AppendLine(name + ".__index = " + name);
            AppendLine("export type " + name + " = typeof(setmetatable({} :: " + name + "_self, " + name + "))");
        }
        AppendLine("");

        // Emit static fields
        for (int i = 0; i < _staticFieldCount; i++)
        {
            string val = _staticFieldDefaults[i];
            if (val != null)
            {
                AppendLine(name + "." + _staticFieldNames[i] + " = " + val);
            }
            else
            {
                AppendLine(name + "." + _staticFieldNames[i] + " = " + DefaultForType(_staticFieldTypes[i]));
            }
        }
        if (_staticFieldCount > 0) AppendLine("");

        // Emit explicit constructors
        bool hasCtor = false;
        for (int i = 0; i < members.Length; i++)
        {
            if (members[i].Kind == 8878) // ConstructorDeclaration
            {
                ConstructorDeclarationSyntax ctor = (ConstructorDeclarationSyntax)members[i];
                EmitConstructor(name, ctor);
                AppendLine("");
                hasCtor = true;
            }
        }

        // If no constructor, emit a default .new() for instance types
        if (!hasCtor && !isAllStatic)
        {
            EmitDefaultConstructor(name);
            AppendLine("");
        }

        // Emit methods
        for (int i = 0; i < members.Length; i++)
        {
            if (members[i].Kind == 8875) // MethodDeclaration
            {
                MethodDeclarationSyntax method = (MethodDeclarationSyntax)members[i];
                EmitMethod(name, method, isAllStatic);
                AppendLine("");
            }
        }

        // Emit expression-bodied properties as get_ accessor methods
        for (int i = 0; i < members.Length; i++)
        {
            if (members[i].Kind == 8892) // PropertyDeclaration
            {
                PropertyDeclarationSyntax prop = (PropertyDeclarationSyntax)members[i];
                if (prop.ExpressionBody != null)
                {
                    EmitExpressionProperty(name, prop, isAllStatic);
                    AppendLine("");
                }
            }
        }

        _currentClassName = savedClassName;
        _baseClassName = savedBaseClassName;
    }

    private void EmitDefaultConstructor(string className)
    {
        AppendLine("function " + className + ".new(): " + className);
        Indent();

        if (_baseClassName != null)
        {
            // Inheritance: call parent constructor, re-set metatable to child
            AppendLine("local self = setmetatable(" + _baseClassName + ".new() :: any, " + className + ")");
            // Set child-specific field defaults
            for (int i = 0; i < _fieldCount; i++)
            {
                string val = _fieldDefaults[i];
                if (val == null) val = DefaultForType(_fieldTypes[i]);
                AppendLine("self." + _fieldNames[i] + " = " + val);
            }
        }
        else if (_fieldCount > 0)
        {
            AppendLine("local self = setmetatable({");
            Indent();
            for (int i = 0; i < _fieldCount; i++)
            {
                string val = _fieldDefaults[i];
                if (val == null) val = DefaultForType(_fieldTypes[i]);
                AppendLine(_fieldNames[i] + " = " + val + ",");
            }
            Dedent();
            AppendLine("} :: " + className + "_self, " + className + ")");
        }
        else
        {
            AppendLine("local self = setmetatable({} :: " + className + "_self, " + className + ")");
        }

        AppendLine("return self");
        Dedent();
        AppendLine("end");
    }

    private void EmitConstructor(string className, ConstructorDeclarationSyntax ctor)
    {
        string parms = "";
        for (int i = 0; i < ctor.Parameters.Length; i++)
        {
            if (i > 0) parms = parms + ", ";
            parms = parms + ctor.Parameters[i].Name + ": " + MapType(ctor.Parameters[i].TypeName);
        }

        AppendLine("function " + className + ".new(" + parms + "): " + className);
        Indent();

        // Save and set up parameter/local tracking for constructor scope
        int savedParamCount = _paramCount;
        int savedLocalCount = _localCount;
        _paramCount = 0;
        _localCount = 0;
        for (int i = 0; i < ctor.Parameters.Length; i++)
        {
            _paramNames[_paramCount] = ctor.Parameters[i].Name;
            _paramTypes[_paramCount] = ctor.Parameters[i].TypeName;
            _paramCount = _paramCount + 1;
        }

        if (_baseClassName != null && ctor.BaseOrThisKeyword == "base")
        {
            // Inheritance with explicit base(args): call parent constructor
            string baseArgs = "";
            if (ctor.InitializerArguments != null)
            {
                for (int i = 0; i < ctor.InitializerArguments.Length; i++)
                {
                    if (i > 0) baseArgs = baseArgs + ", ";
                    baseArgs = baseArgs + EmitExpression(ctor.InitializerArguments[i]);
                }
            }
            AppendLine("local self = setmetatable(" + _baseClassName + ".new(" + baseArgs + ") :: any, " + className + ")");

            // Set child-specific field defaults
            for (int i = 0; i < _fieldCount; i++)
            {
                string val = _fieldDefaults[i];
                if (val == null) val = DefaultForType(_fieldTypes[i]);
                AppendLine("self." + _fieldNames[i] + " = " + val);
            }
        }
        else if (_baseClassName != null)
        {
            // Inheritance without explicit base call: call parameterless parent constructor
            AppendLine("local self = setmetatable(" + _baseClassName + ".new() :: any, " + className + ")");

            // Set child-specific field defaults
            for (int i = 0; i < _fieldCount; i++)
            {
                string val = _fieldDefaults[i];
                if (val == null) val = DefaultForType(_fieldTypes[i]);
                AppendLine("self." + _fieldNames[i] + " = " + val);
            }
        }
        else if (_fieldCount > 0)
        {
            // No inheritance: standard setmetatable with field table
            AppendLine("local self = setmetatable({");
            Indent();
            for (int i = 0; i < _fieldCount; i++)
            {
                string val = _fieldDefaults[i];
                if (val == null) val = DefaultForType(_fieldTypes[i]);
                AppendLine(_fieldNames[i] + " = " + val + ",");
            }
            Dedent();
            AppendLine("} :: " + className + "_self, " + className + ")");
        }
        else
        {
            AppendLine("local self = setmetatable({} :: " + className + "_self, " + className + ")");
        }

        // Emit constructor body
        if (ctor.Body != null)
        {
            bool savedStatic = _isStaticContext;
            _isStaticContext = false;
            EmitStatements(ctor.Body.Statements);
            _isStaticContext = savedStatic;
        }

        AppendLine("return self");
        _paramCount = savedParamCount;
        _localCount = savedLocalCount;
        Dedent();
        AppendLine("end");
    }

    private void EmitMethod(string className, MethodDeclarationSyntax method, bool isAllStatic)
    {
        string retType = MapType(method.ReturnType);

        // Build parameter list, prepending self for instance methods
        string parms = "";
        if (!method.IsStatic && !isAllStatic)
        {
            parms = "self: " + className;
        }
        for (int i = 0; i < method.Parameters.Length; i++)
        {
            if (parms.Length > 0) parms = parms + ", ";
            parms = parms + method.Parameters[i].Name + ": " + MapType(method.Parameters[i].TypeName);
        }

        AppendLine("function " + className + "." + method.Name + "(" + parms + "): " + retType);
        Indent();

        // Save and set up parameter/local tracking for this method scope
        int savedParamCount = _paramCount;
        int savedLocalCount = _localCount;
        _paramCount = 0;
        _localCount = 0;
        for (int i = 0; i < method.Parameters.Length; i++)
        {
            _paramNames[_paramCount] = method.Parameters[i].Name;
            _paramTypes[_paramCount] = method.Parameters[i].TypeName;
            _paramCount = _paramCount + 1;
        }

        bool savedStatic = _isStaticContext;
        _isStaticContext = method.IsStatic || isAllStatic;

        if (method.Body != null)
        {
            EmitStatements(method.Body.Statements);
        }

        _isStaticContext = savedStatic;
        _paramCount = savedParamCount;
        _localCount = savedLocalCount;
        Dedent();
        AppendLine("end");
    }

    private void EmitExpressionProperty(string className, PropertyDeclarationSyntax prop, bool isAllStatic)
    {
        string retType = MapType(prop.TypeName);
        string parms = "";
        if (!prop.IsStatic && !isAllStatic)
        {
            parms = "self: " + className;
        }

        AppendLine("function " + className + ".get_" + prop.Name + "(" + parms + "): " + retType);
        Indent();

        bool savedStatic = _isStaticContext;
        _isStaticContext = prop.IsStatic || isAllStatic;

        string expr = EmitExpression(prop.ExpressionBody);
        AppendLine("return " + expr);

        _isStaticContext = savedStatic;
        Dedent();
        AppendLine("end");
    }

    public override void VisitEnumDeclaration(EnumDeclarationSyntax node)
    {
        string name = node.Name;

        // Determine if this is a numeric enum (any member has an explicit value)
        bool isNumeric = false;
        for (int i = 0; i < node.Members.Length; i++)
        {
            if (node.Members[i].Value != null)
            {
                isNumeric = true;
            }
        }

        AppendLine("local " + name + " = table.freeze({");
        Indent();

        int autoValue = 0;
        for (int i = 0; i < node.Members.Length; i++)
        {
            string memberName = node.Members[i].Name;
            if (node.Members[i].Value != null)
            {
                string val = EmitExpression(node.Members[i].Value);
                AppendLine(memberName + " = " + val + ",");
            }
            else if (isNumeric)
            {
                AppendLine(memberName + " = " + IntToString(autoValue) + ",");
                autoValue++;
            }
            else
            {
                // String-valued enum: member name is its own value
                AppendLine(memberName + " = \"" + memberName + "\",");
            }
        }

        Dedent();
        AppendLine("})");

        if (isNumeric)
        {
            AppendLine("export type " + name + " = number");
        }
        else
        {
            AppendLine("export type " + name + " = keyof<typeof(" + name + ")>");
        }
        AppendLine("");
    }

    // ────────────────────────────────────────────────────────
    //  Statement emission
    // ────────────────────────────────────────────────────────

    private void EmitStatements(StatementSyntax[] stmts)
    {
        for (int i = 0; i < stmts.Length; i++)
        {
            EmitStatement(stmts[i]);
        }
    }

    private void EmitStatement(StatementSyntax stmt)
    {
        if (stmt == null) return;
        int kind = stmt.Kind;

        if (kind == 8792) // Block
        {
            BlockSyntax block = (BlockSyntax)stmt;
            EmitStatements(block.Statements);
            return;
        }

        if (kind == 8805) // ReturnStatement
        {
            ReturnStatementSyntax ret = (ReturnStatementSyntax)stmt;
            if (ret.Expression == null)
            {
                AppendLine("return");
            }
            else
            {
                AppendLine("return " + EmitExpression(ret.Expression));
            }
            return;
        }

        if (kind == 8797) // ExpressionStatement
        {
            ExpressionStatementSyntax exprStmt = (ExpressionStatementSyntax)stmt;
            string exprText = EmitExpressionStatement(exprStmt.Expression);
            AppendLine(exprText);
            return;
        }

        if (kind == 8793) // LocalDeclaration
        {
            LocalDeclarationStatementSyntax local = (LocalDeclarationStatementSyntax)stmt;
            string luauType = MapType(local.TypeName);

            // Track local variable for colon-call and string indexing detection
            if (_localCount < 64)
            {
                _localNames[_localCount] = local.VariableName;
                _localTypes[_localCount] = local.TypeName;
                _localCount = _localCount + 1;
            }

            if (local.Initializer != null)
            {
                string init = EmitExpression(local.Initializer);
                AppendLine("local " + local.VariableName + ": " + luauType + " = " + init);
            }
            else
            {
                AppendLine("local " + local.VariableName + ": " + luauType + " = " + DefaultForType(local.TypeName));
            }
            return;
        }

        if (kind == 8802) // WhileStatement
        {
            WhileStatementSyntax ws = (WhileStatementSyntax)stmt;
            AppendLine("while " + EmitExpression(ws.Condition) + " do");
            Indent();
            EmitBlockBody(ws.Body);
            Dedent();
            AppendLine("end");
            return;
        }

        if (kind == 8811) // ForStatement
        {
            ForStatementSyntax fs = (ForStatementSyntax)stmt;
            EmitForStatement(fs);
            return;
        }

        if (kind == 8812) // ForEachStatement
        {
            ForEachStatementSyntax fes = (ForEachStatementSyntax)stmt;
            // Track foreach variable for colon-call and string indexing detection
            if (_localCount < 64)
            {
                _localNames[_localCount] = fes.Identifier;
                _localTypes[_localCount] = fes.TypeName;
                _localCount = _localCount + 1;
            }
            AppendLine("for _, " + fes.Identifier + " in " + EmitExpression(fes.Expression) + " do");
            Indent();
            EmitBlockBody(fes.Body);
            Dedent();
            AppendLine("end");
            return;
        }

        if (kind == 8810) // DoStatement
        {
            DoStatementSyntax ds = (DoStatementSyntax)stmt;
            AppendLine("repeat");
            Indent();
            EmitBlockBody(ds.Body);
            Dedent();
            AppendLine("until not (" + EmitExpression(ds.Condition) + ")");
            return;
        }

        if (kind == 8821) // SwitchStatement
        {
            SwitchStatementSyntax ss = (SwitchStatementSyntax)stmt;
            EmitSwitchStatement(ss);
            return;
        }

        if (kind == 8825) // TryStatement
        {
            TryStatementSyntax ts = (TryStatementSyntax)stmt;
            EmitTryStatement(ts);
            return;
        }

        if (kind == 8808) // ThrowStatement
        {
            ThrowStatementSyntax thr = (ThrowStatementSyntax)stmt;
            if (thr.Expression != null)
            {
                // throw new ExceptionType(msg) → error(msg)
                if (thr.Expression.Kind == 8649) // ObjectCreation
                {
                    ObjectCreationExpressionSyntax obj = (ObjectCreationExpressionSyntax)thr.Expression;
                    if (obj.Arguments.Length > 0)
                    {
                        AppendLine("error(" + EmitExpression(obj.Arguments[0]) + ")");
                    }
                    else
                    {
                        AppendLine("error(\"" + obj.TypeName + "\")");
                    }
                }
                else
                {
                    AppendLine("error(" + EmitExpression(thr.Expression) + ")");
                }
            }
            else
            {
                AppendLine("error(\"re-throw\")");
            }
            return;
        }

        // All remaining statements (IfStatement, BreakStatement, ContinueStatement)
        // are handled via double-dispatch through AcceptWalker.
        stmt.AcceptWalker(this);
    }

    public override void VisitIfStatement(IfStatementSyntax node)
    {
        AppendLine("if " + EmitExpression(node.Condition) + " then");
        Indent();
        EmitBlockBody(node.ThenBody);
        Dedent();

        if (node.ElseBody != null)
        {
            // Emit else-if chain without nested end keywords
            EmitElseBody(node.ElseBody);
        }
        else
        {
            AppendLine("end");
        }
    }

    private void EmitElseBody(StatementSyntax elseBody)
    {
        if (elseBody == null)
        {
            AppendLine("end");
            return;
        }

        // Plain else block
        if (elseBody.Kind == 8792) // Block
        {
            AppendLine("else");
            Indent();
            BlockSyntax block = (BlockSyntax)elseBody;
            EmitStatements(block.Statements);
            Dedent();
            AppendLine("end");
            return;
        }

        // else-if chain: IfStatement (kind 8819)
        if (elseBody.Kind == 8819)
        {
            IfStatementSyntax elseIf = (IfStatementSyntax)elseBody;
            AppendLine("elseif " + EmitExpression(elseIf.Condition) + " then");
            Indent();
            EmitBlockBody(elseIf.ThenBody);
            Dedent();

            if (elseIf.ElseBody != null)
            {
                EmitElseBody(elseIf.ElseBody);
            }
            else
            {
                AppendLine("end");
            }
            return;
        }

        // Fallback: bare statement in else position (shouldn't happen in well-formed code)
        AppendLine("else");
        Indent();
        EmitStatement(elseBody);
        Dedent();
        AppendLine("end");
    }

    public override void VisitBreakStatement(BreakStatementSyntax node)
    {
        AppendLine("break");
    }

    public override void VisitContinueStatement(ContinueStatementSyntax node)
    {
        AppendLine("continue");
    }

    private void EmitBlockBody(StatementSyntax body)
    {
        if (body == null) return;
        if (body.Kind == 8792) // Block
        {
            BlockSyntax block = (BlockSyntax)body;
            EmitStatements(block.Statements);
        }
        else
        {
            EmitStatement(body);
        }
    }

    private void EmitForStatement(ForStatementSyntax fs)
    {
        // Detect simple numeric for: for (int i = start; i < end; i++)
        // and emit as Luau numeric for: for i = start, end - 1 do
        bool isSimpleNumericFor = false;
        string varName = "";
        string startVal = "";
        string endExpr = "";

        if (fs.Declaration != null && fs.Declaration.Kind == 8793
            && fs.Condition != null && fs.Incrementors.Length == 1)
        {
            LocalDeclarationStatementSyntax decl = (LocalDeclarationStatementSyntax)fs.Declaration;
            varName = decl.VariableName;
            if (decl.Initializer != null)
            {
                startVal = EmitExpression(decl.Initializer);
            }

            int condKind = fs.Condition.Kind;
            if (condKind >= 8668 && condKind <= 8688)
            {
                BinaryExpressionSyntax cond = (BinaryExpressionSyntax)fs.Condition;
                ExpressionSyntax inc = fs.Incrementors[0];

                bool incIsPlus = false;
                if (inc.Kind == 8738 || inc.Kind == 8739) // PostfixUnary
                {
                    PostfixUnaryExpressionSyntax post = (PostfixUnaryExpressionSyntax)inc;
                    if (post.OperatorKind == (Microsoft.CodeAnalysis.CSharp.SyntaxKind)8440)
                    {
                        incIsPlus = true;
                    }
                }
                else if (inc.Kind == 8734) // PreIncrement
                {
                    incIsPlus = true;
                }

                if (incIsPlus)
                {
                    if (cond.OperatorToken.Text == "<")
                    {
                        endExpr = EmitExpression(cond.Right) + " - 1";
                        isSimpleNumericFor = true;
                    }
                    else if (cond.OperatorToken.Text == "<=")
                    {
                        endExpr = EmitExpression(cond.Right);
                        isSimpleNumericFor = true;
                    }
                }
            }
        }

        if (isSimpleNumericFor)
        {
            AppendLine("for " + varName + " = " + startVal + ", " + endExpr + " do");
            Indent();
            EmitBlockBody(fs.Body);
            Dedent();
            AppendLine("end");
        }
        else
        {
            // General case: lower to while loop
            if (fs.Declaration != null)
            {
                EmitStatement(fs.Declaration);
            }
            string condText = "true";
            if (fs.Condition != null)
            {
                condText = EmitExpression(fs.Condition);
            }
            AppendLine("while " + condText + " do");
            Indent();
            EmitBlockBody(fs.Body);
            for (int i = 0; i < fs.Incrementors.Length; i++)
            {
                AppendLine(EmitExpressionStatement(fs.Incrementors[i]));
            }
            Dedent();
            AppendLine("end");
        }
    }

    private void EmitSwitchStatement(SwitchStatementSyntax ss)
    {
        string switchExpr = EmitExpression(ss.Expression);
        string switchVar = "__switch_val";
        AppendLine("local " + switchVar + " = " + switchExpr);

        bool isFirst = true;
        for (int i = 0; i < ss.Sections.Length; i++)
        {
            SwitchSectionSyntax section = ss.Sections[i];
            bool isDefault = false;
            string caseCondition = "";

            for (int j = 0; j < section.Labels.Length; j++)
            {
                if (section.Labels[j] == null)
                {
                    isDefault = true;
                }
                else
                {
                    string labelExpr = EmitExpression(section.Labels[j]);
                    if (caseCondition.Length > 0)
                    {
                        caseCondition = caseCondition + " or ";
                    }
                    caseCondition = caseCondition + switchVar + " == " + labelExpr;
                }
            }

            if (isDefault && caseCondition.Length == 0)
            {
                if (isFirst)
                {
                    AppendLine("do");
                }
                else
                {
                    AppendLine("else");
                }
            }
            else if (isFirst)
            {
                AppendLine("if " + caseCondition + " then");
            }
            else
            {
                AppendLine("elseif " + caseCondition + " then");
            }

            Indent();
            for (int j = 0; j < section.Statements.Length; j++)
            {
                // Skip the trailing break that C# switch sections require
                if (section.Statements[j].Accept() == "break;")
                {
                    continue;
                }
                EmitStatement(section.Statements[j]);
            }
            Dedent();
            isFirst = false;
        }

        AppendLine("end");
    }

    private void EmitTryStatement(TryStatementSyntax ts)
    {
        // Determine the error variable name from the first catch clause
        string errVar = "__err";
        if (ts.Catches.Length > 0 && ts.Catches[0].Identifier != null)
        {
            errVar = ts.Catches[0].Identifier;
        }

        AppendLine("local __ok, " + errVar + " = pcall(function()");
        Indent();
        if (ts.Block != null)
        {
            EmitStatements(ts.Block.Statements);
        }
        Dedent();
        AppendLine("end)");

        if (ts.Catches.Length > 0)
        {
            AppendLine("if not __ok then");
            Indent();
            EmitStatements(ts.Catches[0].Block.Statements);
            Dedent();
            AppendLine("end");
        }

        // finally always executes — emit inline after the pcall block
        if (ts.FinallyBlock != null)
        {
            EmitStatements(ts.FinallyBlock.Statements);
        }
    }

    // ────────────────────────────────────────────────────────
    //  Expression emission (kind-based dispatch with casts)
    // ────────────────────────────────────────────────────────

    /// <summary>
    /// Emit an expression that appears as a statement (assignment, increment, call).
    /// Postfix/prefix ++ and -- are emitted as compound assignments here.
    /// </summary>
    private string EmitExpressionStatement(ExpressionSyntax expr)
    {
        if (expr == null) return "";
        int kind = expr.Kind;

        // Simple assignment
        if (kind == 8714)
        {
            AssignmentExpressionSyntax assign = (AssignmentExpressionSyntax)expr;
            return EmitExpression(assign.Left) + " = " + EmitExpression(assign.Right);
        }

        // Compound assignments
        if (kind == 8715)
        {
            AssignmentExpressionSyntax assign = (AssignmentExpressionSyntax)expr;
            return EmitExpression(assign.Left) + " += " + EmitExpression(assign.Right);
        }
        if (kind == 8716)
        {
            AssignmentExpressionSyntax assign = (AssignmentExpressionSyntax)expr;
            return EmitExpression(assign.Left) + " -= " + EmitExpression(assign.Right);
        }
        if (kind == 8717)
        {
            AssignmentExpressionSyntax assign = (AssignmentExpressionSyntax)expr;
            return EmitExpression(assign.Left) + " *= " + EmitExpression(assign.Right);
        }
        if (kind == 8718)
        {
            AssignmentExpressionSyntax assign = (AssignmentExpressionSyntax)expr;
            return EmitExpression(assign.Left) + " /= " + EmitExpression(assign.Right);
        }
        if (kind == 8719)
        {
            AssignmentExpressionSyntax assign = (AssignmentExpressionSyntax)expr;
            return EmitExpression(assign.Left) + " %= " + EmitExpression(assign.Right);
        }

        // Postfix ++/--
        if (kind == 8738)
        {
            PostfixUnaryExpressionSyntax post = (PostfixUnaryExpressionSyntax)expr;
            return EmitExpression(post.Operand) + " += 1";
        }
        if (kind == 8739)
        {
            PostfixUnaryExpressionSyntax post = (PostfixUnaryExpressionSyntax)expr;
            return EmitExpression(post.Operand) + " -= 1";
        }

        // Prefix ++/--
        if (kind == 8734)
        {
            PrefixUnaryExpressionSyntax pre = (PrefixUnaryExpressionSyntax)expr;
            return EmitExpression(pre.Operand) + " += 1";
        }
        if (kind == 8735)
        {
            PrefixUnaryExpressionSyntax pre = (PrefixUnaryExpressionSyntax)expr;
            return EmitExpression(pre.Operand) + " -= 1";
        }

        // Default: emit as a plain expression (e.g. a function call)
        return EmitExpression(expr);
    }

    private string EmitExpression(ExpressionSyntax expr)
    {
        if (expr == null) return "nil";
        int kind = expr.Kind;

        // ── Literals ──────────────────────────────────────────
        if (kind == 8748) return "true";   // TrueLiteralExpression
        if (kind == 8749) return "false";  // FalseLiteralExpression
        if (kind == 8754) return "nil";    // NullLiteralExpression
        if (kind == 8753) return "nil";    // DefaultLiteralExpression

        if (kind == 8750) // NumericLiteralExpression
        {
            LiteralExpressionSyntax lit = (LiteralExpressionSyntax)expr;
            string text = lit.Token.Text;
            // Strip C# numeric type suffixes (f, d, m, L, u, etc.)
            if (text.Length > 0)
            {
                char last = text[text.Length - 1];
                if (last == 'f' || last == 'F'
                    || last == 'd' || last == 'D'
                    || last == 'm' || last == 'M'
                    || last == 'L' || last == 'l'
                    || last == 'u' || last == 'U')
                {
                    text = text.Substring(0, text.Length - 1);
                }
            }
            return text;
        }

        if (kind == 8751) // StringLiteralExpression
        {
            LiteralExpressionSyntax lit = (LiteralExpressionSyntax)expr;
            return lit.Token.Text;
        }

        if (kind == 8752) // CharacterLiteralExpression
        {
            LiteralExpressionSyntax lit = (LiteralExpressionSyntax)expr;
            string charText = lit.Token.Text;
            // Convert 'x' to string.byte("x", 1) numeric value
            if (charText.Length >= 3 && charText[0] == '\'' && charText[charText.Length - 1] == '\'')
            {
                string inner = charText.Substring(1, charText.Length - 2);
                if (inner == "\\n") return "10";
                if (inner == "\\r") return "13";
                if (inner == "\\t") return "9";
                if (inner == "\\\\") return "92";
                if (inner == "\\'") return "39";
                if (inner == "\\\"") return "34";
                if (inner == "\\0") return "0";
                if (inner.Length == 1)
                {
                    return "string.byte(\"" + inner + "\", 1)";
                }
            }
            return "string.byte(" + charText + ", 1)";
        }

        // ── Identifier ────────────────────────────────────────
        if (kind == 8616) // IdentifierName
        {
            IdentifierNameSyntax ident = (IdentifierNameSyntax)expr;
            string name = ident.Identifier.Text;

            if (name == "null") return "nil";
            if (name == "true") return "true";
            if (name == "false") return "false";
            if (name == "this") return "self";

            // Instance field: prefix with self. when in instance context
            if (!_isStaticContext && _currentClassName.Length > 0)
            {
                for (int i = 0; i < _fieldCount; i++)
                {
                    if (_fieldNames[i] == name)
                    {
                        return "self." + name;
                    }
                }
            }

            return name;
        }

        // ── Parenthesized ─────────────────────────────────────
        if (kind == 8632)
        {
            ParenthesizedExpressionSyntax paren = (ParenthesizedExpressionSyntax)expr;
            return "(" + EmitExpression(paren.Expression) + ")";
        }

        // ── Binary ────────────────────────────────────────────
        if (kind >= 8668 && kind <= 8688)
        {
            return EmitBinary(expr);
        }

        // ── is / as ───────────────────────────────────────────
        if (kind == 8657) // IsExpression
        {
            BinaryExpressionSyntax bin = (BinaryExpressionSyntax)expr;
            return "true --[[is " + EmitExpression(bin.Right) + "]]";
        }
        if (kind == 8658) // AsExpression
        {
            BinaryExpressionSyntax bin = (BinaryExpressionSyntax)expr;
            return EmitExpression(bin.Left);
        }

        // ── Prefix unary ──────────────────────────────────────
        if (kind == 8730 || kind == 8731 || kind == 8733) // UnaryPlus, UnaryMinus, LogicalNot
        {
            PrefixUnaryExpressionSyntax pre = (PrefixUnaryExpressionSyntax)expr;
            string opText = pre.OperatorToken.Text;
            if (opText == "!") return "not " + EmitExpression(pre.Operand);
            if (opText == "-") return "-" + EmitExpression(pre.Operand);
            return opText + EmitExpression(pre.Operand);
        }
        if (kind == 8734) // PreIncrement (in expression context)
        {
            PrefixUnaryExpressionSyntax pre = (PrefixUnaryExpressionSyntax)expr;
            return EmitExpression(pre.Operand) + " + 1";
        }
        if (kind == 8735) // PreDecrement (in expression context)
        {
            PrefixUnaryExpressionSyntax pre = (PrefixUnaryExpressionSyntax)expr;
            return EmitExpression(pre.Operand) + " - 1";
        }

        // ── Postfix ───────────────────────────────────────────
        if (kind == 8738 || kind == 8739) // PostIncrement, PostDecrement (in expression context)
        {
            PostfixUnaryExpressionSyntax post = (PostfixUnaryExpressionSyntax)expr;
            // Return the original value (side-effect is separate)
            return EmitExpression(post.Operand);
        }

        // ── Assignment ────────────────────────────────────────
        if (kind >= 8714 && kind <= 8726)
        {
            return EmitAssignment(expr);
        }

        // ── Member access ─────────────────────────────────────
        if (kind == 8689)
        {
            return EmitMemberAccess(expr);
        }

        // ── Invocation ────────────────────────────────────────
        if (kind == 8634)
        {
            return EmitInvocation(expr);
        }

        // ── Object creation ───────────────────────────────────
        if (kind == 8649)
        {
            return EmitObjectCreation(expr);
        }

        // ── Element access ────────────────────────────────────
        if (kind == 8635)
        {
            return EmitElementAccess(expr);
        }

        // ── Cast ──────────────────────────────────────────────
        if (kind == 8640)
        {
            CastExpressionSyntax cast = (CastExpressionSyntax)expr;
            // Casts are no-ops in Luau (dynamic typing)
            return EmitExpression(cast.Expression);
        }

        // ── Lambda ────────────────────────────────────────────
        if (kind == 8643)
        {
            return EmitLambda(expr);
        }

        // ── Conditional (ternary) ─────────────────────────────
        if (kind == 8633)
        {
            ConditionalExpressionSyntax cond = (ConditionalExpressionSyntax)expr;
            return "if " + EmitExpression(cond.Condition)
                + " then " + EmitExpression(cond.WhenTrue)
                + " else " + EmitExpression(cond.WhenFalse);
        }

        // ── Switch expression ─────────────────────────────────
        if (kind == 9023)
        {
            return EmitSwitchExpression(expr);
        }

        // ── Unknown ───────────────────────────────────────────
        return "nil --[[unknown expr kind " + IntToString(kind) + "]]";
    }

    // ── Binary expression ────────────────────────────────────
    private string EmitBinary(ExpressionSyntax expr)
    {
        BinaryExpressionSyntax bin = (BinaryExpressionSyntax)expr;
        string left = EmitExpression(bin.Left);
        string right = EmitExpression(bin.Right);
        string op = bin.OperatorToken.Text;

        // C# → Luau operator mappings
        if (op == "!=") return left + " ~= " + right;
        if (op == "&&") return left + " and " + right;
        if (op == "||") return left + " or " + right;
        if (op == "??")
        {
            // Null coalescing: a ?? b → if a ~= nil then a else b
            return "if " + left + " ~= nil then " + left + " else " + right;
        }

        // String concatenation: + where any operand in the chain is a string literal
        // or a known string-typed variable
        if (op == "+")
        {
            bool isStringConcat = false;
            if (bin.Left.Kind == 8751) isStringConcat = true;
            if (bin.Right.Kind == 8751) isStringConcat = true;
            // Check if the already-emitted left/right contain ".." (propagated from sub-expr)
            if (ContainsConcatOp(left)) isStringConcat = true;
            if (ContainsConcatOp(right)) isStringConcat = true;
            // Propagate through left-hand + chains: check if any operand is a string literal
            if (bin.Left.Kind >= 8668 && bin.Left.Kind <= 8688)
            {
                if (HasStringLiteralInChain(bin.Left))
                {
                    isStringConcat = true;
                }
            }
            // Propagate through right-hand + chains
            if (bin.Right.Kind >= 8668 && bin.Right.Kind <= 8688)
            {
                if (HasStringLiteralInChain(bin.Right))
                {
                    isStringConcat = true;
                }
            }
            // Type-aware: check if either operand is a known string-typed variable
            if (!isStringConcat && HasStringTypedOperand(bin.Left)) isStringConcat = true;
            if (!isStringConcat && HasStringTypedOperand(bin.Right)) isStringConcat = true;
            if (isStringConcat)
            {
                // Wrap char-typed operands with string.char() for correct concat
                string lVal = WrapCharForConcat(bin.Left, left);
                string rVal = WrapCharForConcat(bin.Right, right);
                return lVal + " .. " + rVal;
            }
        }

        // Integer division: int / int → // in Luau (floor division)
        if (op == "/")
        {
            if (IsIntegerExpression(bin.Left) && IsIntegerExpression(bin.Right))
            {
                return left + " // " + right;
            }
        }

        // Bitwise operators
        if (op == "&") return "bit32.band(" + left + ", " + right + ")";
        if (op == "|") return "bit32.bor(" + left + ", " + right + ")";
        if (op == "^") return "bit32.bxor(" + left + ", " + right + ")";
        if (op == "<<") return "bit32.lshift(" + left + ", " + right + ")";
        if (op == ">>") return "bit32.rshift(" + left + ", " + right + ")";

        // All other operators pass through unchanged: ==, <, >, <=, >=, +, -, *, /, %
        return left + " " + op + " " + right;
    }

    /// <summary>
    /// Recursively check if any node in a binary + chain contains a string literal.
    /// </summary>
    private bool HasStringLiteralInChain(ExpressionSyntax expr)
    {
        if (expr.Kind == 8751) return true; // StringLiteral
        if (expr.Kind >= 8668 && expr.Kind <= 8688)
        {
            BinaryExpressionSyntax bin = (BinaryExpressionSyntax)expr;
            if (bin.OperatorToken.Text == "+")
            {
                if (HasStringLiteralInChain(bin.Left)) return true;
                if (HasStringLiteralInChain(bin.Right)) return true;
            }
        }
        return false;
    }

    /// <summary>
    /// Check if an already-emitted string contains " .. " (indicating a prior concat was detected).
    /// </summary>
    private bool ContainsConcatOp(string emitted)
    {
        int idx = 0;
        while (idx <= emitted.Length - 4)
        {
            if (emitted[idx] == ' ' && emitted[idx + 1] == '.' && emitted[idx + 2] == '.' && emitted[idx + 3] == ' ')
            {
                return true;
            }
            idx++;
        }
        return false;
    }

    /// <summary>
    /// Returns true if the expression is a known string-typed variable (param, local, or field).
    /// </summary>
    private bool HasStringTypedOperand(ExpressionSyntax expr)
    {
        if (expr.Kind == 8616) // IdentifierName
        {
            IdentifierNameSyntax id = (IdentifierNameSyntax)expr;
            string name = id.Identifier.Text;
            string varType = GetVariableType(name);
            if (varType != null) return IsStringType(varType);
            if (!_isStaticContext)
            {
                string fieldType = GetFieldType(name);
                if (fieldType != null) return IsStringType(fieldType);
            }
        }
        return false;
    }

    /// <summary>
    /// Returns true if the C# type is an integer type (not float/double).
    /// </summary>
    private bool IsIntegerType(string typeName)
    {
        if (typeName == null) return false;
        if (typeName == "int") return true;
        if (typeName == "long") return true;
        if (typeName == "short") return true;
        if (typeName == "byte") return true;
        if (typeName == "sbyte") return true;
        if (typeName == "ushort") return true;
        if (typeName == "uint") return true;
        if (typeName == "ulong") return true;
        if (typeName == "char") return true;
        return false;
    }

    /// <summary>
    /// Returns true if the expression is known to be integer-typed.
    /// Checks: integer literals, known int-typed variables/fields.
    /// </summary>
    private bool IsIntegerExpression(ExpressionSyntax expr)
    {
        // Integer literal
        if (expr.Kind == 8750) return true; // NumericLiteral (assume integer unless has '.')

        // Identifier: check variable/field types
        if (expr.Kind == 8616) // IdentifierName
        {
            IdentifierNameSyntax id = (IdentifierNameSyntax)expr;
            string name = id.Identifier.Text;
            string varType = GetVariableType(name);
            if (varType != null) return IsIntegerType(varType);
            if (!_isStaticContext)
            {
                string fieldType = GetFieldType(name);
                if (fieldType != null) return IsIntegerType(fieldType);
            }
        }

        // Binary expression: result of integer arithmetic is integer
        if (expr.Kind >= 8668 && expr.Kind <= 8688)
        {
            BinaryExpressionSyntax bin = (BinaryExpressionSyntax)expr;
            string op = bin.OperatorToken.Text;
            if (op == "+" || op == "-" || op == "*" || op == "/" || op == "%")
            {
                return IsIntegerExpression(bin.Left) && IsIntegerExpression(bin.Right);
            }
        }

        return false;
    }

    /// <summary>
    /// Returns true if the expression is a known char-typed variable.
    /// </summary>
    private bool IsCharTypedExpression(ExpressionSyntax expr)
    {
        if (expr.Kind == 8616) // IdentifierName
        {
            IdentifierNameSyntax id = (IdentifierNameSyntax)expr;
            string name = id.Identifier.Text;
            string varType = GetVariableType(name);
            if (varType == "char") return true;
        }
        return false;
    }

    /// <summary>
    /// Wraps a char-typed expression in string.char() for use in string concatenation.
    /// </summary>
    private string WrapCharForConcat(ExpressionSyntax expr, string emitted)
    {
        if (expr.Kind == 8752) // CharacterLiteralExpression → already a number, wrap
        {
            return "string.char(" + emitted + ")";
        }
        if (IsCharTypedExpression(expr))
        {
            return "string.char(" + emitted + ")";
        }
        // Cast expression to char: (char)(expr) → string.char(expr)
        if (expr.Kind == 8640) // CastExpression
        {
            CastExpressionSyntax cast = (CastExpressionSyntax)expr;
            if (cast.TypeName == "char")
            {
                return "string.char(" + emitted + ")";
            }
        }
        return emitted;
    }

    // ── Assignment expression ─────────────────────────────────
    private string EmitAssignment(ExpressionSyntax expr)
    {
        AssignmentExpressionSyntax assign = (AssignmentExpressionSyntax)expr;
        string left = EmitExpression(assign.Left);
        string right = EmitExpression(assign.Right);
        int kind = expr.Kind;

        if (kind == 8714) return left + " = " + right;
        if (kind == 8715)
        {
            // += on strings → ..=
            if (assign.Right.Kind == 8751) return left + " ..= " + right;
            if (assign.Right.Kind >= 8668 && assign.Right.Kind <= 8688)
            {
                if (HasStringLiteralInChain(assign.Right)) return left + " ..= " + right;
            }
            if (ContainsConcatOp(right)) return left + " ..= " + right;
            return left + " += " + right;
        }
        if (kind == 8716) return left + " -= " + right;
        if (kind == 8717) return left + " *= " + right;
        if (kind == 8718) return left + " /= " + right;
        if (kind == 8719) return left + " %= " + right;

        return left + " = " + right;
    }

    // ── Member access ─────────────────────────────────────────
    private string EmitMemberAccess(ExpressionSyntax expr)
    {
        MemberAccessExpressionSyntax ma = (MemberAccessExpressionSyntax)expr;
        string memberName = ma.Name.Text;
        string obj = EmitExpression(ma.Expression);

        // .Length / .Count → # operator
        if (memberName == "Length" || memberName == "Count")
        {
            return "#" + obj;
        }

        // Console.Write / Console.WriteLine → print (handled at invocation level too)
        if (obj == "Console" && memberName == "WriteLine") return "print";
        if (obj == "Console" && memberName == "Write") return "print";

        // Math.X → math.X
        if (obj == "Math")
        {
            string luauMath = MapMathMember(memberName);
            if (luauMath != null) return luauMath;
        }

        // string static helpers
        if (obj == "string" && memberName == "Empty") return "\"\"";

        // this.X / self.X → self.X
        if (obj == "this" || obj == "self")
        {
            return "self." + memberName;
        }

        // base.X → BaseClass.X (for field access via metatable chain, use self.X)
        if (obj == "base")
        {
            if (_baseClassName != null)
            {
                return _baseClassName + "." + memberName;
            }
            return _currentClassName + "." + memberName;
        }

        return obj + "." + memberName;
    }

    private string MapMathMember(string member)
    {
        if (member == "Max") return "math.max";
        if (member == "Min") return "math.min";
        if (member == "Abs") return "math.abs";
        if (member == "Floor") return "math.floor";
        if (member == "Ceiling") return "math.ceil";
        if (member == "Round") return "math.round";
        if (member == "Sqrt") return "math.sqrt";
        if (member == "Pow") return "math.pow";
        if (member == "Log") return "math.log";
        if (member == "PI") return "math.pi";
        if (member == "E") return "math.exp(1)";
        return null;
    }

    /// <summary>
    /// Returns true if the given identifier name is a known variable (parameter or local),
    /// meaning method calls on it should use colon syntax.
    /// </summary>
    /// <summary>
    /// Returns true if the given name is a known instance method of the current class.
    /// </summary>
    private bool IsInstanceMethod(string name)
    {
        for (int i = 0; i < _methodCount; i++)
        {
            if (_methodNames[i] == name && !_isMethodStatic[i]) return true;
        }
        return false;
    }

    /// <summary>
    /// Returns true if the given name is a known static method of the current class.
    /// </summary>
    private bool IsStaticMethod(string name)
    {
        for (int i = 0; i < _methodCount; i++)
        {
            if (_methodNames[i] == name && _isMethodStatic[i]) return true;
        }
        return false;
    }

    private bool IsKnownVariable(string name)
    {
        for (int i = 0; i < _paramCount; i++)
        {
            if (_paramNames[i] == name) return true;
        }
        for (int i = 0; i < _localCount; i++)
        {
            if (_localNames[i] == name) return true;
        }
        return false;
    }

    /// <summary>
    /// Returns true if the expression on the left of a member-access call is an instance
    /// (should use colon syntax) rather than a type name (should use dot syntax).
    /// Heuristic: self, self.field, known param/local, element access → instance.
    /// Single uppercase identifier not in params/locals → type name → dot.
    /// </summary>
    private bool IsInstanceCallTarget(ExpressionSyntax target, string emittedObj)
    {
        // self → always instance
        if (emittedObj == "self") return true;

        // self.field → instance
        if (emittedObj.Length > 5 && emittedObj.Substring(0, 5) == "self.") return true;

        // Element access result (e.g. self.Items[i + 1]) → instance
        if (target.Kind == 8690) return true; // ElementAccess

        // Known parameter or local variable → instance
        if (target.Kind == 8616) // IdentifierName
        {
            IdentifierNameSyntax id = (IdentifierNameSyntax)target;
            if (IsKnownVariable(id.Identifier.Text)) return true;
        }

        // Member access on a known variable (e.g. walker.Something) → instance
        if (target.Kind == 8689) // MemberAccess
        {
            MemberAccessExpressionSyntax inner = (MemberAccessExpressionSyntax)target;
            if (inner.Expression.Kind == 8616) // left side is identifier
            {
                IdentifierNameSyntax leftId = (IdentifierNameSyntax)inner.Expression;
                if (IsKnownVariable(leftId.Identifier.Text)) return true;
            }
            // Recursive: if left side is self → instance
            if (inner.Expression.Kind == 8616)
            {
                IdentifierNameSyntax leftId2 = (IdentifierNameSyntax)inner.Expression;
                if (leftId2.Identifier.Text == "self" || leftId2.Identifier.Text == "this") return true;
            }
        }

        // Default: single uppercase identifier → likely type name → dot
        return false;
    }

    // ── Invocation ────────────────────────────────────────────
    private string EmitInvocation(ExpressionSyntax expr)
    {
        InvocationExpressionSyntax inv = (InvocationExpressionSyntax)expr;

        // Build argument list
        string args = "";
        for (int i = 0; i < inv.Arguments.Length; i++)
        {
            if (i > 0) args = args + ", ";
            args = args + EmitExpression(inv.Arguments[i]);
        }

        // Member-access call: obj.Method(args)
        if (inv.Expression.Kind == 8689) // MemberAccess
        {
            MemberAccessExpressionSyntax ma = (MemberAccessExpressionSyntax)inv.Expression;
            string methodName = ma.Name.Text;
            string obj = EmitExpression(ma.Expression);

            // Console.WriteLine / Console.Write → print(args)
            if (obj == "Console" && (methodName == "WriteLine" || methodName == "Write"))
            {
                return "print(" + args + ")";
            }

            // string.IsNullOrEmpty(s) → (s == nil or #s == 0)
            if (obj == "string" && methodName == "IsNullOrEmpty")
            {
                return "(" + args + " == nil or #" + args + " == 0)";
            }

            // StringBuilder methods (we model StringBuilder as a plain string)
            if (methodName == "Append")
            {
                return obj + " = " + obj + " .. " + args;
            }
            if (methodName == "AppendLine")
            {
                if (args.Length > 0)
                {
                    return obj + " = " + obj + " .. " + args + " .. \"\\n\"";
                }
                return obj + " = " + obj + " .. \"\\n\"";
            }
            if (methodName == "ToString" && inv.Arguments.Length == 0)
            {
                return "tostring(" + obj + ")";
            }

            // List / array methods
            if (methodName == "Add")
            {
                return "table.insert(" + obj + ", " + args + ")";
            }
            if (methodName == "Clear")
            {
                return "table.clear(" + obj + ")";
            }
            if (methodName == "Contains")
            {
                return "table.find(" + obj + ", " + args + ") ~= nil";
            }
            if (methodName == "Insert")
            {
                return "table.insert(" + obj + ", " + args + ")";
            }
            if (methodName == "RemoveAt")
            {
                return "table.remove(" + obj + ", " + args + " + 1)";
            }

            // string instance methods
            if (methodName == "Substring")
            {
                if (inv.Arguments.Length == 1)
                {
                    return "string.sub(" + obj + ", " + args + " + 1)";
                }
                if (inv.Arguments.Length == 2)
                {
                    string start = EmitExpression(inv.Arguments[0]);
                    string len = EmitExpression(inv.Arguments[1]);
                    return "string.sub(" + obj + ", " + start + " + 1, " + start + " + " + len + ")";
                }
            }
            if (methodName == "IndexOf")
            {
                // If the argument is a char literal (emitted as number), wrap with string.char()
                string findArg = args;
                if (inv.Arguments.Length == 1 && inv.Arguments[0].Kind == 8752) // CharacterLiteral
                {
                    findArg = "string.char(" + args + ")";
                }
                return "(string.find(" + obj + ", " + findArg + ", 1, true) or 0) - 1";
            }
            if (methodName == "StartsWith")
            {
                return "string.sub(" + obj + ", 1, #" + args + ") == " + args;
            }
            if (methodName == "EndsWith")
            {
                return "string.sub(" + obj + ", -#" + args + ") == " + args;
            }
            if (methodName == "Trim")
            {
                return "string.match(" + obj + ", \"^%s*(.-)%s*$\")";
            }
            if (methodName == "ToLower")
            {
                return "string.lower(" + obj + ")";
            }
            if (methodName == "ToUpper")
            {
                return "string.upper(" + obj + ")";
            }
            if (methodName == "Replace")
            {
                return "string.gsub(" + obj + ", " + args + ")";
            }

            // base.Method(args) → BaseClass.Method(self, args)
            if (obj == "base" && _baseClassName != null)
            {
                if (args.Length > 0)
                {
                    return _baseClassName + "." + methodName + "(self, " + args + ")";
                }
                return _baseClassName + "." + methodName + "(self)";
            }

            // Determine colon vs dot syntax
            if (IsInstanceCallTarget(ma.Expression, obj))
            {
                // Instance call: obj:Method(args)
                return obj + ":" + methodName + "(" + args + ")";
            }

            return obj + "." + methodName + "(" + args + ")";
        }

        // Direct call: callee(args)
        // Check for bare instance/static method calls in current class
        if (inv.Expression.Kind == 8616) // IdentifierName
        {
            IdentifierNameSyntax calleeId = (IdentifierNameSyntax)inv.Expression;
            string methodName = calleeId.Identifier.Text;

            // Bare instance method: ClassName.Method(self, args)
            if (!_isStaticContext && _currentClassName.Length > 0 && IsInstanceMethod(methodName))
            {
                if (args.Length > 0)
                {
                    return _currentClassName + "." + methodName + "(self, " + args + ")";
                }
                return _currentClassName + "." + methodName + "(self)";
            }

            // Bare static method: ClassName.Method(args)
            if (_currentClassName.Length > 0 && IsStaticMethod(methodName))
            {
                return _currentClassName + "." + methodName + "(" + args + ")";
            }
        }

        string callee = EmitExpression(inv.Expression);
        return callee + "(" + args + ")";
    }

    // ── Object creation ───────────────────────────────────────
    private string EmitObjectCreation(ExpressionSyntax expr)
    {
        ObjectCreationExpressionSyntax obj = (ObjectCreationExpressionSyntax)expr;

        string args = "";
        for (int i = 0; i < obj.Arguments.Length; i++)
        {
            if (i > 0) args = args + ", ";
            args = args + EmitExpression(obj.Arguments[i]);
        }

        string typeName = obj.TypeName;

        // new StringBuilder() → "" (model as plain string)
        if (typeName == "StringBuilder") return "\"\"";

        // Collection constructors → empty table
        if (typeName.Length > 5 && typeName.Substring(0, 5) == "List<") return "{}";
        if (typeName.Length > 11 && typeName.Substring(0, 11) == "Dictionary<") return "{}";
        if (typeName.Length > 8 && typeName.Substring(0, 8) == "HashSet<") return "{}";

        // Exception types → their message string (used with error())
        if (typeName == "Exception"
            || typeName == "InvalidOperationException"
            || typeName == "ArgumentException"
            || typeName == "ArgumentNullException"
            || typeName == "NotImplementedException"
            || typeName == "NotSupportedException"
            || typeName == "IndexOutOfRangeException"
            || typeName == "OverflowException")
        {
            if (obj.Arguments.Length > 0)
            {
                return EmitExpression(obj.Arguments[0]);
            }
            return "\"" + typeName + "\"";
        }

        // Object initializer: new T() { Field = val, ... }
        // Emit as an immediately-invoked function expression to produce a value
        if (obj.Initializers.Length > 0)
        {
            string iife = "(function() local __obj = " + typeName + ".new(" + args + "); ";
            for (int i = 0; i < obj.Initializers.Length; i++)
            {
                string fieldName = EmitExpression(obj.Initializers[i].Left);
                string fieldVal = EmitExpression(obj.Initializers[i].Right);
                iife = iife + "__obj." + fieldName + " = " + fieldVal + "; ";
            }
            iife = iife + "return __obj end)()";
            return iife;
        }

        return typeName + ".new(" + args + ")";
    }

    /// <summary>
    /// Returns the C# type name for an identifier if it is a known variable.
    /// Checks params, locals, and instance fields (via self.X).
    /// Returns null if not found.
    /// </summary>
    private string GetVariableType(string name)
    {
        for (int i = 0; i < _paramCount; i++)
        {
            if (_paramNames[i] == name) return _paramTypes[i];
        }
        for (int i = 0; i < _localCount; i++)
        {
            if (_localNames[i] == name) return _localTypes[i];
        }
        return null;
    }

    /// <summary>
    /// Returns true if the given C# type name is a string type.
    /// </summary>
    private bool IsStringType(string typeName)
    {
        if (typeName == null) return false;
        if (typeName == "string") return true;
        if (typeName == "String") return true;
        return false;
    }

    /// <summary>
    /// Returns the C# type of an instance field by name, or null if not found.
    /// </summary>
    private string GetFieldType(string fieldName)
    {
        for (int i = 0; i < _fieldCount; i++)
        {
            if (_fieldNames[i] == fieldName) return _fieldTypes[i];
        }
        return null;
    }

    /// <summary>
    /// Determines if the expression being indexed is a string.
    /// Checks identifier types (params, locals, fields) and self.field types.
    /// </summary>
    private bool IsStringExpression(ExpressionSyntax expr)
    {
        // Simple identifier: check params, locals, then fields
        if (expr.Kind == 8616) // IdentifierName
        {
            IdentifierNameSyntax id = (IdentifierNameSyntax)expr;
            string name = id.Identifier.Text;
            string varType = GetVariableType(name);
            if (varType != null) return IsStringType(varType);
            // Also check instance fields (bare field access without this.)
            if (!_isStaticContext)
            {
                string fieldType = GetFieldType(name);
                if (fieldType != null) return IsStringType(fieldType);
            }
        }

        // Member access: self.field or this.field → check field types
        if (expr.Kind == 8689) // MemberAccess
        {
            MemberAccessExpressionSyntax ma = (MemberAccessExpressionSyntax)expr;
            if (ma.Expression.Kind == 8616) // left is identifier
            {
                IdentifierNameSyntax leftId = (IdentifierNameSyntax)ma.Expression;
                string leftName = leftId.Identifier.Text;
                if (leftName == "this" || leftName == "self")
                {
                    string fieldType = GetFieldType(ma.Name.Text);
                    if (fieldType != null) return IsStringType(fieldType);
                }
            }
        }

        return false;
    }

    // ── Element access ────────────────────────────────────────
    private string EmitElementAccess(ExpressionSyntax expr)
    {
        ElementAccessExpressionSyntax ea = (ElementAccessExpressionSyntax)expr;
        string obj = EmitExpression(ea.Expression);
        string index = EmitExpression(ea.Index);

        // Detect string character indexing: str[i] → string.byte(str, i + 1)
        bool isStringIndex = IsStringExpression(ea.Expression);

        if (isStringIndex)
        {
            // Convert 0-based literal index to 1-based for string.byte
            if (ea.Index.Kind == 8750) // NumericLiteral
            {
                LiteralExpressionSyntax lit = (LiteralExpressionSyntax)ea.Index;
                string numText = lit.Token.Text;
                int numVal = 0;
                bool isSimple = true;
                for (int i = 0; i < numText.Length; i++)
                {
                    char c = numText[i];
                    if (c >= '0' && c <= '9')
                    {
                        numVal = numVal * 10 + (c - '0');
                    }
                    else
                    {
                        isSimple = false;
                    }
                }
                if (isSimple)
                {
                    return "string.byte(" + obj + ", " + IntToString(numVal + 1) + ")";
                }
            }
            return "string.byte(" + obj + ", " + index + " + 1)";
        }

        // Non-string: regular array indexing with 0→1 conversion
        if (ea.Index.Kind == 8750) // NumericLiteral
        {
            LiteralExpressionSyntax lit = (LiteralExpressionSyntax)ea.Index;
            string numText = lit.Token.Text;
            int numVal = 0;
            bool isSimple = true;
            for (int i = 0; i < numText.Length; i++)
            {
                char c = numText[i];
                if (c >= '0' && c <= '9')
                {
                    numVal = numVal * 10 + (c - '0');
                }
                else
                {
                    isSimple = false;
                }
            }
            if (isSimple)
            {
                return obj + "[" + IntToString(numVal + 1) + "]";
            }
        }

        // Non-literal index: add + 1 at runtime
        return obj + "[" + index + " + 1]";
    }

    // ── Lambda ────────────────────────────────────────────────
    private string EmitLambda(ExpressionSyntax expr)
    {
        LambdaExpressionSyntax lam = (LambdaExpressionSyntax)expr;

        string parms = "";
        for (int i = 0; i < lam.ParameterNames.Length; i++)
        {
            if (i > 0) parms = parms + ", ";
            parms = parms + lam.ParameterNames[i];
        }

        if (lam.ExpressionBody != null)
        {
            return "function(" + parms + ") return " + EmitExpression(lam.ExpressionBody) + " end";
        }

        if (lam.BlockBody != null)
        {
            // Save and swap output buffer to capture the block body as a string
            string savedOutput = _output;
            int savedIndent = _indent;
            _output = "";
            _indent = 0;
            EmitBlockBody(lam.BlockBody);
            string body = _output;
            _output = savedOutput;
            _indent = savedIndent;

            // Trim trailing newline
            if (body.Length > 0 && body[body.Length - 1] == '\n')
            {
                body = body.Substring(0, body.Length - 1);
            }
            return "function(" + parms + ")\n" + body + "\nend";
        }

        return "function(" + parms + ") end";
    }

    // ── Switch expression ─────────────────────────────────────
    private string EmitSwitchExpression(ExpressionSyntax expr)
    {
        SwitchExpressionSyntax sw = (SwitchExpressionSyntax)expr;
        string govExpr = EmitExpression(sw.GoverningExpression);

        string result = "";
        for (int i = 0; i < sw.Arms.Length; i++)
        {
            SwitchExpressionArmSyntax arm = sw.Arms[i];
            string armExpr = EmitExpression(arm.Expression);

            if (arm.Pattern == null)
            {
                // Default arm: _ => value
                if (result.Length == 0)
                {
                    result = armExpr;
                }
                else
                {
                    result = result + " else " + armExpr;
                }
            }
            else
            {
                string patternExpr = EmitExpression(arm.Pattern);
                if (result.Length == 0)
                {
                    result = "if " + govExpr + " == " + patternExpr + " then " + armExpr;
                }
                else
                {
                    result = result + " elseif " + govExpr + " == " + patternExpr + " then " + armExpr;
                }
            }
        }

        return result;
    }

    // ── Utility: integer to string without string interpolation ──
    private string IntToString(int value)
    {
        if (value == 0) return "0";

        bool negative = false;
        if (value < 0)
        {
            negative = true;
            value = -value;
        }

        string result = "";
        int n = value;
        while (n > 0)
        {
            int digit = n % 10;
            char c = (char)('0' + digit);
            result = c + result;
            n = n / 10;
        }

        if (negative) result = "-" + result;
        return result;
    }
}
